/**
 * One-shot: densify grammar quizzes
 */
const fs = require("fs");
const path = "data/quizzes.json";
const quizzes = JSON.parse(fs.readFileSync(path, "utf8"));
let maxId = 0;
quizzes.forEach((q) => {
  const m = String(q.id || "").match(/^q(\d+)$/);
  if (m) maxId = Math.max(maxId, Number(m[1]));
});

const add = [
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:be-verbs",
    question: "Choose the correct sentence:",
    question_bn: "সঠিক বাক্যটি বেছে নিন:",
    options: ["I am happy.", "I is happy.", "I are happy.", "I be happy."],
    answer: "I am happy.",
    explanation: "I + am.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:be-verbs",
    question: "She ___ my sister.",
    question_bn: "সঠিক be verb:",
    options: ["is", "am", "are", "be"],
    answer: "is",
    explanation: "he/she/it + is.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:be-verbs",
    question: "You ___ late today.",
    question_bn: "সঠিক be verb:",
    options: ["are", "is", "am", "be"],
    answer: "are",
    explanation: "you/we/they + are.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:present-simple",
    question: "She ___ tea every morning.",
    question_bn: "সঠিক রূপ:",
    options: ["drinks", "drink", "drinking", "drank"],
    answer: "drinks",
    explanation: "he/she/it + -s.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:present-simple",
    question: "They ___ in Dhaka.",
    question_bn: "সঠিক রূপ:",
    options: ["live", "lives", "living", "lived"],
    answer: "live",
    explanation: "I/you/we/they + base verb.",
  },
  {
    type: "type",
    skill: "grammar",
    item_id: "grammar:present-simple",
    question: "Make negative: He likes coffee.",
    question_bn: "নেগেটিভ বানান:",
    answer: "He doesn't like coffee.",
    answers: ["He does not like coffee.", "He doesn't like coffee."],
    explanation: "does not + base verb.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:present-continuous",
    question: "Look! It ___ now.",
    question_bn: "সঠিক রূপ:",
    options: ["is raining", "rains", "rain", "rained"],
    answer: "is raining",
    explanation: "now → Present Continuous.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:present-continuous",
    question: "I ___ English this month.",
    question_bn: "সঠিক রূপ:",
    options: ["am learning", "learn", "learns", "learned"],
    answer: "am learning",
    explanation: "temporary action → am + -ing.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:past-simple",
    question: "Yesterday she ___ to school.",
    question_bn: "সঠিক রূপ:",
    options: ["went", "go", "goes", "going"],
    answer: "went",
    explanation: "go → went.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:past-simple",
    question: "___ you finish the work?",
    question_bn: "সঠিক auxiliary:",
    options: ["Did", "Do", "Does", "Are"],
    answer: "Did",
    explanation: "Past questions use Did + base verb.",
  },
  {
    type: "type",
    skill: "grammar",
    item_id: "grammar:past-simple",
    question: "Negative: They came early.",
    question_bn: "নেগেটিভ:",
    answer: "They did not come early.",
    answers: ["They didn't come early.", "They did not come early."],
    explanation: "did not + base verb.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:modals-can-should",
    question: "You ___ drink more water.",
    question_bn: "সঠিক modal:",
    options: ["should", "should to", "can to", "must to"],
    answer: "should",
    explanation: "should + base verb (no to).",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:modals-can-should",
    question: "___ you help me, please?",
    question_bn: "সঠিক:",
    options: ["Can", "Should", "Are", "Do"],
    answer: "Can",
    explanation: "Can for ability/request.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:subject-verb-agreement",
    question: "The news ___ good.",
    question_bn: "সঠিক:",
    options: ["is", "are", "am", "be"],
    answer: "is",
    explanation: "news is singular.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:subject-verb-agreement",
    question: "My friends ___ here.",
    question_bn: "সঠিক:",
    options: ["are", "is", "am", "be"],
    answer: "are",
    explanation: "plural subject → are.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:articles",
    question: "I bought ___ umbrella.",
    question_bn: "সঠিক article:",
    options: ["an", "a", "the", "no article"],
    answer: "an",
    explanation: "umbrella → vowel sound → an.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:articles",
    question: "___ sun rises in the east.",
    question_bn: "সঠিক:",
    options: ["The", "A", "An", "No article"],
    answer: "The",
    explanation: "unique things take the.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:prepositions-in-on-at",
    question: "The meeting is ___ Monday.",
    question_bn: "সঠিক:",
    options: ["on", "in", "at", "to"],
    answer: "on",
    explanation: "days → on.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:prepositions-in-on-at",
    question: "I wake up ___ 6 a.m.",
    question_bn: "সঠিক:",
    options: ["at", "in", "on", "to"],
    answer: "at",
    explanation: "clock times → at.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:prepositions-in-on-at",
    question: "She was born ___ 1998.",
    question_bn: "সঠিক:",
    options: ["in", "on", "at", "to"],
    answer: "in",
    explanation: "years → in.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:countable-uncountable",
    question: "There isn't ___ milk left.",
    question_bn: "সঠিক:",
    options: ["much", "many", "a", "few"],
    answer: "much",
    explanation: "uncountable → much.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:countable-uncountable",
    question: "How ___ apples do you want?",
    question_bn: "সঠিক:",
    options: ["many", "much", "a lot", "more of"],
    answer: "many",
    explanation: "countable plural → many.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:present-perfect",
    question: "I ___ finished my homework.",
    question_bn: "সঠিক:",
    options: ["have", "has", "am", "did"],
    answer: "have",
    explanation: "I/you/we/they + have + past participle.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:present-perfect",
    question: "She ___ lived here for five years.",
    question_bn: "সঠিক:",
    options: ["has", "have", "is", "did"],
    answer: "has",
    explanation: "he/she/it + has.",
  },
  {
    type: "mcq",
    skill: "grammar",
    item_id: "grammar:present-perfect",
    question: "Choose the correct sentence:",
    question_bn: "সঠিক বাক্য:",
    options: [
      "Have you ever been to Cox's Bazar?",
      "Did you ever been to Cox's Bazar?",
      "Have you ever go to Cox's Bazar?",
      "Has you ever been to Cox's Bazar?",
    ],
    answer: "Have you ever been to Cox's Bazar?",
    explanation: "Have + subject + past participle.",
  },
  {
    type: "type",
    skill: "grammar",
    item_id: "grammar:present-perfect",
    question: "Make Present Perfect: I / see / that film",
    question_bn: "Present Perfect লিখুন:",
    answer: "I have seen that film.",
    answers: ["I have seen that film.", "I've seen that film."],
    explanation: "have + past participle (see→seen).",
  },
];

add.forEach((q, i) => {
  q.id = "q" + (maxId + 1 + i);
  quizzes.push(q);
});

fs.writeFileSync(path, JSON.stringify(quizzes, null, 2) + "\n");
const g = quizzes.filter((x) => x.skill === "grammar");
const by = {};
g.forEach((x) => {
  by[x.item_id] = (by[x.item_id] || 0) + 1;
});
console.log("added", add.length, "grammar total", g.length);
console.log(by);
