# -*- coding: utf-8 -*-
"""Add B1+ verbs to the bank and grow Verb Forms study lists. Bank may keep A1/A2; lists do not."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from cefr_policy import keep_word, list_cefr_label  # noqa: E402

VERB_DATA = ROOT / "data" / "verb-forms.json"
VLISTS = ROOT / "data" / "vocabulary-lists.json"

MIN_SIZE = 80
CEFR_OK = {"B1", "B2", "C1", "C2"}
VF_IDS = (
    "vf-daily-conversation",
    "vf-regular-starter",
    "vf-irregular-core",
    "vf-ielts-speaking",
    "vf-ielts-writing",
    "vf-ielts-reading",
    "verb-forms-master",
)
BAG = {
    "D": "vf-daily-conversation",
    "R": "vf-regular-starter",
    "I": "vf-irregular-core",
    "S": "vf-ielts-speaking",
    "W": "vf-ielts-writing",
    "G": "vf-ielts-reading",
}
DOUBLE = {
    "admit", "commit", "control", "occur", "omit", "permit", "prefer", "refer",
    "regret", "submit", "transfer", "cancel", "travel", "label", "level", "model",
    "signal", "enrol", "fulfil", "counsel", "equip",
}


def slug(w: str) -> str:
    return "verb:" + re.sub(r"[^a-z0-9]+", "-", w.strip().lower()).strip("-")


def reg_forms(v1: str) -> tuple[str, str, str, str]:
    w = v1.lower()
    if w in DOUBLE:
        v2 = w + w[-1] + "ed"
        v4 = w + w[-1] + "ing"
    elif w.endswith("ie"):
        v2 = w + "d"
        v4 = w[:-2] + "ying"
    elif w.endswith("e") and not w.endswith(("ee", "oe", "ye")):
        v2 = w + "d"
        v4 = w[:-1] + "ing"
    elif len(w) > 1 and w[-1] == "y" and w[-2] not in "aeiou":
        v2 = w[:-1] + "ied"
        v4 = w + "ing"
    else:
        v2 = w + "ed"
        v4 = w + "ing"
    if len(w) > 1 and w[-1] == "y" and w[-2] not in "aeiou":
        v5 = w[:-1] + "ies"
    elif w.endswith(("s", "sh", "ch", "x", "z", "o")):
        v5 = w + "es"
    else:
        v5 = w + "s"
    return v2, v2, v4, v5


def V(
    v1: str,
    phonetic: str,
    meaning_en: str,
    meaning_bn: str,
    present: str,
    present_bn: str,
    past: str,
    past_bn: str,
    *,
    cefr: str = "B1",
    category: str = "daily",
    irregular: bool = False,
    v2: str = "",
    v3: str = "",
    v4: str = "",
    v5: str = "",
    bags: str = "DR",
    tags: list[str] | None = None,
    perfect: str = "",
    perfect_bn: str = "",
    continuous: str = "",
    continuous_bn: str = "",
    gerund_ex: str = "",
    gerund_ex_bn: str = "",
    part_ex: str = "",
    part_ex_bn: str = "",
) -> dict:
    if cefr not in CEFR_OK:
        raise ValueError(f"B1+ only: {v1} ({cefr})")
    if irregular:
        if not all([v2, v3, v4, v5]):
            raise ValueError(f"irregular needs forms: {v1}")
    else:
        v2, v3, v4, v5 = reg_forms(v1)
    lists = [BAG[ch] for ch in bags if ch in BAG]
    return {
        "id": slug(v1),
        "v1": v1,
        "v2": v2,
        "v3": v3,
        "v4": v4,
        "v5": v5,
        "phonetic": phonetic,
        "meaning_en": meaning_en,
        "meaning_bn": meaning_bn,
        "cefr": cefr,
        "category": category,
        "irregular": irregular,
        "examples": {
            "present": present,
            "present_bn": present_bn,
            "past": past,
            "past_bn": past_bn,
            "perfect": perfect or f"They have {v3} this already.",
            "perfect_bn": perfect_bn or "তারা ইতিমধ্যে এটা করেছে।",
            "continuous": continuous or f"She is {v4} it now.",
            "continuous_bn": continuous_bn or "সে এখন এটা করছে।",
        },
        "gerund_use": f"Gerund ({v4}) — as subject or after enjoy/avoid/keep",
        "gerund_example": gerund_ex or f"{v4.capitalize()} regularly makes a difference.",
        "gerund_example_bn": gerund_ex_bn or "নিয়মিত করলে পার্থক্য হয়।",
        "participle_use": f"Past participle ({v3}) — perfect tenses and passive",
        "participle_example": part_ex or f"The issue has been {v3}.",
        "participle_example_bn": part_ex_bn or "বিষয়টি হয়ে গেছে।",
        "tags": tags or ["verb", "grammar"],
        "_lists": lists,
    }


NEW = [
    # ── irregular B1+ ────────────────────────────────────────────────────────
    V("beat", "/biːt/", "to defeat; to hit repeatedly", "হারানো / বারবার আঘাত করা",
      "Good preparation can beat exam stress.", "ভালো প্রস্তুতি পরীক্ষার চাপ হারাতে পারে।",
      "Our team beat the champions last season.", "গত সিজনে আমাদের দল চ্যাম্পিয়নদের হারিয়েছিল।",
      cefr="B1", category="daily", irregular=True, v2="beat", v3="beaten", v4="beating", v5="beats", bags="DIS"),
    V("bear", "/beə/", "to accept or endure something difficult", "সহ্য করা / বহন করা",
      "I cannot bear noisy neighbours.", "আমি হৈচৈ করা প্রতিবেশী সহ্য করতে পারি না।",
      "She bore the criticism calmly.", "সে সমালোচনা শান্তভাবে সহ্য করেছিল।",
      cefr="B2", category="daily", irregular=True, v2="bore", v3="borne", v4="bearing", v5="bears", bags="DISG"),
    V("bind", "/baɪnd/", "to tie; to unite people with a duty", "বাঁধা / বাধ্য করা",
      "Contracts bind both sides.", "চুক্তি দুই পক্ষকে বাধ্য করে।",
      "The agreement bound the suppliers.", "চুক্তি সরবরাহকারীদের বাধ্য করেছিল।",
      cefr="B2", category="office", irregular=True, v2="bound", v3="bound", v4="binding", v5="binds", bags="IRWG"),
    V("bleed", "/bliːd/", "to lose blood; to drain money or colour", "রক্তপাত হওয়া / ক্ষয় হওয়া",
      "The company is bleeding cash.", "কোম্পানি নগদ অর্থ হারাচ্ছে।",
      "He bled after the accident.", "দুর্ঘটনার পর তার রক্তপাত হয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="bled", v3="bled", v4="bleeding", v5="bleeds", bags="DIG"),
    V("breed", "/briːd/", "to cause something to develop; to keep animals", "জন্ম দেওয়া / প্রজনন করানো",
      "Poverty can breed crime.", "দারিদ্র্য অপরাধ জন্মাতে পারে।",
      "They bred cattle on the farm.", "তারা খামারে গরু পালন করত।",
      cefr="B2", category="ielts", irregular=True, v2="bred", v3="bred", v4="breeding", v5="breeds", bags="IWG"),
    V("broadcast", "/ˈbrɔːdkɑːst/", "to send out a programme on TV or radio", "সম্প্রচার করা",
      "News channels broadcast live debates.", "নিউজ চ্যানেল লাইভ বিতর্ক সম্প্রচার করে।",
      "The speech was broadcast nationwide.", "বক্তৃতাটি দেশজুড়ে সম্প্রচার হয়েছিল।",
      cefr="B2", category="ielts", irregular=True, v2="broadcast", v3="broadcast", v4="broadcasting", v5="broadcasts", bags="ISWG"),
    V("burst", "/bɜːst/", "to break open suddenly", "ফেটে যাওয়া",
      "Pipes burst in freezing weather.", "তীব্র ঠান্ডায় পাইপ ফেটে যায়।",
      "The balloon burst during the party.", "পার্টিতে বেলুন ফেটে গিয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="burst", v3="burst", v4="bursting", v5="bursts", bags="DIG"),
    V("cast", "/kɑːst/", "to throw; to choose actors; to create doubt", "নিক্ষেপ করা / বাছাই করা",
      "Critics cast doubt on the figures.", "সমালোচকরা তথ্য নিয়ে সন্দেহ তোলেন।",
      "The director cast a new actor.", "পরিচালক নতুন অভিনেতা বাছাই করেছিলেন।",
      cefr="B2", category="ielts", irregular=True, v2="cast", v3="cast", v4="casting", v5="casts", bags="ISWG"),
    V("cling", "/klɪŋ/", "to hold tightly; to refuse to give up an idea", "আঁকড়ে ধরা",
      "Some voters cling to old habits.", "কিছু ভোটার পুরনো অভ্যাস আঁকড়ে থাকে।",
      "The child clung to her mother.", "বাচ্চাটি মাকে আঁকড়ে ধরেছিল।",
      cefr="B2", category="daily", irregular=True, v2="clung", v3="clung", v4="clinging", v5="clings", bags="DISG"),
    V("creep", "/kriːp/", "to move slowly and quietly; to increase gradually", "আস্তে আস্তে চলা / বাড়া",
      "Costs creep up every year.", "খরচ প্রতি বছর আস্তে আস্তে বাড়ে।",
      "Inflation crept into double digits.", "মুদ্রাস্ফীতি দুই অঙ্কে উঠে গিয়েছিল।",
      cefr="B2", category="ielts", irregular=True, v2="crept", v3="crept", v4="creeping", v5="creeps", bags="IWG"),
    V("flee", "/fliː/", "to run away from danger", "পালিয়ে যাওয়া",
      "Thousands flee conflict each year.", "প্রতি বছর হাজারো মানুষ সংঘাত থেকে পালায়।",
      "Families fled the flooded village.", "পরিবারগুলো বন্যাগ্রস্ত গ্রাম থেকে পালিয়েছিল।",
      cefr="B2", category="ielts", irregular=True, v2="fled", v3="fled", v4="fleeing", v5="flees", bags="ISWG"),
    V("fling", "/flɪŋ/", "to throw with force; to start something energetically", "জোরে ছুড়ে দেওয়া",
      "Do not fling accusations without proof.", "প্রমাণ ছাড়া অভিযোগ ছুড়ে দেবেন না।",
      "He flung the report onto the desk.", "সে রিপোর্টটা ডেস্কে ছুড়ে দিয়েছিল।",
      cefr="C1", category="daily", irregular=True, v2="flung", v3="flung", v4="flinging", v5="flings", bags="DIS"),
    V("forbid", "/fəˈbɪd/", "to refuse to allow", "নিষেধ করা",
      "The rules forbid late submissions.", "নিয়ম দেরিতে জমা নিষেধ করে।",
      "The court forbade further contact.", "আদালত আর যোগাযোগ নিষেধ করেছিল।",
      cefr="B2", category="office", irregular=True, v2="forbade", v3="forbidden", v4="forbidding", v5="forbids", bags="IRSG"),
    V("forecast", "/ˈfɔːkɑːst/", "to say what is likely to happen", "পূর্বাভাস দেওয়া",
      "Economists forecast slower growth.", "অর্থনীতিবিদরা মন্থর প্রবৃদ্ধির পূর্বাভাস দেন।",
      "The office forecast higher demand.", "অফিস বেশি চাহিদার পূর্বাভাস দিয়েছিল।",
      cefr="B1", category="ielts", irregular=True, v2="forecast", v3="forecast", v4="forecasting", v5="forecasts", bags="IRSWG"),
    V("foresee", "/fɔːˈsiː/", "to know something will happen", "আগে থেকে বোঝা",
      "Few people foresee a sudden crash.", "হঠাৎ পতন কম লোকেই আগে থেকে বোঝে।",
      "She foresaw the staffing problem.", "সে কর্মীসংকট আগেই দেখেছিল।",
      cefr="B2", category="ielts", irregular=True, v2="foresaw", v3="foreseen", v4="foreseeing", v5="foresees", bags="ISWG"),
    V("freeze", "/friːz/", "to become ice; to stop movement or funding", "জমে যাওয়া / স্থগিত করা",
      "Banks sometimes freeze suspicious accounts.", "ব্যাংক মাঝে মাঝে সন্দেহজনক অ্যাকাউন্ট স্থগিত করে।",
      "The lake froze overnight.", "হ্রদ রাতারাতি জমে গিয়েছিল।",
      cefr="B1", category="daily", irregular=True, v2="froze", v3="frozen", v4="freezing", v5="freezes", bags="DISW"),
    V("grind", "/ɡraɪnd/", "to crush into powder; to work hard in a dull way", "পেষা / কঠিন পরিশ্রম করা",
      "Students grind through past papers.", "শিক্ষার্থীরা পুরনো প্রশ্নপত্র নিয়ে খাটে।",
      "They ground the spices fresh.", "তারা মশলা তাজা পেষেছিল।",
      cefr="B2", category="daily", irregular=True, v2="ground", v3="ground", v4="grinding", v5="grinds", bags="DIS"),
    V("kneel", "/niːl/", "to go down on one or both knees", "হাঁটু গেড়ে বসা",
      "Protesters kneel in silence.", "বিক্ষোভকারীরা নীরবে হাঁটু গেড়ে বসে।",
      "He knelt to tie the child's shoe.", "সে বাচ্চার জুতা বাঁধতে হাঁটু গেড়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="knelt", v3="knelt", v4="kneeling", v5="kneels", bags="DIS"),
    V("lay", "/leɪ/", "to put something down carefully", "রাখা / বিছানো",
      "Please lay the documents on my desk.", "দয়া করে কাগজগুলো আমার ডেস্কে রাখুন।",
      "They laid a new road last year.", "গত বছর তারা নতুন রাস্তা বসিয়েছিল।",
      cefr="B1", category="daily", irregular=True, v2="laid", v3="laid", v4="laying", v5="lays", bags="DIRSW"),
    V("lean", "/liːn/", "to rest at an angle; to tend to support an idea", "হেলান দেওয়া / ঝোঁক থাকা",
      "I lean towards the cheaper option.", "আমি সস্তা অপশনের দিকেই ঝুঁকি।",
      "She leant against the wall.", "সে দেয়ালে হেলান দিয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="leant", v3="leant", v4="leaning", v5="leans", bags="DIS"),
    V("leap", "/liːp/", "to jump; to increase suddenly", "লাফানো / হঠাৎ বাড়া",
      "Sales leap in December.", "ডিসেম্বরে বিক্রি হঠাৎ বেড়ে যায়।",
      "Profits leapt after the launch.", "লঞ্চের পর মুনাফা লাফিয়ে উঠেছিল।",
      cefr="B2", category="ielts", irregular=True, v2="leapt", v3="leapt", v4="leaping", v5="leaps", bags="IWG"),
    V("mislead", "/ˌmɪsˈliːd/", "to make someone believe something false", "বিভ্রান্ত করা",
      "Headlines can mislead readers.", "শিরোনাম পাঠককে বিভ্রান্ত করতে পারে।",
      "The advert misled customers.", "বিজ্ঞাপনটি গ্রাহকদের বিভ্রান্ত করেছিল।",
      cefr="B2", category="ielts", irregular=True, v2="misled", v3="misled", v4="misleading", v5="misleads", bags="ISWG"),
    V("mistake", "/mɪˈsteɪk/", "to identify someone or something wrongly", "ভুল চেনা / ভুল করা",
      "Do not mistake silence for agreement.", "চুপ থাকা মানেই রাজি—এমন ভুল করবেন না।",
      "I mistook her for her sister.", "আমি তাকে তার বোন ভেবে ভুল করেছিলাম।",
      cefr="B2", category="daily", irregular=True, v2="mistook", v3="mistaken", v4="mistaking", v5="mistakes", bags="DISG"),
    V("offset", "/ˈɒfset/", "to balance an effect with an opposite one", "সমতা আনা / পুষিয়ে দেওয়া",
      "Tree planting can offset emissions.", "গাছ লাগালে নির্গমন পুষিয়ে দেওয়া যায়।",
      "Higher wages offset the extra hours.", "বেশি মজুরি অতিরিক্ত ঘণ্টা পুষিয়ে দিয়েছিল।",
      cefr="B2", category="ielts", irregular=True, v2="offset", v3="offset", v4="offsetting", v5="offsets", bags="IWG"),
    V("outdo", "/ˌaʊtˈduː/", "to do better than someone else", "ছাড়িয়ে যাওয়া",
      "Firms try to outdo their rivals.", "কোম্পানিগুলো প্রতিদ্বন্দ্বীকে ছাড়িয়ে যেতে চায়।",
      "She outdid her previous score.", "সে আগের স্কোর ছাড়িয়ে গিয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="outdid", v3="outdone", v4="outdoing", v5="outdoes", bags="DIS"),
    V("oversee", "/ˌəʊvəˈsiː/", "to watch and manage work", "তদারকি করা",
      "A supervisor oversees the night shift.", "একজন সুপারভাইজার নাইট শিফট তদারকি করেন।",
      "She oversaw the whole renovation.", "সে পুরো সংস্কার তদারকি করেছিল।",
      cefr="B2", category="office", irregular=True, v2="oversaw", v3="overseen", v4="overseeing", v5="oversees", bags="IRSW"),
    V("overtake", "/ˌəʊvəˈteɪk/", "to go past; to become bigger than", "ছাড়িয়ে যাওয়া",
      "Online sales overtake high-street shops.", "অনলাইন বিক্রি দোকানকে ছাড়িয়ে যায়।",
      "India overtook the previous record.", "ভারত আগের রেকর্ড ছাড়িয়ে গিয়েছিল।",
      cefr="B1", category="ielts", irregular=True, v2="overtook", v3="overtaken", v4="overtaking", v5="overtakes", bags="IDSWG"),
    V("prove", "/pruːv/", "to show that something is true", "প্রমাণ করা",
      "You must prove your claim with data.", "তথ্য দিয়ে দাবি প্রমাণ করতে হবে।",
      "The test proved the theory.", "পরীক্ষা তত্ত্বটি প্রমাণ করেছিল।",
      cefr="B1", category="education", irregular=True, v2="proved", v3="proven", v4="proving", v5="proves", bags="IRSWG"),
    V("quit", "/kwɪt/", "to leave a job or stop a habit", "ছেড়ে দেওয়া",
      "He wants to quit smoking this year.", "এই বছর সে ধূমপান ছাড়তে চায়।",
      "She quit the company in March.", "মার্চে সে চাকরি ছেড়েছিল।",
      cefr="B1", category="office", irregular=True, v2="quit", v3="quit", v4="quitting", v5="quits", bags="DIRS"),
    V("rewrite", "/ˌriːˈraɪt/", "to write something again more clearly", "আবার লেখা",
      "I rewrite weak paragraphs at night.", "রাতের বেলা দুর্বল প্যারা আবার লিখি।",
      "She rewrote the introduction twice.", "সে ভূমিকা দুবার আবার লিখেছিল।",
      cefr="B1", category="education", irregular=True, v2="rewrote", v3="rewritten", v4="rewriting", v5="rewrites", bags="IRSW"),
    V("rid", "/rɪd/", "to remove something unwanted", "মুক্ত করা",
      "Cities try to rid streets of plastic.", "শহরগুলো রাস্তা প্লাস্টিকমুক্ত করতে চায়।",
      "We rid the kitchen of ants.", "আমরা রান্নাঘর পিঁপড়ামুক্ত করেছিলাম।",
      cefr="B2", category="daily", irregular=True, v2="rid", v3="rid", v4="ridding", v5="rids", bags="DIG"),
    V("shed", "/ʃed/", "to lose or drop something", "ঝরে ফেলা / কমানো",
      "Firms shed jobs in a recession.", "মন্দাকালে কোম্পানি চাকরি কমায়।",
      "The tree shed its leaves early.", "গাছ তাড়াতাড়ি পাতা ঝরিয়েছিল।",
      cefr="B2", category="ielts", irregular=True, v2="shed", v3="shed", v4="shedding", v5="sheds", bags="IWG"),
    V("shine", "/ʃaɪn/", "to give light; to do extremely well", "জ্বলা / উজ্জ্বল হওয়া",
      "Some students shine in speaking tests.", "কিছু শিক্ষার্থী স্পিকিং টেস্টে উজ্জ্বল হয়।",
      "She shone in the interview.", "সাক্ষাৎকারে সে উজ্জ্বল হয়েছিল।",
      cefr="B1", category="daily", irregular=True, v2="shone", v3="shone", v4="shining", v5="shines", bags="DIS"),
    V("shrink", "/ʃrɪŋk/", "to become smaller", "ছোট হয়ে যাওয়া",
      "Glaciers shrink as temperatures rise.", "তাপমাত্রা বাড়লে হিমবাহ ছোট হয়।",
      "The workforce shrank after automation.", "অটোমেশনের পর কর্মীসংখ্যা কমে গিয়েছিল।",
      cefr="B2", category="ielts", irregular=True, v2="shrank", v3="shrunk", v4="shrinking", v5="shrinks", bags="IWG"),
    V("sink", "/sɪŋk/", "to go down below a surface", "ডুবে যাওয়া",
      "Old boats sink if they are not repaired.", "মেরামত না করলে পুরনো নৌকা ডুবে যায়।",
      "The share price sank in an hour.", "শেয়ারের দাম এক ঘণ্টায় ডুবে গিয়েছিল।",
      cefr="B1", category="ielts", irregular=True, v2="sank", v3="sunk", v4="sinking", v5="sinks", bags="IDWG"),
    V("spin", "/spɪn/", "to turn quickly; to present news in a biased way", "ঘোরানো / ঘুরিয়ে বলা",
      "Politicians spin bad results.", "রাজনীতিকরা খারাপ ফল ঘুরিয়ে বলেন।",
      "The wheels spun on the ice.", "বরফে চাকা ঘুরেছিল।",
      cefr="B2", category="ielts", irregular=True, v2="spun", v3="spun", v4="spinning", v5="spins", bags="ISG"),
    V("split", "/splɪt/", "to divide into parts", "ভাগ করা / ফাটা",
      "Couples sometimes split the bills.", "দম্পতিরা মাঝে মাঝে বিল ভাগ করে।",
      "The party split over the policy.", "নীতি নিয়ে দলটি ভেঙে গিয়েছিল।",
      cefr="B1", category="daily", irregular=True, v2="split", v3="split", v4="splitting", v5="splits", bags="DIRSW"),
    V("spring", "/sprɪŋ/", "to jump; to appear suddenly", "লাফানো / হঠাৎ আসা",
      "New cafés spring up every month.", "প্রতি মাসে নতুন ক্যাফে গজিয়ে ওঠে।",
      "Tears sprang to her eyes.", "তার চোখে জল এসে গিয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="sprang", v3="sprung", v4="springing", v5="springs", bags="DIG"),
    V("sting", "/stɪŋ/", "to hurt with a sharp pain or remark", "হুল ফোটানো / কষ্ট দেওয়া",
      "Criticism can sting more than failure.", "ব্যর্থতার চেয়ে সমালোচনা বেশি কষ্ট দিতে পারে।",
      "The comment stung him.", "মন্তব্যটি তাকে কষ্ট দিয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="stung", v3="stung", v4="stinging", v5="stings", bags="DIS"),
    V("strike", "/straɪk/", "to hit; to refuse to work; to occur to someone", "আঘাত করা / ধর্মঘট করা",
      "Workers strike for fair pay.", "শ্রমিকরা ন্যায্য মজুরির জন্য ধর্মঘট করে।",
      "The idea struck me on the bus.", "বাসে বসেই ধারণাটা মাথায় এসেছিল।",
      cefr="B2", category="ielts", irregular=True, v2="struck", v3="struck", v4="striking", v5="strikes", bags="IDSWG"),
    V("strive", "/straɪv/", "to try very hard", "কঠোর চেষ্টা করা",
      "We strive for accuracy in essays.", "রচনায় আমরা নির্ভুলতার জন্য চেষ্টা করি।",
      "She strove to finish on time.", "সময়মতো শেষ করতে সে কঠোর চেষ্টা করেছিল।",
      cefr="C1", category="education", irregular=True, v2="strove", v3="striven", v4="striving", v5="strives", bags="IRSWG"),
    V("swear", "/sweə/", "to promise seriously; to use rude words", "শপথ করা / গালি দেওয়া",
      "Witnesses swear to tell the truth.", "সাক্ষীরা সত্য বলার শপথ করে।",
      "He swore he had locked the door.", "সে শপথ করে বলেছিল দরজা তালা দিয়েছে।",
      cefr="B1", category="daily", irregular=True, v2="swore", v3="sworn", v4="swearing", v5="swears", bags="DIS"),
    V("sweep", "/swiːp/", "to clean with a broom; to move quickly across", "ঝাড়ু দেওয়া / ছড়িয়ে পড়া",
      "Change can sweep through an industry.", "পরিবর্তন এক শিল্পে ছড়িয়ে পড়তে পারে।",
      "Floods swept away the bridge.", "বন্যা সেতু ভেসে নিয়ে গিয়েছিল।",
      cefr="B1", category="daily", irregular=True, v2="swept", v3="swept", v4="sweeping", v5="sweeps", bags="DIG"),
    V("swell", "/swel/", "to become larger", "ফুলে ওঠা",
      "Crowds swell before the festival.", "উৎসবের আগে ভিড় ফুলে ওঠে।",
      "His ankle swelled after the match.", "ম্যাচের পর তার গোড়ালি ফুলে গিয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="swelled", v3="swollen", v4="swelling", v5="swells", bags="DIG"),
    V("swing", "/swɪŋ/", "to move from side to side; to change suddenly", "দোলা / হঠাৎ বদলানো",
      "Public opinion can swing overnight.", "জনমত রাতারাতি বদলাতে পারে।",
      "The vote swung to the opposition.", "ভোট বিরোধী দলের দিকে চলে গিয়েছিল।",
      cefr="B2", category="ielts", irregular=True, v2="swung", v3="swung", v4="swinging", v5="swings", bags="ISWG"),
    V("tear", "/teə/", "to pull something apart", "ছিঁড়ে ফেলা",
      "Do not tear the answer sheet.", "উত্তরপত্র ছিঁড়বেন না।",
      "She tore up the rough draft.", "সে খসড়া ছিঁড়ে ফেলেছিল।",
      cefr="B1", category="daily", irregular=True, v2="tore", v3="torn", v4="tearing", v5="tears", bags="DIRS"),
    V("thrust", "/θrʌst/", "to push suddenly and with force", "জোরে ঠেলে দেওয়া",
      "The report thrust the issue into public debate.", "রিপোর্ট বিষয়টিকে জনবিতর্কে ঠেলে দিল।",
      "He thrust the form into my hand.", "সে ফর্মটা আমার হাতে ঠেলে দিয়েছিল।",
      cefr="C1", category="ielts", irregular=True, v2="thrust", v3="thrust", v4="thrusting", v5="thrusts", bags="IG"),
    V("tread", "/tred/", "to step on; to behave carefully", "পা রাখা / সাবধানে চলা",
      "Managers must tread carefully with staff.", "ম্যানেজারদের কর্মীদের সাথে সাবধানে চলতে হয়।",
      "She trod on a loose cable.", "সে আলগা তারের উপর পা দিয়েছিল।",
      cefr="C1", category="office", irregular=True, v2="trod", v3="trodden", v4="treading", v5="treads", bags="ISG"),
    V("undercut", "/ˌʌndəˈkʌt/", "to charge less than a competitor", "দাম কমিয়ে প্রতিযোগিতা করা",
      "Online shops undercut local stores.", "অনলাইন দোকান স্থানীয় দোকানের চেয়ে কম দামে বেচে।",
      "The importer undercut every rival.", "আমদানিকারক সব প্রতিদ্বন্দ্বীর দাম কাটিয়েছিল।",
      cefr="B2", category="office", irregular=True, v2="undercut", v3="undercut", v4="undercutting", v5="undercuts", bags="IWG"),
    V("uphold", "/ʌpˈhəʊld/", "to support a law, decision or principle", "বজায় রাখা / সমর্থন করা",
      "Courts uphold constitutional rights.", "আদালত সাংবিধানিক অধিকার বজায় রাখে।",
      "The committee upheld the ban.", "কমিটি নিষেধাজ্ঞা বহাল রেখেছিল।",
      cefr="B2", category="ielts", irregular=True, v2="upheld", v3="upheld", v4="upholding", v5="upholds", bags="IWG"),
    V("upset", "/ʌpˈset/", "to make someone unhappy; to disturb a plan", "মন খারাপ করা / বিঘ্ন ঘটানো",
      "Delays upset exam candidates.", "দেরি পরীক্ষার্থীদের বিরক্ত করে।",
      "The news upset the whole family.", "খবরটা পুরো পরিবারকে বিচলিত করেছিল।",
      cefr="B1", category="daily", irregular=True, v2="upset", v3="upset", v4="upsetting", v5="upsets", bags="DIS"),
    V("weave", "/wiːv/", "to make cloth; to combine ideas or stories", "বোনা / গেঁথে তোলা",
      "Good essays weave examples into the argument.", "ভালো রচনা যুক্তিতে উদাহরণ গেঁথে তোলে।",
      "She wove three studies into one paragraph.", "সে তিনটি স্টাডি এক প্যারায় গেঁথেছিল।",
      cefr="B2", category="education", irregular=True, v2="wove", v3="woven", v4="weaving", v5="weaves", bags="IRSW"),
    V("weep", "/wiːp/", "to cry", "কাঁদা",
      "Some films make people weep openly.", "কিছু সিনেমা মানুষকে খোলাখুলি কাঁদায়।",
      "He wept after the result.", "ফলাফলের পর সে কেঁদেছিল।",
      cefr="B2", category="daily", irregular=True, v2="wept", v3="wept", v4="weeping", v5="weeps", bags="DIS"),
    V("wind", "/waɪnd/", "to turn something; to follow a twisting path", "পেঁচানো / বাঁকানো পথে চলা",
      "The road winds through the hills.", "রাস্তা পাহাড়ের মধ্যে বেঁকে চলে।",
      "She wound the cable neatly.", "সে তার গুছিয়ে পেঁচিয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="wound", v3="wound", v4="winding", v5="winds", bags="DIG"),
    V("withhold", "/wɪðˈhəʊld/", "to refuse to give something", "আটকে রাখা",
      "Offices withhold tax from salaries.", "অফিস বেতন থেকে কর কেটে রাখে।",
      "The school withheld the certificates.", "স্কুল সনদ আটকে রেখেছিল।",
      cefr="B2", category="office", irregular=True, v2="withheld", v3="withheld", v4="withholding", v5="withholds", bags="IRWG"),
    V("withstand", "/wɪðˈstænd/", "to not be damaged by something strong", "সহ্য করে টিকে থাকা",
      "Bridges must withstand heavy floods.", "সেতুকে ভারী বন্যা সহ্য করতে হয়।",
      "The building withstood the earthquake.", "ভবনটি ভূমিকম্প সহ্য করেছিল।",
      cefr="C1", category="ielts", irregular=True, v2="withstood", v3="withstood", v4="withstanding", v5="withstands", bags="IWG"),
    V("wring", "/rɪŋ/", "to twist to remove water; to get something with effort", "নিংড়ানো / কষ্টে আদায় করা",
      "Campaigners wring concessions from ministers.", "প্রচারকরা মন্ত্রীদের কাছ থেকে ছাড় আদায় করে।",
      "She wrung the cloth dry.", "সে কাপড় নিংড়ে শুকিয়েছিল।",
      cefr="C1", category="daily", irregular=True, v2="wrung", v3="wrung", v4="wringing", v5="wrings", bags="IG"),
    V("dwell", "/dwel/", "to live somewhere; to keep thinking about something", "বাস করা / আটকে থাকা",
      "Do not dwell on one bad score.", "একটা খারাপ স্কোরে আটকে থাকবেন না।",
      "The essay dwelt on rural poverty.", "রচনা গ্রামীণ দারিদ্র্য নিয়ে বিস্তারিত বলেছিল।",
      cefr="C1", category="ielts", irregular=True, v2="dwelt", v3="dwelt", v4="dwelling", v5="dwells", bags="ISWG"),
    V("unwind", "/ʌnˈwaɪnd/", "to relax; to undo something wound", "চাপ কমানো / খুলে দেওয়া",
      "I unwind with a short walk.", "আমি একটু হেঁটে চাপ কমাই।",
      "He unwound after the speaking test.", "স্পিকিং টেস্টের পর সে চাপমুক্ত হয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="unwound", v3="unwound", v4="unwinding", v5="unwinds", bags="DIS"),
    V("string", "/strɪŋ/", "to hang things in a line; to join words or events", "সারি করে লাগানো",
      "Speakers string ideas into a story.", "বক্তারা ধারণাগুলো গল্পের মতো সাজান।",
      "They strung lights across the street.", "তারা রাস্তায় আলো সারি করে লাগিয়েছিল।",
      cefr="B2", category="daily", irregular=True, v2="strung", v3="strung", v4="stringing", v5="strings", bags="DIS"),

    # ── regular B1+ ──────────────────────────────────────────────────────────
    V("afford", "/əˈfɔːd/", "to have enough money or time for something", "সামর্থ্য থাকা",
      "Few families can afford private tutors.", "কম পরিবারই প্রাইভেট টিউটর সামলাতে পারে।",
      "We afforded a short break last year.", "গত বছর আমরা ছোট ছুটি সামলাতে পেরেছিলাম।",
      cefr="B1", bags="DRS"),
    V("acknowledge", "/əkˈnɒlɪdʒ/", "to accept that something is true", "স্বীকার করা",
      "I acknowledge the limits of this study.", "এই গবেষণার সীমা আমি স্বীকার করি।",
      "She acknowledged her mistake.", "সে তার ভুল স্বীকার করেছিল।",
      cefr="B2", category="education", bags="RSWG"),
    V("adapt", "/əˈdæpt/", "to change in order to fit a new situation", "খাপ খাওয়ানো",
      "Workers adapt to new software quickly.", "কর্মীরা নতুন সফটওয়্যারে তাড়াতাড়ি খাপ খায়।",
      "The school adapted the timetable.", "স্কুল রুটিন বদলে নিয়েছিল।",
      cefr="B1", bags="DRSW"),
    V("allow", "/əˈlaʊ/", "to give permission", "অনুমতি দেওয়া",
      "The app allows offline practice.", "অ্যাপ অফলাইনে অনুশীলনের অনুমতি দেয়।",
      "The invigilator allowed extra time.", "পরিদর্শক অতিরিক্ত সময় দিয়েছিলেন।",
      cefr="B1", bags="DRS"),
    V("announce", "/əˈnaʊns/", "to tell people about something officially", "ঘোষণা করা",
      "The board will announce the results tomorrow.", "বোর্ড আগামীকাল ফল ঘোষণা করবে।",
      "They announced a hiring freeze.", "তারা নিয়োগ স্থগিতের ঘোষণা দিয়েছিল।",
      cefr="B1", category="office", bags="DRS"),
    V("appear", "/əˈpɪə/", "to seem; to become visible", "মনে হওয়া / দেখা দেওয়া",
      "The graph appears to flatten after 2019.", "২০১৯-এর পর গ্রাফ সমতল মনে হয়।",
      "New symptoms appeared overnight.", "নতুন উপসর্গ রাতারাতি দেখা দিয়েছিল।",
      cefr="B1", category="ielts", bags="RSWG"),
    V("apply", "/əˈplaɪ/", "to request formally; to use a method", "আবেদন করা / প্রয়োগ করা",
      "I apply this method in Task 2.", "টাস্ক ২-এ আমি এই পদ্ধতি প্রয়োগ করি।",
      "She applied for the scholarship.", "সে বৃত্তির জন্য আবেদন করেছিল।",
      cefr="B1", category="education", bags="DRSW"),
    V("appreciate", "/əˈpriːʃieɪt/", "to recognise the value of something", "মূল্যায়ন করা / কৃতজ্ঞ হওয়া",
      "I appreciate honest feedback.", "আমি সৎ মতামতের কদর করি।",
      "The manager appreciated extra effort.", "ম্যানেজার অতিরিক্ত চেষ্টার কদর করেছিলেন।",
      cefr="B1", bags="DRS"),
    V("assume", "/əˈsjuːm/", "to believe something is true without proof", "অনুমান করা",
      "Do not assume the writer agrees.", "লেখক রাজি—এমন অনুমান করবেন না।",
      "I assumed the meeting was cancelled.", "আমি ধরে নিয়েছিলাম মিটিং বাতিল।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("attend", "/əˈtend/", "to go to an event", "উপস্থিত থাকা",
      "Many candidates attend speaking clubs.", "অনেক পরীক্ষার্থী স্পিকিং ক্লাবে যায়।",
      "He attended every workshop.", "সে প্রতিটি ওয়ার্কশপে গিয়েছিল।",
      cefr="B1", category="education", bags="DRS"),
    V("blame", "/bleɪm/", "to say someone caused a problem", "দোষ দেওয়া",
      "People often blame traffic for lateness.", "দেরির জন্য মানুষ প্রায়ই যানজটকে দোষ দেয়।",
      "The report blamed poor planning.", "রিপোর্ট খারাপ পরিকল্পনাকে দায়ী করেছিল।",
      cefr="B1", bags="DRS"),
    V("boost", "/buːst/", "to increase or improve something", "বাড়ানো / চাঙা করা",
      "Practice can boost fluency.", "অনুশীলন সাবলীলতা বাড়াতে পারে।",
      "The campaign boosted sales.", "ক্যাম্পেইন বিক্রি বাড়িয়েছিল।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("bother", "/ˈbɒðə/", "to take the trouble; to annoy", "কষ্ট করা / বিরক্ত করা",
      "Few people bother to check sources.", "কম লোকেই সূত্র যাচাইয়ের কষ্ট করে।",
      "The noise bothered the neighbours.", "শব্দ প্রতিবেশীদের বিরক্ত করেছিল।",
      cefr="B1", bags="DRS"),
    V("cite", "/saɪt/", "to mention a source as evidence", "উদ্ধৃত করা",
      "Good essays cite recent studies.", "ভালো রচনা সাম্প্রতিক গবেষণা উদ্ধৃত করে।",
      "The author cited WHO data.", "লেখক ডব্লিউএইচও-র তথ্য উদ্ধৃত করেছিলেন।",
      cefr="B2", category="ielts", bags="RWG"),
    V("clarify", "/ˈklærəfaɪ/", "to make something easier to understand", "পরিষ্কার করা",
      "Could you clarify that point?", "ওই পয়েন্টটা কি পরিষ্কার করবেন?",
      "The teacher clarified the marking.", "শিক্ষক মার্কিং পরিষ্কার করেছিলেন।",
      cefr="B1", category="education", bags="DRSW"),
    V("classify", "/ˈklæsɪfaɪ/", "to put things into groups", "শ্রেণিভুক্ত করা",
      "Scientists classify waste by type.", "বিজ্ঞানীরা বর্জ্য ধরন অনুযায়ী ভাগ করেন।",
      "The passage classified jobs as skilled or unskilled.", "প্যাসেজ চাকরি দক্ষ/অদক্ষ হিসেবে ভাগ করেছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("coincide", "/ˌkəʊɪnˈsaɪd/", "to happen at the same time", "একই সময়ে ঘটা",
      "The strike coincided with exams.", "ধর্মঘট পরীক্ষার সাথে মিলে গিয়েছিল।",
      "Two studies coincided in their findings.", "দুই গবেষণার ফল মিলে গিয়েছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("comprise", "/kəmˈpraɪz/", "to consist of", "গঠিত হওয়া",
      "The sample comprises 400 adults.", "নমুনা ৪০০ প্রাপ্তবয়স্ক নিয়ে গঠিত।",
      "The committee comprised five members.", "কমিটি পাঁচ সদস্য নিয়ে গঠিত ছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("conduct", "/kənˈdʌkt/", "to organise and carry out", "পরিচালনা করা",
      "Researchers conduct surveys online.", "গবেষকরা অনলাইনে জরিপ চালান।",
      "The school conducted a mock test.", "স্কুল মক টেস্ট নিয়েছিল।",
      cefr="B2", category="education", bags="RSWG"),
    V("consist", "/kənˈsɪst/", "to be made of (consist of)", "গঠিত হওয়া",
      "Task 1 consists of a graph and a summary.", "টাস্ক ১-এ গ্রাফ ও সারাংশ থাকে।",
      "The diet consisted mainly of rice.", "খাবার মূলত ভাত দিয়ে গঠিত ছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("constitute", "/ˈkɒnstɪtjuːt/", "to be considered as; to make up", "গণ্য হওয়া / গঠন করা",
      "This does not constitute proof.", "এটাকে প্রমাণ বলা যায় না।",
      "Women constituted 40% of the workforce.", "কর্মশক্তির ৪০% নারী ছিলেন।",
      cefr="B2", category="ielts", bags="RWG"),
    V("consume", "/kənˈsjuːm/", "to use energy, food or goods", "খরচ করা / খাওয়া",
      "Cities consume huge amounts of water.", "শহর বিপুল পানি খরচ করে।",
      "The factory consumed more fuel last year.", "গত বছর কারখানা বেশি জ্বালানি খরচ করেছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("contradict", "/ˌkɒntrəˈdɪkt/", "to say the opposite of something", "বিরোধিতা করা",
      "Paragraph B seems to contradict A.", "প্যারা বি যেন এ-এর বিরোধিতা করে।",
      "The witness contradicted earlier claims.", "সাক্ষী আগের দাবির বিরোধিতা করেছিল।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("contrast", "/kənˈtrɑːst/", "to compare in order to show differences", "পার্থক্য দেখানো",
      "The chart contrasts urban and rural pay.", "চার্ট শহর ও গ্রামের বেতনের পার্থক্য দেখায়।",
      "The essay contrasted two policies.", "রচনা দুই নীতির পার্থক্য দেখিয়েছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("convince", "/kənˈvɪns/", "to make someone believe something", "বিশ্বাস করানো",
      "You need to convince the examiner.", "পরীক্ষককে বিশ্বাস করাতে হবে।",
      "The data convinced the committee.", "তথ্য কমিটিকে বিশ্বাস করিয়েছিল।",
      cefr="B1", bags="DRS"),
    V("cope", "/kəʊp/", "to deal successfully with a problem", "সামলানো",
      "How do you cope with exam pressure?", "পরীক্ষার চাপ কীভাবে সামলান?",
      "She coped well with the delay.", "দেরি সে ভালোভাবে সামলেছিল।",
      cefr="B1", bags="DRS"),
    V("criticise", "/ˈkrɪtɪsaɪz/", "to say what is wrong with something", "সমালোচনা করা",
      "Some people criticise online learning.", "কেউ কেউ অনলাইন শেখাকে সমালোচনা করেন।",
      "The article criticised the policy.", "নিবন্ধটি নীতির সমালোচনা করেছিল।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("decrease", "/dɪˈkriːs/", "to become smaller in size or amount", "কমে যাওয়া",
      "Emissions decrease after the new law.", "নতুন আইনের পর নির্গমন কমে।",
      "Unemployment decreased in 2022.", "২০২২-এ বেকারত্ব কমেছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("define", "/dɪˈfaɪn/", "to say exactly what a word means", "সংজ্ঞায়িত করা",
      "First define the key term.", "আগে মূল শব্দের সংজ্ঞা দিন।",
      "The author defined poverty narrowly.", "লেখক দারিদ্র্যকে সংকীর্ণভাবে সংজ্ঞায়িত করেছিলেন।",
      cefr="B1", category="education", bags="RSWG"),
    V("delay", "/dɪˈleɪ/", "to make something happen later", "দেরি করানো",
      "Traffic delays the morning commute.", "যানজট সকালের যাতায়াত দেরি করায়।",
      "The airline delayed the flight.", "এয়ারলাইন ফ্লাইট দেরি করেছিল।",
      cefr="B1", bags="DRS"),
    V("deliver", "/dɪˈlɪvə/", "to take something to a place; to give a speech", "পৌঁছে দেওয়া / বক্তৃতা দেওয়া",
      "Couriers deliver parcels the same day.", "কুরিয়ার সেদিনই পার্সেল পৌঁছে দেয়।",
      "She delivered a clear presentation.", "সে পরিষ্কার উপস্থাপনা দিয়েছিল।",
      cefr="B1", category="office", bags="DRS"),
    V("deny", "/dɪˈnaɪ/", "to say that something is not true", "অস্বীকার করা",
      "Companies often deny responsibility.", "কোম্পানি প্রায়ই দায় অস্বীকার করে।",
      "He denied the accusation.", "সে অভিযোগ অস্বীকার করেছিল।",
      cefr="B1", bags="DRSG"),
    V("depend", "/dɪˈpend/", "to be affected by something else", "নির্ভর করা",
      "Progress depends on daily practice.", "উন্নতি প্রতিদিনের অনুশীলনের উপর নির্ভর করে।",
      "The result depended on one question.", "ফল এক প্রশ্নের উপর নির্ভর করেছিল।",
      cefr="B1", bags="DRSWG"),
    V("deserve", "/dɪˈzɜːv/", "to be worthy of something", "যোগ্য হওয়া",
      "Hard-working staff deserve a raise.", "পরিশ্রমী কর্মীরা ইনক্রিমেন্টের যোগ্য।",
      "The idea deserved more attention.", "ধারণাটি আরও মনোযোগ পাওয়ার যোগ্য ছিল।",
      cefr="B1", bags="DRS"),
    V("determine", "/dɪˈtɜːmɪn/", "to find out exactly; to decide", "নির্ধারণ করা",
      "Surveys determine public opinion.", "জরিপ জনমত নির্ধারণ করে।",
      "The court determined the cause.", "আদালত কারণ নির্ধারণ করেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("disagree", "/ˌdɪsəˈɡriː/", "to have a different opinion", "অসম্মত হওয়া",
      "I disagree with that conclusion.", "সেই সিদ্ধান্তের সাথে আমি একমত নই।",
      "The two studies disagreed.", "দুই গবেষণা একমত হয়নি।",
      cefr="B1", bags="DRS"),
    V("discourage", "/dɪsˈkʌrɪdʒ/", "to make someone less confident or willing", "নিরুৎসাহিত করা",
      "High fees discourage applicants.", "উচ্চ ফি আবেদনকারীদের নিরুৎসাহিত করে।",
      "Failure discouraged him for a month.", "ব্যর্থতা তাকে এক মাস নিরুৎসাহিত করেছিল।",
      cefr="B2", bags="DRS"),
    V("distinguish", "/dɪˈstɪŋɡwɪʃ/", "to recognise a difference", "পার্থক্য করা",
      "Readers must distinguish fact from opinion.", "পাঠককে তথ্য ও মতামত আলাদা করতে হয়।",
      "The study distinguished two groups.", "গবেষণা দুই দল আলাদা করেছিল।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("distribute", "/dɪˈstrɪbjuːt/", "to give things to a number of people", "বিতরণ করা",
      "NGOs distribute food after floods.", "বন্যার পর এনজিও খাবার বিতরণ করে।",
      "The school distributed past papers.", "স্কুল পুরনো প্রশ্নপত্র বিতরণ করেছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("doubt", "/daʊt/", "to feel uncertain about something", "সন্দেহ করা",
      "I doubt the figure is accurate.", "সংখ্যাটা নির্ভুল কিনা সন্দেহ হয়।",
      "She doubted the author's claim.", "সে লেখকের দাবি নিয়ে সন্দেহ করেছিল।",
      cefr="B1", bags="DRSG"),
    V("earn", "/ɜːn/", "to get money by working", "উপার্জন করা",
      "Many graduates earn less at first.", "অনেক গ্র্যাজুয়েট শুরুতে কম উপার্জন করে।",
      "She earned a promotion last year.", "গত বছর সে পদোন্নতি পেয়েছিল।",
      cefr="B1", category="office", bags="DRS"),
    V("eliminate", "/ɪˈlɪmɪneɪt/", "to remove completely", "বাদ দেওয়া",
      "The plan aims to eliminate waste.", "পরিকল্পনার লক্ষ্য বর্জ্য বাদ দেওয়া।",
      "They eliminated two weak options.", "তারা দুই দুর্বল অপশন বাদ দিয়েছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("emerge", "/ɪˈmɜːdʒ/", "to appear or become known", "উঠে আসা",
      "A pattern emerges in the second paragraph.", "দ্বিতীয় প্যারায় একটা ধরন উঠে আসে।",
      "New evidence emerged later.", "পরে নতুন প্রমাণ উঠে এসেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("enhance", "/ɪnˈhɑːns/", "to improve the quality of something", "উন্নত করা",
      "Feedback can enhance writing.", "ফিডব্যাক লেখা উন্নত করতে পারে।",
      "Lighting enhanced the photos.", "আলো ছবিগুলো উন্নত করেছিল।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("ensure", "/ɪnˈʃɔː/", "to make certain that something happens", "নিশ্চিত করা",
      "Please ensure answers are spelled correctly.", "উত্তরের বানান যেন ঠিক থাকে নিশ্চিত করুন।",
      "Staff ensured everyone signed in.", "কর্মীরা নিশ্চিত করেছিলেন সবাই সাইন ইন করেছে।",
      cefr="B2", category="office", bags="DRSW"),
    V("establish", "/ɪˈstæblɪʃ/", "to start; to prove", "প্রতিষ্ঠা করা / প্রমাণ করা",
      "The first sentence establishes the topic.", "প্রথম বাক্য বিষয় প্রতিষ্ঠা করে।",
      "Researchers established a link.", "গবেষকরা যোগসূত্র প্রমাণ করেছিলেন।",
      cefr="B2", category="ielts", bags="RWG"),
    V("estimate", "/ˈestɪmeɪt/", "to guess an amount roughly", "আনুমানিক হিসাব করা",
      "Experts estimate a 10% rise.", "বিশেষজ্ঞরা ১০% বৃদ্ধির আনুমান করেন।",
      "The council estimated the cost.", "কাউন্সিল খরচের আনুমান করেছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("examine", "/ɪɡˈzæmɪn/", "to look at something carefully", "পরীক্ষা করা",
      "The passage examines rural migration.", "প্যাসেজ গ্রামীণ অভিবাসন পরীক্ষা করে।",
      "Doctors examined the samples.", "ডাক্তাররা নমুনা পরীক্ষা করেছিলেন।",
      cefr="B1", category="education", bags="RSWG"),
    V("exceed", "/ɪkˈsiːd/", "to go beyond a limit", "ছাড়িয়ে যাওয়া",
      "Noise levels exceed the legal limit.", "শব্দের মাত্রা আইনি সীমা ছাড়ায়।",
      "Demand exceeded supply.", "চাহিদা সরবরাহ ছাড়িয়ে গিয়েছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("expand", "/ɪkˈspænd/", "to become larger", "বিস্তৃত হওয়া",
      "Universities expand online courses.", "বিশ্ববিদ্যালয় অনলাইন কোর্স বাড়ায়।",
      "The company expanded overseas.", "কোম্পানি বিদেশে বিস্তৃত হয়েছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("expect", "/ɪkˈspekt/", "to think something will happen", "আশা করা",
      "I expect the graph to rise again.", "গ্রাফ আবার উঠবে বলে আশা করি।",
      "We expected a longer delay.", "আমরা আরও দেরি আশা করেছিলাম।",
      cefr="B1", bags="DRSW"),
    V("explain", "/ɪkˈspleɪn/", "to make something clear", "ব্যাখ্যা করা",
      "Can you explain your choice?", "আপনার পছন্দ কি ব্যাখ্যা করবেন?",
      "The teacher explained the rule.", "শিক্ষক নিয়ম ব্যাখ্যা করেছিলেন।",
      cefr="B1", category="education", bags="DRS"),
    V("express", "/ɪkˈspres/", "to show a feeling or idea in words", "প্রকাশ করা",
      "Speakers should express opinions clearly.", "বক্তাদের মতামত স্পষ্ট প্রকাশ করা উচিত।",
      "She expressed concern about fees.", "সে ফি নিয়ে উদ্বেগ প্রকাশ করেছিল।",
      cefr="B1", bags="DRS"),
    V("fail", "/feɪl/", "to not succeed", "ব্যর্থ হওয়া",
      "Some plans fail without funding.", "অর্থ ছাড়া কিছু পরিকল্পনা ব্যর্থ হয়।",
      "The first attempt failed.", "প্রথম চেষ্টা ব্যর্থ হয়েছিল।",
      cefr="B1", bags="DRS"),
    V("focus", "/ˈfəʊkəs/", "to give attention to one thing", "মনোযোগ দেওয়া",
      "I focus on linking words in writing.", "রাইটিংয়ে আমি লিংকিং ওয়ার্ডে মন দিই।",
      "The lecture focused on climate.", "লেকচার জলবায়ু নিয়ে ছিল।",
      cefr="B1", category="education", bags="DRSW"),
    V("gather", "/ˈɡæðə/", "to come together; to collect", "জমা হওয়া / সংগ্রহ করা",
      "Students gather evidence from the text.", "শিক্ষার্থীরা টেক্সট থেকে প্রমাণ সংগ্রহ করে।",
      "A crowd gathered outside.", "বাইরে ভিড় জমেছিল।",
      cefr="B1", bags="DRSG"),
    V("hesitate", "/ˈhezɪteɪt/", "to pause before doing something", "ইতস্তত করা",
      "Do not hesitate if you know the answer.", "উত্তর জানলে ইতস্তত করবেন না।",
      "She hesitated before speaking.", "কথা বলার আগে সে ইতস্তত করেছিল।",
      cefr="B2", bags="DRS"),
    V("highlight", "/ˈhaɪlaɪt/", "to emphasise the most important part", "গুরুত্ব দিয়ে দেখানো",
      "The chart highlights a sharp drop.", "চার্ট তীব্র পতন দেখায়।",
      "The speaker highlighted two risks.", "বক্তা দুই ঝুঁকি তুলে ধরেছিলেন।",
      cefr="B1", category="ielts", bags="RSWG"),
    V("ignore", "/ɪɡˈnɔː/", "to pay no attention", "উপেক্ষা করা",
      "Do not ignore the second question.", "দ্বিতীয় প্রশ্ন উপেক্ষা করবেন না।",
      "They ignored the warning.", "তারা সতর্কতা উপেক্ষা করেছিল।",
      cefr="B1", bags="DRSG"),
    V("imagine", "/ɪˈmædʒɪn/", "to form a picture in your mind", "কল্পনা করা",
      "Imagine you are describing your hometown.", "কল্পনা করুন নিজ শহর বর্ণনা করছেন।",
      "I imagined a quieter office.", "আমি শান্ত অফিস কল্পনা করেছিলাম।",
      cefr="B1", bags="DRS"),
    V("improve", "/ɪmˈpruːv/", "to become better", "উন্নতি করা",
      "Daily speaking can improve fluency.", "প্রতিদিন কথা বললে সাবলীলতা বাড়ে।",
      "Her score improved by one band.", "তার স্কোর এক ব্যান্ড উন্নত হয়েছিল।",
      cefr="B1", category="education", bags="DRSW"),
    V("include", "/ɪnˈkluːd/", "to have something as a part", "অন্তর্ভুক্ত করা",
      "Good answers include a specific example.", "ভালো উত্তরে নির্দিষ্ট উদাহরণ থাকে।",
      "The fee included study materials.", "ফিতে স্টাডি ম্যাটেরিয়াল ছিল।",
      cefr="B1", bags="DRSWG"),
    V("increase", "/ɪnˈkriːs/", "to become larger in amount", "বাড়া",
      "Demand increases in the holiday season.", "ছুটির মৌসুমে চাহিদা বাড়ে।",
      "Fees increased last year.", "গত বছর ফি বেড়েছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("inform", "/ɪnˈfɔːm/", "to tell someone about something", "জানানো",
      "Please inform the office of any delay.", "দেরি হলে অফিসকে জানান।",
      "Staff informed students of the change.", "কর্মীরা শিক্ষার্থীদের পরিবর্তন জানিয়েছিল।",
      cefr="B1", category="office", bags="DRS"),
    V("inspire", "/ɪnˈspaɪə/", "to make someone want to do something well", "অনুপ্রাণিত করা",
      "Good teachers inspire confidence.", "ভালো শিক্ষক আত্মবিশ্বাস জাগায়।",
      "The talk inspired me to practise more.", "আলোচনা আমাকে আরও অনুশীলনে অনুপ্রাণিত করেছিল।",
      cefr="B2", bags="DRS"),
    V("intend", "/ɪnˈtend/", "to have a plan", "ইচ্ছা করা",
      "I intend to retake the test in October.", "অক্টোবরে টেস্ট আবার দেওয়ার ইচ্ছা।",
      "They intended to expand the clinic.", "তারা ক্লিনিক বাড়ানোর ইচ্ছা করেছিল।",
      cefr="B1", bags="DRS"),
    V("interpret", "/ɪnˈtɜːprɪt/", "to explain the meaning of something", "ব্যাখ্যা করা",
      "Candidates must interpret the graph.", "পরীক্ষার্থীদের গ্রাফ ব্যাখ্যা করতে হয়।",
      "Critics interpreted the film differently.", "সমালোচকরা সিনেমা আলাদাভাবে ব্যাখ্যা করেছিলেন।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("introduce", "/ˌɪntrəˈdjuːs/", "to bring something new; to present a person", "চালু করা / পরিচয় করানো",
      "The city introduced a plastic ban.", "শহর প্লাস্টিক নিষেধাজ্ঞা চালু করেছে।",
      "She introduced a useful example.", "সে একটি কাজে লাগে এমন উদাহরণ দিয়েছিল।",
      cefr="B1", bags="DRSW"),
    V("investigate", "/ɪnˈvestɪɡeɪt/", "to try to find out the facts", "তদন্ত করা",
      "Journalists investigate the claims.", "সাংবাদিকরা দাবিগুলো তদন্ত করেন।",
      "Police investigated the leak.", "পুলিশ লিক তদন্ত করেছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("invite", "/ɪnˈvaɪt/", "to ask someone to come", "আমন্ত্রণ করা",
      "They invite questions at the end.", "শেষে তারা প্রশ্ন করতে বলেন।",
      "The college invited guest speakers.", "কলেজ অতিথি বক্তা ডেকেছিল।",
      cefr="B1", bags="DRS"),
    V("justify", "/ˈdʒʌstɪfaɪ/", "to give a good reason for something", "যুক্তি দেওয়া",
      "You must justify your opinion.", "মতামতের যুক্তি দিতে হবে।",
      "The firm justified the price rise.", "কোম্পানি দাম বৃদ্ধির যুক্তি দিয়েছিল।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("mention", "/ˈmenʃn/", "to say something briefly", "উল্লেখ করা",
      "Did the speaker mention cost?", "বক্তা কি খরচের কথা বলেছিলেন?",
      "She mentioned two solutions.", "সে দুই সমাধান উল্লেখ করেছিল।",
      cefr="B1", bags="DRS"),
    V("neglect", "/nɪˈɡlekt/", "to fail to look after something", "অবহেলা করা",
      "Do not neglect pronunciation.", "উচ্চারণ অবহেলা করবেন না।",
      "The council neglected the park.", "কাউন্সিল পার্ক অবহেলা করেছিল।",
      cefr="B2", category="ielts", bags="DRSG"),
    V("notice", "/ˈnəʊtɪs/", "to become aware of something", "লক্ষ করা",
      "I notice a pattern in the mistakes.", "ভুলগুলোতে একটা ধরন লক্ষ করি।",
      "She noticed the date was wrong.", "সে দেখেছিল তারিখ ভুল।",
      cefr="B1", bags="DRS"),
    V("observe", "/əbˈzɜːv/", "to watch carefully; to notice", "পর্যবেক্ষণ করা",
      "Scientists observe animal behaviour.", "বিজ্ঞানীরা প্রাণীর আচরণ পর্যবেক্ষণ করেন।",
      "Teachers observed a drop in attendance.", "শিক্ষকরা উপস্থিতি কমতে দেখেছিলেন।",
      cefr="B2", category="ielts", bags="RSWG"),
    V("obtain", "/əbˈteɪn/", "to get something, especially officially", "অর্জন করা / পাওয়া",
      "Students obtain ID cards on day one.", "শিক্ষার্থীরা প্রথম দিনে আইডি কার্ড পায়।",
      "She obtained a work permit.", "সে ওয়ার্ক পারমিট পেয়েছিল।",
      cefr="B2", category="office", bags="RWG"),
    V("occur", "/əˈkɜː/", "to happen", "ঘটা",
      "Accidents occur more at night.", "দুর্ঘটনা রাতে বেশি ঘটে।",
      "A sharp rise occurred in 2018.", "২০১৮-এ তীব্র বৃদ্ধি ঘটেছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("offer", "/ˈɒfə/", "to say you will give or do something", "প্রস্তাব দেওয়া",
      "Libraries offer free Wi-Fi.", "লাইব্রেরি ফ্রি ওয়াই-ফাই দেয়।",
      "The company offered flexible hours.", "কোম্পানি নমনীয় সময়ের প্রস্তাব দিয়েছিল।",
      cefr="B1", bags="DRS"),
    V("organise", "/ˈɔːɡənaɪz/", "to plan and arrange", "সাজানো / আয়োজন করা",
      "I organise ideas before writing.", "লেখার আগে ধারণা সাজাই।",
      "They organised a charity fair.", "তারা দাতব্য মেলা আয়োজন করেছিল।",
      cefr="B1", bags="DRS"),
    V("outweigh", "/ˌaʊtˈweɪ/", "to be more important than something else", "বেশি গুরুত্বপূর্ণ হওয়া",
      "Benefits outweigh the costs.", "খরচের চেয়ে সুবিধা বেশি।",
      "The risks outweighed the gains.", "লাভের চেয়ে ঝুঁকি বেশি ছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("perform", "/pəˈfɔːm/", "to do a task or entertainment", "সম্পাদন করা",
      "Nurses perform essential work.", "নার্সরা জরুরি কাজ করেন।",
      "The team performed well under pressure.", "চাপে দল ভালো করেছিল।",
      cefr="B1", bags="DRS"),
    V("plunge", "/plʌndʒ/", "to fall suddenly and steeply", "হঠাৎ পড়ে যাওয়া",
      "Oil prices plunge during a glut.", "অতিরিক্ত সরবরাহে তেলের দাম হঠাৎ পড়ে।",
      "The currency plunged overnight.", "মুদ্রা রাতারাতি পড়ে গিয়েছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("pose", "/pəʊz/", "to create a problem or question", "সৃষ্টি করা / উত্থাপন করা",
      "Plastic waste poses a health risk.", "প্লাস্টিক বর্জ্য স্বাস্থ্যঝুঁকি সৃষ্টি করে।",
      "The study posed three questions.", "গবেষণা তিনটি প্রশ্ন তুলেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("prefer", "/prɪˈfɜː/", "to like one thing more than another", "বেশি পছন্দ করা",
      "I prefer tea to coffee.", "কফির চেয়ে চা বেশি পছন্দ করি।",
      "She preferred working from home.", "সে বাড়ি থেকে কাজ বেশি পছন্দ করত।",
      cefr="B1", bags="DRS"),
    V("prepare", "/prɪˈpeə/", "to make ready", "প্রস্তুত করা",
      "Candidates prepare notes for Part 2.", "পরীক্ষার্থীরা পার্ট ২-এর নোট তৈরি করে।",
      "We prepared a checklist.", "আমরা চেকলিস্ট তৈরি করেছিলাম।",
      cefr="B1", bags="DRS"),
    V("promise", "/ˈprɒmɪs/", "to say you will definitely do something", "প্রতিশ্রুতি দেওয়া",
      "Leaders promise cleaner air.", "নেতারা পরিষ্কার বাতাসের প্রতিশ্রুতি দেন।",
      "He promised to send the file.", "সে ফাইল পাঠানোর কথা দিয়েছিল।",
      cefr="B1", bags="DRS"),
    V("protect", "/prəˈtekt/", "to keep safe from harm", "রক্ষা করা",
      "Laws protect consumers.", "আইন ভোক্তাদের রক্ষা করে।",
      "Trees protected the soil.", "গাছ মাটি রক্ষা করেছিল।",
      cefr="B1", bags="DRSWG"),
    V("pursue", "/pəˈsjuː/", "to follow a goal over time", "অনুসরণ করা / চেষ্টা চালিয়ে যাওয়া",
      "Many graduates pursue further study.", "অনেক গ্র্যাজুয়েট উচ্চতর পড়া চালিয়ে যায়।",
      "She pursued a career in nursing.", "সে নার্সিংয়ে ক্যারিয়ার গড়েছিল।",
      cefr="B2", category="education", bags="RSWG"),
    V("recall", "/rɪˈkɔːl/", "to remember", "মনে করা",
      "I cannot recall the exact date.", "সঠিক তারিখ মনে পড়ছে না।",
      "He recalled a similar example.", "সে একই রকম উদাহরণ মনে করেছিল।",
      cefr="B2", bags="DRS"),
    V("recognise", "/ˈrekəɡnaɪz/", "to know someone or something again; to accept", "চেনা / স্বীকার করা",
      "I recognise this question type.", "এই ধরনের প্রশ্ন চিনি।",
      "The board recognised her work.", "বোর্ড তার কাজ স্বীকার করেছিল।",
      cefr="B1", bags="DRSG"),
    V("recover", "/rɪˈkʌvə/", "to get better after a problem", "ঘুরে দাঁড়ানো",
      "Markets recover after a shock.", "ধাক্কার পর বাজার ঘুরে দাঁড়ায়।",
      "She recovered quickly from flu.", "সর্দি থেকে সে তাড়াতাড়ি সেরে উঠেছিল।",
      cefr="B1", category="ielts", bags="DRSWG"),
    V("refer", "/rɪˈfɜː/", "to mention; to send someone for help", "উল্লেখ করা / পাঠানো",
      "The writer refers to earlier research.", "লেখক আগের গবেষণার উল্লেখ করেন।",
      "The doctor referred me to a clinic.", "ডাক্তার আমাকে ক্লিনিকে পাঠিয়েছিলেন।",
      cefr="B1", category="ielts", bags="RSWG"),
    V("regulate", "/ˈreɡjuleɪt/", "to control with official rules", "নিয়ন্ত্রণ করা",
      "Governments regulate food safety.", "সরকার খাদ্য নিরাপত্তা নিয়ন্ত্রণ করে।",
      "The bank regulated interest rates.", "ব্যাংক সুদের হার নিয়ন্ত্রণ করেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("reject", "/rɪˈdʒekt/", "to refuse to accept", "প্রত্যাখ্যান করা",
      "Some readers reject the conclusion.", "কিছু পাঠক সিদ্ধান্ত প্রত্যাখ্যান করে।",
      "The editor rejected the draft.", "সম্পাদক খসড়া ফিরিয়ে দিয়েছিলেন।",
      cefr="B1", bags="DRSG"),
    V("relax", "/rɪˈlæks/", "to rest and become less worried", "আরাম করা",
      "I relax by walking after study.", "পড়ার পর হেঁটে আরাম করি।",
      "She relaxed once the test ended.", "টেস্ট শেষ হলে সে আরাম পেয়েছিল।",
      cefr="B1", bags="DRS"),
    V("release", "/rɪˈliːs/", "to let something go; to make public", "মুক্ত করা / প্রকাশ করা",
      "The office will release the timetable.", "অফিস রুটিন প্রকাশ করবে।",
      "They released the report on Friday.", "শুক্রবার তারা রিপোর্ট প্রকাশ করেছিল।",
      cefr="B1", category="office", bags="DRSG"),
    V("remind", "/rɪˈmaɪnd/", "to help someone remember", "মনে করিয়ে দেওয়া",
      "Alarms remind me to review cards.", "অ্যালার্ম কার্ড রিভিউ মনে করায়।",
      "The email reminded staff of the deadline.", "ইমেইল কর্মীদের ডেডলাইন মনে করিয়েছিল।",
      cefr="B1", bags="DRS"),
    V("remove", "/rɪˈmuːv/", "to take something away", "সরানো",
      "Please remove irrelevant examples.", "অপ্রাসঙ্গিক উদাহরণ সরান।",
      "They removed the old sign.", "তারা পুরনো সাইন সরিয়েছিল।",
      cefr="B1", bags="DRS"),
    V("replace", "/rɪˈpleɪs/", "to put something new instead", "বদলে দেওয়া",
      "Apps replace some paper forms.", "অ্যাপ কিছু কাগজের ফর্ম বদলে দেয়।",
      "The clinic replaced outdated machines.", "ক্লিনিক পুরনো মেশিন বদলেছিল।",
      cefr="B1", bags="DRSW"),
    V("report", "/rɪˈpɔːt/", "to give information about something", "জানানো / রিপোর্ট করা",
      "Newspapers report the latest figures.", "পত্রিকা সর্বশেষ সংখ্যা জানায়।",
      "She reported a drop in attendance.", "সে উপস্থিতি কমার কথা জানিয়েছিল।",
      cefr="B1", category="office", bags="DRSWG"),
    V("restrict", "/rɪˈstrɪkt/", "to limit something", "সীমিত করা",
      "Cities restrict diesel vehicles.", "শহর ডিজেল গাড়ি সীমিত করে।",
      "The rule restricted overtime.", "নিয়ম অতিরিক্ত সময় সীমিত করেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("retain", "/rɪˈteɪn/", "to keep something", "ধরে রাখা",
      "Firms try to retain skilled staff.", "কোম্পানি দক্ষ কর্মী ধরে রাখতে চায়।",
      "The soil retained moisture.", "মাটি আর্দ্রতা ধরে রেখেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("retire", "/rɪˈtaɪə/", "to stop working because of age", "অবসর নেওয়া",
      "Many people retire at 60.", "অনেকে ৬০-এ অবসর নেন।",
      "She retired from teaching last year.", "গত বছর সে শিক্ষকতা থেকে অবসর নিয়েছিল।",
      cefr="B1", bags="DRS"),
    V("satisfy", "/ˈsætɪsfaɪ/", "to please; to be enough", "সন্তুষ্ট করা",
      "One example may not satisfy the examiner.", "এক উদাহরণ পরীক্ষককে যথেষ্ট নাও লাগতে পারে।",
      "The apology satisfied the customer.", "ক্ষমা গ্রাহককে সন্তুষ্ট করেছিল।",
      cefr="B1", bags="DRS"),
    V("search", "/sɜːtʃ/", "to look carefully for something", "খোঁজা",
      "I search the passage for keywords.", "কীওয়ার্ডের জন্য প্যাসেজ খুঁজি।",
      "They searched the records.", "তারা রেকর্ড খুঁজেছিল।",
      cefr="B1", bags="DRSG"),
    V("select", "/sɪˈlekt/", "to choose from a group", "বাছাই করা",
      "Select the heading that fits best.", "যে হেডিং মিলে সেটা বাছুন।",
      "The panel selected three finalists.", "প্যানেল তিনজন ফাইনালিস্ট বাছাই করেছিল।",
      cefr="B1", bags="DRSG"),
    V("settle", "/ˈsetl/", "to resolve; to start living in a place", "মীমাংসা করা / বসতি করা",
      "Both sides settled the dispute.", "দুই পক্ষ বিরোধ মিটিয়েছিল।",
      "Families settled near the river.", "পরিবারগুলো নদীর কাছে বসতি করেছিল।",
      cefr="B1", bags="DRSG"),
    V("soar", "/sɔː/", "to rise very quickly", "লাফিয়ে ওঠা",
      "Temperatures soar in May.", "মে মাসে তাপমাত্রা লাফিয়ে ওঠে।",
      "Rents soared in the capital.", "রাজধানীতে ভাড়া লাফিয়ে উঠেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("solve", "/sɒlv/", "to find an answer to a problem", "সমাধান করা",
      "We need to solve the housing shortage.", "আবাসন সংকট সমাধান করতে হবে।",
      "The team solved the error.", "দল ত্রুটি সমাধান করেছিল।",
      cefr="B1", bags="DRS"),
    V("stabilise", "/ˈsteɪbəlaɪz/", "to become steady", "স্থিতিশীল করা",
      "Prices stabilise after harvest.", "ফসল কাটার পর দাম স্থিতিশীল হয়।",
      "The currency stabilised in June.", "জুনে মুদ্রা স্থিতিশীল হয়েছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("struggle", "/ˈstrʌɡl/", "to try hard in a difficult situation", "সংগ্রাম করা",
      "Many learners struggle with articles.", "অনেক শিক্ষার্থী আর্টিকেল নিয়ে হিমশিম খায়।",
      "He struggled to finish on time.", "সময়মতো শেষ করতে সে হিমশিম খেয়েছিল।",
      cefr="B1", bags="DRS"),
    V("summarise", "/ˈsʌməraɪz/", "to give the main points briefly", "সারসংক্ষেপ করা",
      "Summarise the graph in one sentence.", "গ্রাফ এক বাক্যে সারসংক্ষেপ করুন।",
      "She summarised the lecture well.", "সে লেকচার ভালোভাবে সারসংক্ষেপ করেছিল।",
      cefr="B1", category="education", bags="RSWG"),
    V("sustain", "/səˈsteɪn/", "to keep something going", "টিকিয়ে রাখা",
      "Farms cannot sustain this water use.", "এই পানি ব্যবহার খামার টিকাতে পারে না।",
      "The city sustained growth for a decade.", "শহর এক দশক প্রবৃদ্ধি ধরে রেখেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("switch", "/swɪtʃ/", "to change from one thing to another", "বদলানো",
      "I switch to English in meetings.", "মিটিংয়ে আমি ইংরেজিতে চলে যাই।",
      "They switched suppliers last month.", "গত মাসে তারা সরবরাহকারী বদলেছিল।",
      cefr="B1", bags="DRS"),
    V("tackle", "/ˈtækl/", "to deal with a difficult problem", "মোকাবিলা করা",
      "Cities must tackle air pollution.", "শহরকে বায়ুদূষণ মোকাবিলা করতে হবে।",
      "The team tackled the backlog.", "দল জমে থাকা কাজ সামলেছিল।",
      cefr="B1", bags="DRSW"),
    V("tend", "/tend/", "to be likely to do something", "ঝোঁক থাকা",
      "I tend to speak too fast.", "আমি দ্রুত কথা বলতে অভ্যস্ত।",
      "Prices tended to rise in summer.", "গ্রীষ্মে দাম বাড়ার ঝোঁক ছিল।",
      cefr="B1", bags="DRSW"),
    V("threaten", "/ˈθretn/", "to be likely to cause harm", "হুমকি দেওয়া",
      "Droughts threaten food security.", "খরা খাদ্যনিরাপত্তাকে হুমকি দেয়।",
      "The storm threatened the coast.", "ঝড় উপকূলকে হুমকি দিয়েছিল।",
      cefr="B1", bags="DRSG"),
    V("train", "/treɪn/", "to teach skills through practice", "প্রশিক্ষণ দেওয়া",
      "Companies train staff in safety.", "কোম্পানি কর্মীদের নিরাপত্তায় প্রশিক্ষণ দেয়।",
      "She trained as a nurse.", "সে নার্স হিসেবে প্রশিক্ষণ নিয়েছিল।",
      cefr="B1", category="office", bags="DRS"),
    V("transform", "/trænsˈfɔːm/", "to change completely", "রূপান্তর করা",
      "Phones transformed daily communication.", "ফোন দৈনন্দিন যোগাযোগ বদলে দিয়েছে।",
      "The reform transformed the sector.", "সংস্কার খাতটি রূপান্তর করেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("trigger", "/ˈtrɪɡə/", "to cause something to start", "ট্রিগার করা / শুরু করানো",
      "Stress can trigger headaches.", "চাপ মাথাব্যথা শুরু করতে পারে।",
      "The announcement triggered protests.", "ঘোষণা বিক্ষোভ শুরু করেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("trust", "/trʌst/", "to believe that someone is honest", "বিশ্বাস করা",
      "Patients must trust their doctors.", "রোগীদের ডাক্তারকে বিশ্বাস করতে হয়।",
      "I trusted the official figures.", "আমি সরকারি সংখ্যা বিশ্বাস করেছিলাম।",
      cefr="B1", bags="DRS"),
    V("undermine", "/ˌʌndəˈmaɪn/", "to make something weaker", "দুর্বল করা",
      "Fake news can undermine trust.", "ভুয়া খবর বিশ্বাস দুর্বল করতে পারে।",
      "Cuts undermined the service.", "কাটছাঁট সেবা দুর্বল করেছিল।",
      cefr="C1", category="ielts", bags="RWG"),
    V("update", "/ʌpˈdeɪt/", "to add the latest information", "হালনাগাদ করা",
      "Please update your CV.", "সিভি হালনাগাদ করুন।",
      "They updated the website yesterday.", "গতকাল তারা ওয়েবসাইট আপডেট করেছিল।",
      cefr="B1", category="office", bags="DRS"),
    V("vary", "/ˈveəri/", "to be different in different cases", "ভেদে যাওয়া",
      "Prices vary by region.", "অঞ্চলভেদে দাম বদলায়।",
      "Results varied across age groups.", "বয়সভেদে ফল আলাদা ছিল।",
      cefr="B1", category="ielts", bags="RSWG"),
    V("warn", "/wɔːn/", "to tell someone about a possible danger", "সতর্ক করা",
      "Doctors warn against late nights.", "ডাক্তাররা রাত জাগার বিরুদ্ধে সতর্ক করেন।",
      "The sign warned of a sharp bend.", "সাইন তীক্ষ্ণ বাঁকের সতর্কতা দিয়েছিল।",
      cefr="B1", bags="DRS"),
    V("welcome", "/ˈwelkəm/", "to greet in a friendly way; to be glad about", "স্বাগত জানানো",
      "We welcome questions after the talk.", "আলোচনার পর প্রশ্ন স্বাগত।",
      "Staff welcomed the new policy.", "কর্মীরা নতুন নীতিকে স্বাগত জানিয়েছিল।",
      cefr="B1", bags="DRS"),
    V("wonder", "/ˈwʌndə/", "to want to know", "ভাবতে থাকা",
      "I wonder why the figure dropped.", "সংখ্যা কেন কমল ভাবছি।",
      "She wondered if the claim was true.", "দাবি সত্য কিনা সে ভেবেছিল।",
      cefr="B1", bags="DRS"),
    V("worry", "/ˈwʌri/", "to feel anxious", "চিন্তা করা",
      "Do not worry about a few mistakes.", "কয়েকটা ভুল নিয়ে চিন্তা করবেন না।",
      "Parents worried about school fees.", "অভিভাবকরা স্কুল ফি নিয়ে চিন্তিত ছিলেন।",
      cefr="B1", bags="DRS"),
    V("double", "/ˈdʌbl/", "to become twice as much", "দ্বিগুণ হওয়া",
      "Online courses double every few years.", "অনলাইন কোর্স কয়েক বছর পরপর দ্বিগুণ হয়।",
      "The population doubled in 20 years.", "২০ বছরে জনসংখ্যা দ্বিগুণ হয়েছিল।",
      cefr="B1", category="ielts", bags="RWG"),
    V("attribute", "/əˈtrɪbjuːt/", "to say something is caused by", "কারণ হিসেবে ধরা",
      "Authors attribute the decline to policy.", "লেখকরা পতনকে নীতির কারণ ধরেন।",
      "She attributed success to practice.", "সে সাফল্য অনুশীলনের কারণে বলেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("derive", "/dɪˈraɪv/", "to get something from a source", "উৎস থেকে পাওয়া",
      "English derives many words from Latin.", "ইংরেজি ল্যাটিন থেকে অনেক শব্দ পায়।",
      "They derived the figure from census data.", "তারা আদমশুমারি থেকে সংখ্যা বের করেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("exclude", "/ɪkˈskluːd/", "to keep something out", "বাদ রাখা",
      "The sample excludes children under 12.", "নমুনায় ১২-এর নিচের শিশু নেই।",
      "The rule excluded part-time staff.", "নিয়ম পার্ট-টাইম কর্মী বাদ রেখেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
    V("relate", "/rɪˈleɪt/", "to show a connection", "সম্পর্কিত করা",
      "The writer relates stress to workload.", "লেখক চাপকে কাজের চাপের সাথে যুক্ত করেন।",
      "The findings related to earlier work.", "ফলাফল আগের কাজের সাথে সম্পর্কিত ছিল।",
      cefr="B1", category="ielts", bags="RSWG"),
    V("associate", "/əˈsəʊʃieɪt/", "to connect in the mind", "যুক্ত করা",
      "People associate IELTS with study abroad.", "মানুষ আইইএলটিএসকে বিদেশে পড়ার সাথে যুক্ত করে।",
      "The brand associated itself with sport.", "ব্র্যান্ড নিজেকে খেলার সাথে যুক্ত করেছিল।",
      cefr="B2", category="ielts", bags="RWG"),
]


PROMOTE_IDS = {"verb:increase"}  # bank CEFR was A2; the verb is B1 in Cambridge


def merge_bank(bank: list, new_rows: list) -> tuple[int, int]:
    by_id = {v["id"]: i for i, v in enumerate(bank)}
    added = updated = 0
    for row in new_rows:
        item = {k: v for k, v in row.items() if k != "_lists"}
        if item["id"] in by_id:
            if item["id"] in PROMOTE_IDS and not keep_word(bank[by_id[item["id"]]]):
                bank[by_id[item["id"]]] = item
                updated += 1
            continue
        bank.append(item)
        by_id[item["id"]] = len(bank) - 1
        added += 1
    return added, updated


def append_ids(L: dict, ids: list[str]) -> None:
    seen = set(L.get("word_ids") or [])
    out = list(L.get("word_ids") or [])
    for wid in ids:
        if wid and wid not in seen:
            out.append(wid)
            seen.add(wid)
    L["word_ids"] = out


def prune(L: dict, lookup: dict, pred) -> None:
    L["word_ids"] = [wid for wid in (L.get("word_ids") or []) if pred(lookup.get(wid) or {})]


def fill(L: dict, bank: list, pred, min_n: int = MIN_SIZE) -> None:
    seen = set(L.get("word_ids") or [])
    out = list(L.get("word_ids") or [])
    for w in bank:
        if len(out) >= min_n:
            break
        if not keep_word(w):
            continue
        wid = w.get("id")
        if not wid or wid in seen:
            continue
        if pred(w):
            out.append(wid)
            seen.add(wid)
    L["word_ids"] = out


def blob(v: dict) -> str:
    return " ".join(
        [
            str(v.get("v1") or ""),
            str(v.get("meaning_en") or ""),
            str(v.get("category") or ""),
            " ".join(v.get("tags") or []),
        ]
    ).lower()


def main() -> None:
    bank = json.loads(VERB_DATA.read_text(encoding="utf-8"))
    meta = json.loads(VLISTS.read_text(encoding="utf-8"))
    lists = {L["id"]: L for L in meta.get("lists") or []}

    added, updated = merge_bank(bank, NEW)
    lookup = {v["id"]: v for v in bank}

    assigned: dict[str, list[str]] = {lid: [] for lid in VF_IDS}
    for row in NEW:
        for lid in row.get("_lists") or []:
            assigned.setdefault(lid, []).append(row["id"])

    for lid, ids in assigned.items():
        if lid == "verb-forms-master":
            continue
        L = lists.get(lid)
        if L:
            append_ids(L, ids)

    fill(lists["vf-daily-conversation"], bank, lambda v: (v.get("category") or "") in {"daily", "office", "travel"})
    fill(lists["vf-regular-starter"], bank, lambda v: not v.get("irregular"))
    fill(lists["vf-irregular-core"], bank, lambda v: bool(v.get("irregular")), min_n=60)
    fill(
        lists["vf-ielts-speaking"],
        bank,
        lambda v: (v.get("category") or "") in {"daily", "education"} or "speak" in blob(v),
    )
    fill(
        lists["vf-ielts-writing"],
        bank,
        lambda v: (v.get("category") or "") in {"ielts", "education"} or any(
            k in blob(v) for k in ("graph", "essay", "academic", "increase", "decline")
        ),
    )
    fill(
        lists["vf-ielts-reading"],
        bank,
        lambda v: (v.get("category") or "") == "ielts" or any(
            k in blob(v) for k in ("passage", "claim", "imply", "reveal", "research")
        ),
    )
    prune(lists["vf-regular-starter"], lookup, lambda v: not v.get("irregular"))
    prune(lists["vf-irregular-core"], lookup, lambda v: bool(v.get("irregular")))

    master = lists["verb-forms-master"]
    master["word_ids"] = [v["id"] for v in bank if keep_word(v)]
    master["cefr"] = "B1–C1"

    for lid in VF_IDS:
        L = lists.get(lid)
        if not L:
            continue
        L["word_ids"] = [wid for wid in (L.get("word_ids") or []) if keep_word(lookup.get(wid))]
        L["cefr"] = list_cefr_label(L.get("cefr"))

    VERB_DATA.write_text(json.dumps(bank, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    VLISTS.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"verb-forms.json: {len(bank)} total (+{added} new, {updated} promoted)")
    print("id\tcount")
    for lid in VF_IDS:
        L = lists.get(lid)
        n = len((L or {}).get("word_ids") or [])
        flag = " !" if n < 40 else ""
        print(f"{lid}\t{n}{flag}")


if __name__ == "__main__":
    main()

