# -*- coding: utf-8 -*-
"""
Build comprehensive verb learning list with:
- V1 (base), V2 (past), V3 (past participle), V4 (present participle / -ing), V5 (3rd person singular)
- phonetic (V1)
- meaning_bn, meaning_en
- example sentences for each tense form
- gerund usage explanation
- participle usage explanation
- irregular / regular flag
- category (daily, office, education, travel, …)
- CEFR level
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from cefr_policy import keep_word  # noqa: E402

VOCAB = ROOT / "data" / "vocabulary.json"
VLISTS = ROOT / "data" / "vocabulary-lists.json"
VERB_DATA = ROOT / "data" / "verb-forms.json"


def slug(w: str) -> str:
    return "verb:" + re.sub(r"[^a-z0-9]+", "-", w.strip().lower()).strip("-")


def V(
    v1: str,
    v2: str,
    v3: str,
    v4: str,
    v5: str,
    phonetic: str,
    meaning_en: str,
    meaning_bn: str,
    *,
    cefr: str = "A2",
    category: str = "daily",
    irregular: bool = True,
    examples: dict | None = None,
    gerund_use: str = "",
    gerund_ex: str = "",
    gerund_ex_bn: str = "",
    participle_use: str = "",
    participle_ex: str = "",
    participle_ex_bn: str = "",
    tags: list[str] | None = None,
) -> dict:
    return {
        "id": slug(v1),
        "v1": v1,
        "v2": v2,
        "v3": v3,
        "v4": v4,
        "v5": v5,
        "phonetic": phonetic,
        "meaning_en": meaning_en,
        "meaning_bn": meaning_bn,
        "cefr": cefr,
        "category": category,
        "irregular": irregular,
        "examples": examples or {},
        "gerund_use": gerund_use,
        "gerund_example": gerund_ex,
        "gerund_example_bn": gerund_ex_bn,
        "participle_use": participle_use,
        "participle_example": participle_ex,
        "participle_example_bn": participle_ex_bn,
        "tags": tags or ["verb", "grammar"],
    }


VERBS = [
    # ─── IRREGULAR ────────────────────────────────────────────────────────────
    V("be", "was/were", "been", "being", "is/are",
      "/biː/",
      "to exist; to have a quality",
      "হওয়া / থাকা",
      cefr="A1", category="daily",
      examples={
          "present": "She is a doctor.",
          "present_bn": "সে একজন ডাক্তার।",
          "past": "They were tired after the exam.",
          "past_bn": "পরীক্ষার পর তারা ক্লান্ত ছিল।",
          "perfect": "I have been busy all week.",
          "perfect_bn": "সারা সপ্তাহ আমি ব্যস্ত ছিলাম।",
          "continuous": "He is being careful.",
          "continuous_bn": "সে সতর্ক থাকছে।",
      },
      gerund_use="Gerund (being) — after prepositions or as subject",
      gerund_ex="Being honest is the best policy.",
      gerund_ex_bn="সৎ থাকাই সেরা নীতি।",
      participle_use="Past participle (been) — in perfect tenses & passive",
      participle_ex="She has been selected for the job.",
      participle_ex_bn="তাকে চাকরির জন্য বাছাই করা হয়েছে।"),

    V("have", "had", "had", "having", "has",
      "/hæv/",
      "to own; to experience",
      "থাকা / রাখা / অনুভব করা",
      cefr="A1", category="daily",
      examples={
          "present": "I have two siblings.",
          "present_bn": "আমার দুই ভাই-বোন আছে।",
          "past": "She had a meeting yesterday.",
          "past_bn": "গতকাল তার একটি মিটিং ছিল।",
          "perfect": "They have had breakfast already.",
          "perfect_bn": "তারা ইতিমধ্যে সকালের নাস্তা করেছে।",
          "continuous": "We are having a great time.",
          "continuous_bn": "আমরা দারুণ সময় কাটাচ্ছি।",
      },
      gerund_use="Gerund (having) — after prepositions",
      gerund_ex="Having a plan saves time.",
      gerund_ex_bn="পরিকল্পনা থাকলে সময় বাঁচে।",
      participle_use="Past participle (had) — auxiliary in past perfect",
      participle_ex="He had finished the work before noon.",
      participle_ex_bn="দুপুরের আগেই সে কাজ শেষ করেছিল।"),

    V("do", "did", "done", "doing", "does",
      "/duː/",
      "to perform an action",
      "করা",
      cefr="A1", category="daily",
      examples={
          "present": "I do my homework every evening.",
          "present_bn": "আমি প্রতি সন্ধ্যায় হোমওয়ার্ক করি।",
          "past": "She did her best in the exam.",
          "past_bn": "সে পরীক্ষায় সর্বোচ্চ চেষ্টা করেছিল।",
          "perfect": "We have done the project.",
          "perfect_bn": "আমরা প্রজেক্ট শেষ করেছি।",
          "continuous": "He is doing the dishes.",
          "continuous_bn": "সে বাসন ধুচ্ছে।",
      },
      gerund_use="Gerund (doing) — as subject or after preposition",
      gerund_ex="Doing exercise daily keeps you fit.",
      gerund_ex_bn="প্রতিদিন ব্যায়াম করলে সুস্থ থাকা যায়।",
      participle_use="Past participle (done) — passive voice",
      participle_ex="The work is done.",
      participle_ex_bn="কাজটি হয়ে গেছে।"),

    V("go", "went", "gone", "going", "goes",
      "/ɡəʊ/",
      "to move to a place",
      "যাওয়া",
      cefr="A1", category="travel",
      examples={
          "present": "I go to school by bus.",
          "present_bn": "আমি বাসে স্কুলে যাই।",
          "past": "They went to Cox's Bazar last month.",
          "past_bn": "তারা গত মাসে কক্সবাজার গিয়েছিল।",
          "perfect": "She has gone to the market.",
          "perfect_bn": "সে বাজারে গেছে।",
          "continuous": "We are going to Dhaka tomorrow.",
          "continuous_bn": "আমরা আগামীকাল ঢাকা যাচ্ছি।",
      },
      gerund_use="Gerund (going) — after enjoy/like/avoid etc.",
      gerund_ex="I enjoy going for morning walks.",
      gerund_ex_bn="আমি সকালে হাঁটতে যেতে পছন্দ করি।",
      participle_use="Past participle (gone) — present perfect; 'been' when returned",
      participle_ex="He has gone to London. (still there)",
      participle_ex_bn="সে লন্ডন চলে গেছে। (এখনও সেখানে)"),

    V("come", "came", "come", "coming", "comes",
      "/kʌm/",
      "to move towards the speaker",
      "আসা",
      cefr="A1", category="daily",
      examples={
          "present": "Come here, please.",
          "present_bn": "এখানে আসুন।",
          "past": "She came home late.",
          "past_bn": "সে দেরিতে বাড়ি এসেছিল।",
          "perfect": "They have come a long way.",
          "perfect_bn": "তারা অনেক পথ এসেছে।",
          "continuous": "He is coming right now.",
          "continuous_bn": "সে এখনই আসছে।",
      },
      gerund_use="Gerund (coming) — as subject or after preposition",
      gerund_ex="Coming early helps you get a good seat.",
      gerund_ex_bn="আগে আসলে ভালো জায়গা পাওয়া যায়।",
      participle_use="Present participle — action in progress alongside main verb",
      participle_ex="Coming down the stairs, she slipped.",
      participle_ex_bn="সিঁড়ি দিয়ে নামতে নামতে সে পড়ে গেল।"),

    V("get", "got", "got/gotten", "getting", "gets",
      "/ɡɛt/",
      "to obtain; to become; to arrive",
      "পাওয়া / হওয়া / পৌঁছানো",
      cefr="A1", category="daily",
      examples={
          "present": "I get up at 6 every morning.",
          "present_bn": "আমি প্রতিদিন সকাল ৬টায় উঠি।",
          "past": "He got a promotion last year.",
          "past_bn": "গত বছর সে পদোন্নতি পেয়েছিল।",
          "perfect": "She has got the visa.",
          "perfect_bn": "সে ভিসা পেয়েছে।",
          "continuous": "It is getting colder.",
          "continuous_bn": "আরও ঠান্ডা হচ্ছে।",
      },
      gerund_use="Gerund (getting) — after verbs like avoid, mind",
      gerund_ex="Getting a good score requires consistent practice.",
      gerund_ex_bn="ভালো স্কোর পেতে নিয়মিত অনুশীলন লাগে।",
      participle_use="Past participle (gotten — US) in perfect tenses",
      participle_ex="She has gotten much better at speaking.",
      participle_ex_bn="সে কথা বলায় অনেক ভালো হয়েছে। (US)"),

    V("give", "gave", "given", "giving", "gives",
      "/ɡɪv/",
      "to hand something to someone",
      "দেওয়া",
      cefr="A1", category="daily",
      examples={
          "present": "She gives clear instructions.",
          "present_bn": "সে স্পষ্ট নির্দেশনা দেয়।",
          "past": "The teacher gave us homework.",
          "past_bn": "শিক্ষক আমাদের হোমওয়ার্ক দিয়েছিলেন।",
          "perfect": "They have given their best.",
          "perfect_bn": "তারা সর্বোচ্চ দিয়েছে।",
          "continuous": "He is giving a speech.",
          "continuous_bn": "সে বক্তৃতা দিচ্ছে।",
      },
      gerund_use="Gerund (giving) — as subject",
      gerund_ex="Giving feedback helps students improve.",
      gerund_ex_bn="ফিডব্যাক দিলে শিক্ষার্থীরা উন্নতি করে।",
      participle_use="Past participle (given) — passive voice",
      participle_ex="Clear instructions were given to all students.",
      participle_ex_bn="সব শিক্ষার্থীকে স্পষ্ট নির্দেশনা দেওয়া হয়েছিল।"),

    V("take", "took", "taken", "taking", "takes",
      "/teɪk/",
      "to carry; to accept; to need",
      "নেওয়া / লাগা",
      cefr="A1", category="daily",
      examples={
          "present": "It takes 30 minutes by bus.",
          "present_bn": "বাসে ৩০ মিনিট লাগে।",
          "past": "She took the exam last week.",
          "past_bn": "সে গত সপ্তাহে পরীক্ষা দিয়েছিল।",
          "perfect": "He has taken his medicine.",
          "perfect_bn": "সে ওষুধ খেয়েছে।",
          "continuous": "We are taking a break.",
          "continuous_bn": "আমরা বিরতি নিচ্ছি।",
      },
      gerund_use="Gerund (taking) — after prepositions or as subject",
      gerund_ex="Taking notes helps you remember.",
      gerund_ex_bn="নোট নিলে মনে থাকে।",
      participle_use="Past participle (taken) — passive",
      participle_ex="The decision was taken by the committee.",
      participle_ex_bn="সিদ্ধান্ত কমিটি নিয়েছিল।"),

    V("make", "made", "made", "making", "makes",
      "/meɪk/",
      "to create or produce",
      "তৈরি করা / বানানো",
      cefr="A1", category="daily",
      examples={
          "present": "I make breakfast every morning.",
          "present_bn": "আমি প্রতিদিন সকালে নাস্তা বানাই।",
          "past": "She made a mistake in the test.",
          "past_bn": "সে পরীক্ষায় ভুল করেছিল।",
          "perfect": "They have made great progress.",
          "perfect_bn": "তারা দারুণ অগ্রগতি করেছে।",
          "continuous": "He is making a plan.",
          "continuous_bn": "সে পরিকল্পনা বানাচ্ছে।",
      },
      gerund_use="Gerund (making) — as subject",
      gerund_ex="Making friends is easier when you are confident.",
      gerund_ex_bn="আত্মবিশ্বাসী হলে বন্ধু বানানো সহজ।",
      participle_use="Past participle (made) — passive",
      participle_ex="The cake was made by my mother.",
      participle_ex_bn="কেকটি আমার মা বানিয়েছিলেন।"),

    V("know", "knew", "known", "knowing", "knows",
      "/nəʊ/",
      "to have information about something",
      "জানা",
      cefr="A1", category="education",
      examples={
          "present": "She knows five languages.",
          "present_bn": "সে পাঁচটি ভাষা জানে।",
          "past": "He knew the answer immediately.",
          "past_bn": "সে সঙ্গে সঙ্গে উত্তর জানত।",
          "perfect": "We have known each other for years.",
          "perfect_bn": "আমরা বছরের পর বছর ধরে একে অপরকে চিনি।",
          "continuous": "*(know rarely used in continuous)*",
          "continuous_bn": "'know' সাধারণত continuous-এ হয় না।",
      },
      gerund_use="Gerund (knowing) — 'not knowing' as subject",
      gerund_ex="Not knowing the rules caused confusion.",
      gerund_ex_bn="নিয়ম না জানার কারণে বিভ্রান্তি হয়েছিল।",
      participle_use="Past participle (known) — passive / adjective",
      participle_ex="She is known for her kindness.",
      participle_ex_bn="সে তার দয়ার জন্য পরিচিত।"),

    V("think", "thought", "thought", "thinking", "thinks",
      "/θɪŋk/",
      "to use your mind; to believe",
      "ভাবা / মনে করা",
      cefr="A1", category="daily",
      examples={
          "present": "I think you are right.",
          "present_bn": "আমি মনে করি তুমি ঠিক বলেছ।",
          "past": "She thought it was Monday.",
          "past_bn": "সে ভেবেছিল আজ সোমবার।",
          "perfect": "Have you thought about it?",
          "perfect_bn": "তুমি কি এটা নিয়ে ভেবেছ?",
          "continuous": "He is thinking carefully.",
          "continuous_bn": "সে সাবধানে ভাবছে।",
      },
      gerund_use="Gerund (thinking) — after prepositions",
      gerund_ex="Thinking positively changes your mindset.",
      gerund_ex_bn="ইতিবাচকভাবে ভাবলে মানসিকতা বদলায়।",
      participle_use="Present participle — simultaneous action",
      participle_ex="Thinking about the question, she smiled.",
      participle_ex_bn="প্রশ্নটি ভাবতে ভাবতে সে হাসল।"),

    V("see", "saw", "seen", "seeing", "sees",
      "/siː/",
      "to notice with your eyes; to understand",
      "দেখা / বোঝা",
      cefr="A1", category="daily",
      examples={
          "present": "I see what you mean.",
          "present_bn": "আমি বুঝতে পারছি তুমি কী বলতে চাইছ।",
          "past": "We saw a great film last night.",
          "past_bn": "গতকাল রাতে আমরা একটা দারুণ ছবি দেখেছিলাম।",
          "perfect": "Have you seen my keys?",
          "perfect_bn": "তুমি কি আমার চাবি দেখেছ?",
          "continuous": "She is seeing a specialist.",
          "continuous_bn": "সে একজন বিশেষজ্ঞ দেখাচ্ছে।",
      },
      gerund_use="Gerund (seeing) — after 'worth', 'enjoy', prepositions",
      gerund_ex="Seeing is believing.",
      gerund_ex_bn="দেখলেই বিশ্বাস হয়।",
      participle_use="Past participle (seen) — passive",
      participle_ex="The film has been seen by millions.",
      participle_ex_bn="ছবিটি লক্ষ লক্ষ মানুষ দেখেছে।"),

    V("say", "said", "said", "saying", "says",
      "/seɪ/",
      "to speak words",
      "বলা",
      cefr="A1", category="daily",
      examples={
          "present": "She says she is ready.",
          "present_bn": "সে বলে যে সে প্রস্তুত।",
          "past": "He said goodbye and left.",
          "past_bn": "সে বিদায় বলে চলে গেল।",
          "perfect": "I have said it many times.",
          "perfect_bn": "আমি এটা অনেকবার বলেছি।",
          "continuous": "She is saying something important.",
          "continuous_bn": "সে গুরুত্বপূর্ণ কিছু বলছে।",
      },
      gerund_use="Gerund (saying) — 'without saying', 'goes without saying'",
      gerund_ex="It goes without saying that practice matters.",
      gerund_ex_bn="এটা বলার অপেক্ষা রাখে না যে অনুশীলন গুরুত্বপূর্ণ।",
      participle_use="Present participle — describing speaker",
      participle_ex="'Let's go,' she said, saying nothing more.",
      participle_ex_bn="'চলো যাই,' সে বলল, আর কিছু না বলে।"),

    V("tell", "told", "told", "telling", "tells",
      "/tɛl/",
      "to inform someone",
      "বলা / জানানো (সরাসরি কাউকে)",
      cefr="A1", category="daily",
      examples={
          "present": "Tell me the truth.",
          "present_bn": "আমাকে সত্যি বলো।",
          "past": "He told us about his trip.",
          "past_bn": "সে আমাদের তার ভ্রমণের কথা বলেছিল।",
          "perfect": "She has told him already.",
          "perfect_bn": "সে ইতিমধ্যে তাকে বলেছে।",
          "continuous": "I am telling you the facts.",
          "continuous_bn": "আমি তোমাকে তথ্য বলছি।",
      },
      gerund_use="Gerund (telling) — as subject",
      gerund_ex="Telling the truth builds trust.",
      gerund_ex_bn="সত্য বললে বিশ্বাস তৈরি হয়।",
      participle_use="Past participle (told) — passive",
      participle_ex="We were told to wait outside.",
      participle_ex_bn="আমাদের বাইরে অপেক্ষা করতে বলা হয়েছিল।"),

    V("write", "wrote", "written", "writing", "writes",
      "/raɪt/",
      "to put words on paper or screen",
      "লেখা",
      cefr="A1", category="education",
      examples={
          "present": "She writes in her diary every night.",
          "present_bn": "সে প্রতি রাতে ডায়েরি লেখে।",
          "past": "He wrote a letter to his friend.",
          "past_bn": "সে তার বন্ধুকে চিঠি লিখেছিল।",
          "perfect": "I have written three essays this week.",
          "perfect_bn": "এই সপ্তাহে আমি তিনটি রচনা লিখেছি।",
          "continuous": "They are writing a report.",
          "continuous_bn": "তারা একটি রিপোর্ট লিখছে।",
      },
      gerund_use="Gerund (writing) — as subject or after prepositions",
      gerund_ex="Writing every day improves your skill.",
      gerund_ex_bn="প্রতিদিন লিখলে দক্ষতা বাড়ে।",
      participle_use="Past participle (written) — passive",
      participle_ex="The report was written by the team.",
      participle_ex_bn="রিপোর্টটি টিম লিখেছিল।"),

    V("read", "read", "read", "reading", "reads",
      "/riːd/ (V1) /rɛd/ (V2,V3)",
      "to look at written words",
      "পড়া",
      cefr="A1", category="education",
      examples={
          "present": "I read the newspaper every morning.",
          "present_bn": "আমি প্রতিদিন সকালে পত্রিকা পড়ি।",
          "past": "She read the whole book in one day.",
          "past_bn": "সে একদিনে পুরো বইটি পড়েছিল।",
          "perfect": "Have you read this novel?",
          "perfect_bn": "তুমি কি এই উপন্যাস পড়েছ?",
          "continuous": "He is reading a report.",
          "continuous_bn": "সে একটি রিপোর্ট পড়ছে।",
      },
      gerund_use="Gerund (reading) — as subject, after enjoy/love/hate",
      gerund_ex="Reading widely improves vocabulary.",
      gerund_ex_bn="ব্যাপক পড়লে শব্দভাণ্ডার বাড়ে।",
      participle_use="Present participle — simultaneous action",
      participle_ex="Reading the question carefully, he found the answer.",
      participle_ex_bn="প্রশ্নটি মনোযোগ দিয়ে পড়তে পড়তে সে উত্তর পেল।"),

    V("speak", "spoke", "spoken", "speaking", "speaks",
      "/spiːk/",
      "to say words; to communicate verbally",
      "কথা বলা",
      cefr="A1", category="daily",
      examples={
          "present": "She speaks three languages.",
          "present_bn": "সে তিনটি ভাষায় কথা বলে।",
          "past": "He spoke at the conference.",
          "past_bn": "সে কনফারেন্সে বক্তৃতা দিয়েছিল।",
          "perfect": "I have spoken to the manager.",
          "perfect_bn": "আমি ম্যানেজারের সঙ্গে কথা বলেছি।",
          "continuous": "They are speaking in English.",
          "continuous_bn": "তারা ইংরেজিতে কথা বলছে।",
      },
      gerund_use="Gerund (speaking) — as subject or after prepositions",
      gerund_ex="Speaking confidently is a skill you can learn.",
      gerund_ex_bn="আত্মবিশ্বাসের সঙ্গে কথা বলা একটি শেখার দক্ষতা।",
      participle_use="Past participle (spoken) — passive; adjective",
      participle_ex="English is spoken worldwide.",
      participle_ex_bn="ইংরেজি বিশ্বজুড়ে কথা বলা হয়।"),

    V("listen", "listened", "listened", "listening", "listens",
      "/ˈlɪs.ən/",
      "to pay attention to sound",
      "মনোযোগ দিয়ে শোনা",
      cefr="A1", category="daily",
      irregular=False,
      examples={
          "present": "Please listen carefully.",
          "present_bn": "মনোযোग দিয়ে শুনুন।",
          "past": "She listened to the lecture twice.",
          "past_bn": "সে লেকচার দুবার শুনেছিল।",
          "perfect": "Have you listened to this podcast?",
          "perfect_bn": "তুমি কি এই পডকাস্ট শুনেছ?",
          "continuous": "He is listening to music.",
          "continuous_bn": "সে গান শুনছে।",
      },
      gerund_use="Gerund (listening) — as subject or after 'enjoy/practice'",
      gerund_ex="Listening to podcasts builds fluency.",
      gerund_ex_bn="পডকাস্ট শুনলে ফ্লুয়েন্সি বাড়ে।",
      participle_use="Present participle — as adjective or simultaneous action",
      participle_ex="The listening skill is tested in Part 1.",
      participle_ex_bn="লিসেনিং দক্ষতা পার্ট ১-এ পরীক্ষা করা হয়।"),

    V("learn", "learned/learnt", "learned/learnt", "learning", "learns",
      "/lɜːn/",
      "to gain knowledge or skill",
      "শেখা",
      cefr="A1", category="education",
      irregular=False,
      examples={
          "present": "Children learn quickly.",
          "present_bn": "শিশুরা দ্রুত শেখে।",
          "past": "I learned/learnt to drive last year.",
          "past_bn": "আমি গত বছর গাড়ি চালানো শিখেছিলাম।",
          "perfect": "She has learned a lot this month.",
          "perfect_bn": "এই মাসে সে অনেক কিছু শিখেছে।",
          "continuous": "We are learning new vocabulary.",
          "continuous_bn": "আমরা নতুন শব্দ শিখছি।",
      },
      gerund_use="Gerund (learning) — as subject or after enjoy/keep",
      gerund_ex="Learning a language takes patience.",
      gerund_ex_bn="একটি ভাষা শিখতে ধৈর্য লাগে।",
      participle_use="Past participle — passive / adjective (learned = scholarly)",
      participle_ex="Mistakes are learned from, not feared.",
      participle_ex_bn="ভুল থেকে শেখা যায়, ভয় নয়।"),

    V("study", "studied", "studied", "studying", "studies",
      "/ˈstʌd.i/",
      "to read and learn about a subject",
      "পড়াশোনা করা / অধ্যয়ন করা",
      cefr="A1", category="education",
      irregular=False,
      examples={
          "present": "I study for two hours every day.",
          "present_bn": "আমি প্রতিদিন দুই ঘণ্টা পড়াশোনা করি।",
          "past": "She studied medicine at university.",
          "past_bn": "সে বিশ্ববিদ্যালয়ে মেডিসিন পড়েছিল।",
          "perfect": "They have studied the report.",
          "perfect_bn": "তারা রিপোর্টটি পড়েছে।",
          "continuous": "He is studying for his exam.",
          "continuous_bn": "সে পরীক্ষার জন্য পড়ছে।",
      },
      gerund_use="Gerund (studying) — as subject",
      gerund_ex="Studying abroad expands your worldview.",
      gerund_ex_bn="বিদেশে পড়লে দৃষ্টিভঙ্গি প্রসারিত হয়।",
      participle_use="Past participle (studied) — passive",
      participle_ex="The topic has been studied by many researchers.",
      participle_ex_bn="বিষয়টি অনেক গবেষক অধ্যয়ন করেছেন।"),

    V("work", "worked", "worked", "working", "works",
      "/wɜːk/",
      "to do a job; to function",
      "কাজ করা",
      cefr="A1", category="office",
      irregular=False,
      examples={
          "present": "She works in a hospital.",
          "present_bn": "সে হাসপাতালে কাজ করে।",
          "past": "He worked overtime last week.",
          "past_bn": "গত সপ্তাহে সে ওভারটাইম করেছিল।",
          "perfect": "They have worked together for years.",
          "perfect_bn": "তারা বছরের পর বছর একসঙ্গে কাজ করেছে।",
          "continuous": "She is working on a new project.",
          "continuous_bn": "সে একটি নতুন প্রজেক্টে কাজ করছে।",
      },
      gerund_use="Gerund (working) — as subject or after enjoy/hate/stop",
      gerund_ex="Working from home saves commuting time.",
      gerund_ex_bn="বাড়িতে কাজ করলে যাতায়াতের সময় বাঁচে।",
      participle_use="Present participle — as adjective",
      participle_ex="She is a working mother.",
      participle_ex_bn="সে একজন কর্মজীবী মা।"),

    V("help", "helped", "helped", "helping", "helps",
      "/hɛlp/",
      "to make it easier for someone",
      "সাহায্য করা",
      cefr="A1", category="daily",
      irregular=False,
      examples={
          "present": "Can you help me?",
          "present_bn": "তুমি কি আমাকে সাহায্য করতে পারবে?",
          "past": "She helped her friend move houses.",
          "past_bn": "সে তার বন্ধুকে বাড়ি বদলাতে সাহায্য করেছিল।",
          "perfect": "They have helped many students.",
          "perfect_bn": "তারা অনেক শিক্ষার্থীকে সাহায্য করেছে।",
          "continuous": "He is helping in the kitchen.",
          "continuous_bn": "সে রান্নাঘরে সাহায্য করছে।",
      },
      gerund_use="Gerund (helping) — as subject",
      gerund_ex="Helping others makes you feel good.",
      gerund_ex_bn="অন্যদের সাহায্য করলে ভালো লাগে।",
      participle_use="Past participle (helped) — passive",
      participle_ex="Many people were helped by the programme.",
      participle_ex_bn="প্রোগ্রামটি অনেককে সাহায্য করেছিল।"),

    V("run", "ran", "run", "running", "runs",
      "/rʌn/",
      "to move fast on foot; to manage",
      "দৌড়ানো / পরিচালনা করা",
      cefr="A2", category="daily",
      examples={
          "present": "He runs 5 km every morning.",
          "present_bn": "সে প্রতিদিন সকালে ৫ কিমি দৌড়ায়।",
          "past": "She ran the whole marathon.",
          "past_bn": "সে পুরো ম্যারাথন দৌড়েছিল।",
          "perfect": "They have run this company for ten years.",
          "perfect_bn": "তারা দশ বছর ধরে এই কোম্পানি পরিচালনা করছে।",
          "continuous": "We are running out of time.",
          "continuous_bn": "আমাদের সময় শেষ হয়ে আসছে।",
      },
      gerund_use="Gerund (running) — as subject or after enjoy/like/hate",
      gerund_ex="Running a business needs dedication.",
      gerund_ex_bn="ব্যবসা পরিচালনায় নিষ্ঠা লাগে।",
      participle_use="Present participle — as adjective",
      participle_ex="Running water is essential in hospitals.",
      participle_ex_bn="হাসপাতালে বহমান পানি অপরিহার্য।"),

    V("eat", "ate", "eaten", "eating", "eats",
      "/iːt/",
      "to put food in your mouth and swallow",
      "খাওয়া",
      cefr="A1", category="food",
      examples={
          "present": "She eats vegetables every day.",
          "present_bn": "সে প্রতিদিন শাকসবজি খায়।",
          "past": "We ate lunch together.",
          "past_bn": "আমরা একসঙ্গে দুপুরের খাবার খেয়েছিলাম।",
          "perfect": "Have you eaten yet?",
          "perfect_bn": "তুমি কি এখনও খেয়েছ?",
          "continuous": "He is eating a banana.",
          "continuous_bn": "সে কলা খাচ্ছে।",
      },
      gerund_use="Gerund (eating) — as subject or after enjoy/avoid/stop",
      gerund_ex="Eating slowly aids digestion.",
      gerund_ex_bn="আস্তে খেলে হজম ভালো হয়।",
      participle_use="Past participle (eaten) — passive",
      participle_ex="The food had been eaten before we arrived.",
      participle_ex_bn="আমরা পৌঁছানোর আগেই খাবার খাওয়া হয়ে গিয়েছিল।"),

    V("sleep", "slept", "slept", "sleeping", "sleeps",
      "/sliːp/",
      "to rest with eyes closed",
      "ঘুমানো",
      cefr="A1", category="daily",
      examples={
          "present": "Adults need to sleep 7–8 hours.",
          "present_bn": "প্রাপ্তবয়স্কদের ৭–৮ ঘণ্টা ঘুমানো দরকার।",
          "past": "She slept through the alarm.",
          "past_bn": "সে অ্যালার্ম না শুনে ঘুমিয়ে রইল।",
          "perfect": "I have not slept well this week.",
          "perfect_bn": "এই সপ্তাহে আমার ঘুম ভালো হয়নি।",
          "continuous": "The baby is sleeping.",
          "continuous_bn": "বাচ্চা ঘুমাচ্ছে।",
      },
      gerund_use="Gerund (sleeping) — as subject",
      gerund_ex="Sleeping early improves focus.",
      gerund_ex_bn="আগে ঘুমালে মনোযোগ বাড়ে।",
      participle_use="Present participle — simultaneous action",
      participle_ex="He fell asleep while sleeping in class.",
      participle_ex_bn="ক্লাসে ঘুমাতে ঘুমাতে সে ঘুমিয়ে পড়ল।"),

    V("buy", "bought", "bought", "buying", "buys",
      "/baɪ/",
      "to get something by paying money",
      "কেনা",
      cefr="A1", category="shopping",
      examples={
          "present": "She buys groceries online.",
          "present_bn": "সে অনলাইনে মুদিখানার মালপত্র কেনে।",
          "past": "He bought a new laptop.",
          "past_bn": "সে একটি নতুন ল্যাপটপ কিনেছিল।",
          "perfect": "They have bought the house.",
          "perfect_bn": "তারা বাড়িটি কিনেছে।",
          "continuous": "I am buying a gift for my mother.",
          "continuous_bn": "আমি মায়ের জন্য উপহার কিনছি।",
      },
      gerund_use="Gerund (buying) — as subject or after enjoy/avoid",
      gerund_ex="Buying second-hand saves money.",
      gerund_ex_bn="পুরনো জিনিস কিনলে অর্থ সাশ্রয় হয়।",
      participle_use="Past participle (bought) — passive",
      participle_ex="The ticket was bought online.",
      participle_ex_bn="টিকিট অনলাইনে কেনা হয়েছিল।"),

    V("find", "found", "found", "finding", "finds",
      "/faɪnd/",
      "to discover; to locate",
      "খুঁজে পাওয়া",
      cefr="A1", category="daily",
      examples={
          "present": "I find grammar interesting.",
          "present_bn": "আমার কাছে গ্রামার মজার।",
          "past": "She found her keys under the sofa.",
          "past_bn": "সে সোফার নিচে তার চাবি পেয়েছিল।",
          "perfect": "We have found a solution.",
          "perfect_bn": "আমরা একটি সমাধান খুঁজে পেয়েছি।",
          "continuous": "They are finding it difficult to agree.",
          "continuous_bn": "তারা একমত হতে কঠিন পাচ্ছে।",
      },
      gerund_use="Gerund (finding) — as subject",
      gerund_ex="Finding a good teacher makes a big difference.",
      gerund_ex_bn="ভালো শিক্ষক পেলে অনেক পার্থক্য হয়।",
      participle_use="Past participle (found) — passive",
      participle_ex="A cure has not been found yet.",
      participle_ex_bn="এখনও কোনো নিরাময় পাওয়া যায়নি।"),

    V("feel", "felt", "felt", "feeling", "feels",
      "/fiːl/",
      "to experience an emotion or sensation",
      "অনুভব করা / মনে হওয়া",
      cefr="A1", category="health",
      examples={
          "present": "I feel tired after class.",
          "present_bn": "ক্লাসের পর আমি ক্লান্ত অনুভব করি।",
          "past": "He felt proud of his achievement.",
          "past_bn": "সে তার সাফল্যে গর্বিত অনুভব করেছিল।",
          "perfect": "Have you felt this way before?",
          "perfect_bn": "তুমি কি আগে এভাবে অনুভব করেছ?",
          "continuous": "She is feeling much better now.",
          "continuous_bn": "সে এখন অনেক ভালো বোধ করছে।",
      },
      gerund_use="Gerund (feeling) — as subject",
      gerund_ex="Feeling confident helps in interviews.",
      gerund_ex_bn="আত্মবিশ্বাসী অনুভব করলে ইন্টারভিউতে সুবিধা হয়।",
      participle_use="Present participle — emotion clause",
      participle_ex="Feeling nervous, she took a deep breath.",
      participle_ex_bn="নার্ভাস অনুভব করতে করতে সে গভীর শ্বাস নিল।"),

    V("begin", "began", "begun", "beginning", "begins",
      "/bɪˈɡɪn/",
      "to start",
      "শুরু করা",
      cefr="A1", category="daily",
      examples={
          "present": "Class begins at 9 a.m.",
          "present_bn": "ক্লাস সকাল ৯টায় শুরু হয়।",
          "past": "She began to feel better.",
          "past_bn": "সে ভালো অনুভব করতে শুরু করেছিল।",
          "perfect": "The project has just begun.",
          "perfect_bn": "প্রজেক্টটি মাত্র শুরু হয়েছে।",
          "continuous": "Students are beginning their exams.",
          "continuous_bn": "শিক্ষার্থীরা তাদের পরীক্ষা শুরু করছে।",
      },
      gerund_use="Gerund (beginning) — as subject",
      gerund_ex="Beginning early gives you an advantage.",
      gerund_ex_bn="আগে শুরু করলে সুবিধা পাওয়া যায়।",
      participle_use="Past participle (begun) — perfect tense",
      participle_ex="Construction has begun on the new road.",
      participle_ex_bn="নতুন রাস্তায় নির্মাণ শুরু হয়েছে।"),

    V("break", "broke", "broken", "breaking", "breaks",
      "/breɪk/",
      "to separate into pieces; to stop something",
      "ভাঙা / বিরতি নেওয়া",
      cefr="A2", category="daily",
      examples={
          "present": "Take a break every hour.",
          "present_bn": "প্রতি ঘণ্টায় বিরতি নিন।",
          "past": "He broke his arm playing cricket.",
          "past_bn": "ক্রিকেট খেলতে গিয়ে তার হাত ভেঙেছিল।",
          "perfect": "She has broken the school record.",
          "perfect_bn": "সে স্কুলের রেকর্ড ভেঙেছে।",
          "continuous": "They are breaking old habits.",
          "continuous_bn": "তারা পুরনো অভ্যাস ভাঙছে।",
      },
      gerund_use="Gerund (breaking) — as subject or after avoid",
      gerund_ex="Breaking bad habits takes time.",
      gerund_ex_bn="খারাপ অভ্যাস ভাঙতে সময় লাগে।",
      participle_use="Past participle (broken) — passive / adjective",
      participle_ex="The window is broken.",
      participle_ex_bn="জানালাটি ভাঙা।"),

    V("meet", "met", "met", "meeting", "meets",
      "/miːt/",
      "to see someone for the first time or by plan",
      "দেখা করা / মিলিত হওয়া",
      cefr="A1", category="daily",
      examples={
          "present": "We meet every Monday.",
          "present_bn": "আমরা প্রতি সোমবার দেখা করি।",
          "past": "I met her at a conference.",
          "past_bn": "আমি তার সঙ্গে কনফারেন্সে দেখা হয়েছিল।",
          "perfect": "They have met before.",
          "perfect_bn": "তারা আগে দেখা করেছে।",
          "continuous": "She is meeting the clients at noon.",
          "continuous_bn": "সে দুপুরে ক্লায়েন্টদের সঙ্গে দেখা করছে।",
      },
      gerund_use="Gerund (meeting) — as subject or after enjoy",
      gerund_ex="Meeting new people expands your network.",
      gerund_ex_bn="নতুন মানুষের সঙ্গে দেখা করলে নেটওয়ার্ক বাড়ে।",
      participle_use="Past participle (met) — passive",
      participle_ex="All targets were met on time.",
      participle_ex_bn="সব লক্ষ্যমাত্রা সময়মতো পূরণ করা হয়েছিল।"),

    V("bring", "brought", "brought", "bringing", "brings",
      "/brɪŋ/",
      "to carry something here",
      "নিয়ে আসা",
      cefr="A2", category="daily",
      examples={
          "present": "Please bring your ID card.",
          "present_bn": "অনুগ্রহ করে আপনার আইডি কার্ড নিয়ে আসুন।",
          "past": "She brought gifts for everyone.",
          "past_bn": "সে সবার জন্য উপহার নিয়ে এসেছিল।",
          "perfect": "Have you brought the documents?",
          "perfect_bn": "তুমি কি নথিপত্র নিয়ে এসেছ?",
          "continuous": "He is bringing the car around.",
          "continuous_bn": "সে গাড়ি নিয়ে আসছে।",
      },
      gerund_use="Gerund (bringing) — as subject",
      gerund_ex="Bringing a dictionary helps in the reading test.",
      gerund_ex_bn="রিডিং পরীক্ষায় ডিকশনারি আনলে সুবিধা হয়।",
      participle_use="Past participle (brought) — passive",
      participle_ex="New technology has been brought into schools.",
      participle_ex_bn="স্কুলে নতুন প্রযুক্তি আনা হয়েছে।"),

    V("show", "showed", "shown", "showing", "shows",
      "/ʃəʊ/",
      "to let someone see; to demonstrate",
      "দেখানো / প্রদর্শন করা",
      cefr="A1", category="daily",
      examples={
          "present": "The graph shows a rise in sales.",
          "present_bn": "গ্রাফ বিক্রিতে বৃদ্ধি দেখায়।",
          "past": "She showed me how to cook.",
          "past_bn": "সে আমাকে রান্না শিখিয়েছিল।",
          "perfect": "Studies have shown its benefits.",
          "perfect_bn": "গবেষণায় এর উপকার দেখানো হয়েছে।",
          "continuous": "He is showing the new students around.",
          "continuous_bn": "সে নতুন শিক্ষার্থীদের চারপাশ দেখাচ্ছে।",
      },
      gerund_use="Gerund (showing) — as subject",
      gerund_ex="Showing respect earns respect.",
      gerund_ex_bn="সম্মান দেখালে সম্মান পাওয়া যায়।",
      participle_use="Past participle (shown) — passive",
      participle_ex="It has been shown that sleep aids memory.",
      participle_ex_bn="দেখানো হয়েছে যে ঘুম স্মৃতিশক্তি বাড়ায়।"),

    V("try", "tried", "tried", "trying", "tries",
      "/traɪ/",
      "to make an effort; to attempt",
      "চেষ্টা করা",
      cefr="A1", category="daily",
      irregular=False,
      examples={
          "present": "Always try your best.",
          "present_bn": "সর্বদা সর্বোচ্চ চেষ্টা করুন।",
          "past": "She tried to call him three times.",
          "past_bn": "সে তাকে তিনবার ফোন করার চেষ্টা করেছিল।",
          "perfect": "Have you tried this method?",
          "perfect_bn": "তুমি কি এই পদ্ধতি চেষ্টা করেছ?",
          "continuous": "He is trying a new approach.",
          "continuous_bn": "সে নতুন পদ্ধতি চেষ্টা করছে।",
      },
      gerund_use="Gerund (trying) — after 'worth', 'keep', 'avoid'",
      gerund_ex="Trying new things builds confidence.",
      gerund_ex_bn="নতুন জিনিস চেষ্টা করলে আত্মবিশ্বাস বাড়ে।",
      participle_use="Present participle — continuous action",
      participle_ex="Trying hard, she finally passed.",
      participle_ex_bn="কঠোর চেষ্টা করে অবশেষে সে পাস করল।"),

    V("keep", "kept", "kept", "keeping", "keeps",
      "/kiːp/",
      "to continue to have; to maintain",
      "রাখা / বজায় রাখা",
      cefr="A2", category="daily",
      examples={
          "present": "Keep your notes organised.",
          "present_bn": "তোমার নোট গুছিয়ে রাখো।",
          "past": "He kept working despite the noise.",
          "past_bn": "শব্দ সত্ত্বেও সে কাজ চালিয়ে গিয়েছিল।",
          "perfect": "She has kept her promise.",
          "perfect_bn": "সে তার প্রতিশ্রুতি রেখেছে।",
          "continuous": "They are keeping quiet.",
          "continuous_bn": "তারা চুপ থাকছে।",
      },
      gerund_use="'keep + gerund' means continue doing",
      gerund_ex="Keep practising and you will improve.",
      gerund_ex_bn="অনুশীলন চালিয়ে যাও, উন্নতি হবে।",
      participle_use="Past participle (kept) — passive",
      participle_ex="The files were kept safely.",
      participle_ex_bn="ফাইলগুলো নিরাপদে রাখা ছিল।"),

    V("increase", "increased", "increased", "increasing", "increases",
      "/ɪnˈkriːs/",
      "to become or make larger",
      "বাড়া / বাড়ানো",
      cefr="A2", category="ielts",
      irregular=False,
      examples={
          "present": "Demand increases every year.",
          "present_bn": "প্রতি বছর চাহিদা বাড়ে।",
          "past": "Sales increased by 20% last quarter.",
          "past_bn": "গত প্রান্তিকে বিক্রি ২০% বেড়েছিল।",
          "perfect": "Prices have increased sharply.",
          "perfect_bn": "দাম তীব্রভাবে বেড়েছে।",
          "continuous": "Traffic is increasing rapidly.",
          "continuous_bn": "ট্রাফিক দ্রুত বাড়ছে।",
      },
      gerund_use="Gerund (increasing) — as subject or after focus on",
      gerund_ex="Increasing productivity requires motivation.",
      gerund_ex_bn="উৎপাদনশীলতা বাড়াতে অনুপ্রেরণা লাগে।",
      participle_use="Present participle (increasing) — as adjective",
      participle_ex="There is an increasing demand for nurses.",
      participle_ex_bn="নার্সের ক্রমবর্ধমান চাহিদা রয়েছে।"),

    V("decide", "decided", "decided", "deciding", "decides",
      "/dɪˈsaɪd/",
      "to choose after thinking",
      "সিদ্ধান্ত নেওয়া",
      cefr="A2", category="daily",
      irregular=False,
      examples={
          "present": "She decides everything for the team.",
          "present_bn": "সে টিমের সব কিছু সিদ্ধান্ত নেয়।",
          "past": "He decided to study abroad.",
          "past_bn": "সে বিদেশে পড়ার সিদ্ধান্ত নিয়েছিল।",
          "perfect": "Have you decided yet?",
          "perfect_bn": "তুমি কি এখনও সিদ্ধান্ত নিয়েছ?",
          "continuous": "We are deciding on the menu.",
          "continuous_bn": "আমরা মেনু নির্ধারণ করছি।",
      },
      gerund_use="Gerund (deciding) — as subject",
      gerund_ex="Deciding quickly is sometimes necessary.",
      gerund_ex_bn="দ্রুত সিদ্ধান্ত নেওয়া কখনও কখনও দরকার।",
      participle_use="Past participle (decided) — passive / adjective",
      participle_ex="The matter is decided.",
      participle_ex_bn="বিষয়টি সিদ্ধান্ত নেওয়া হয়েছে।"),

    V("accept", "accepted", "accepted", "accepting", "accepts",
      "/əkˈsɛpt/",
      "to agree to receive or take",
      "গ্রহণ করা / মেনে নেওয়া",
      cefr="B1", category="office",
      irregular=False,
      examples={
          "present": "She accepts all feedback positively.",
          "present_bn": "সে সব ফিডব্যাক ইতিবাচকভাবে গ্রহণ করে।",
          "past": "He accepted the job offer.",
          "past_bn": "সে চাকরির অফার গ্রহণ করেছিল।",
          "perfect": "We have accepted the terms.",
          "perfect_bn": "আমরা শর্তগুলো মেনে নিয়েছি।",
          "continuous": "The university is accepting applications.",
          "continuous_bn": "বিশ্ববিদ্যালয় আবেদন গ্রহণ করছে।",
      },
      gerund_use="Gerund (accepting) — as subject",
      gerund_ex="Accepting mistakes is the first step to improvement.",
      gerund_ex_bn="ভুল মেনে নেওয়া উন্নতির প্রথম পদক্ষেপ।",
      participle_use="Past participle (accepted) — passive / adjective",
      participle_ex="His paper was accepted by the journal.",
      participle_ex_bn="তার গবেষণাপত্র জার্নালে গৃহীত হয়েছে।"),

    V("achieve", "achieved", "achieved", "achieving", "achieves",
      "/əˈtʃiːv/",
      "to succeed in doing something difficult",
      "অর্জন করা / সাফল্য পাওয়া",
      cefr="B1", category="education",
      irregular=False,
      examples={
          "present": "Hard work helps you achieve your goals.",
          "present_bn": "কঠোর পরিশ্রম লক্ষ্য অর্জনে সাহায্য করে।",
          "past": "She achieved a high band score.",
          "past_bn": "সে উচ্চ ব্যান্ড স্কোর অর্জন করেছিল।",
          "perfect": "They have achieved a lot this year.",
          "perfect_bn": "এই বছর তারা অনেক অর্জন করেছে।",
          "continuous": "We are achieving our targets.",
          "continuous_bn": "আমরা আমাদের লক্ষ্যমাত্রা অর্জন করছি।",
      },
      gerund_use="Gerund (achieving) — as subject",
      gerund_ex="Achieving fluency takes daily effort.",
      gerund_ex_bn="ফ্লুয়েন্সি অর্জনে দৈনিক প্রচেষ্টা লাগে।",
      participle_use="Past participle (achieved) — passive",
      participle_ex="The goal was achieved ahead of schedule.",
      participle_ex_bn="লক্ষ্য নির্ধারিত সময়ের আগেই অর্জিত হয়েছিল।"),

    V("avoid", "avoided", "avoided", "avoiding", "avoids",
      "/əˈvɔɪd/",
      "to stay away from something",
      "এড়িয়ে চলা",
      cefr="B1", category="daily",
      irregular=False,
      examples={
          "present": "Avoid making the same mistake twice.",
          "present_bn": "একই ভুল দুবার করা এড়িয়ে চলুন।",
          "past": "He avoided the busy road.",
          "past_bn": "সে ব্যস্ত রাস্তা এড়িয়ে গিয়েছিল।",
          "perfect": "She has avoided eating junk food.",
          "perfect_bn": "সে জাংক ফুড খাওয়া এড়িয়ে চলেছে।",
          "continuous": "They are avoiding the subject.",
          "continuous_bn": "তারা বিষয়টি এড়িয়ে যাচ্ছে।",
      },
      gerund_use="'avoid + gerund' — never followed by infinitive",
      gerund_ex="Avoid using slang in formal essays.",
      gerund_ex_bn="আনুষ্ঠানিক রচনায় স্ল্যাং ব্যবহার এড়িয়ে চলুন।",
      participle_use="Past participle (avoided) — passive",
      participle_ex="The error could have been avoided.",
      participle_ex_bn="ভুলটি এড়ানো যেত।",
      tags=["verb", "grammar", "ielts"]),
]


def save_verb_data() -> None:
    VERB_DATA.parent.mkdir(parents=True, exist_ok=True)
    VERB_DATA.write_text(json.dumps(VERBS, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def upsert_vocab_list() -> None:
    vmeta = json.loads(VLISTS.read_text(encoding="utf-8"))
    lists = vmeta.get("lists") or []
    ids = [v["id"] for v in VERBS if keep_word(v)]
    entry = {
        "id": "verb-forms-master",
        "title": "Verb Forms Master List",
        "title_bn": "ক্রিয়া রূপ মাস্টার লিস্ট",
        "description": "B1+ verb forms with gerund and participle usage for IELTS/TOEFL/PTE.",
        "description_bn": "B1+ verb-এর V1–V5 + gerund ও participle ব্যবহার সহ।",
        "cefr": "B1–C1",
        "word_ids": ids,
    }
    for i, L in enumerate(lists):
        if L.get("id") == "verb-forms-master":
            lists[i] = entry
            vmeta["lists"] = lists
            VLISTS.write_text(json.dumps(vmeta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            return
    lists.append(entry)
    vmeta["lists"] = lists
    VLISTS.write_text(json.dumps(vmeta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    save_verb_data()
    upsert_vocab_list()
    irreg = sum(1 for v in VERBS if v["irregular"])
    reg = len(VERBS) - irreg
    print(f"verb-forms.json: {len(VERBS)} verbs ({irreg} irregular, {reg} regular)")
    print("vocab list: verb-forms-master updated")


if __name__ == "__main__":
    main()
