# -*- coding: utf-8 -*-
"""Add extra verbs + curated verb-form study lists (daily, IELTS skills)."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
import sys
sys.path.insert(0, str(ROOT / "tools"))
from cefr_policy import keep_word, list_cefr_label  # noqa: E402

VERB_DATA = ROOT / "data" / "verb-forms.json"
VLISTS = ROOT / "data" / "vocabulary-lists.json"


def slug(w: str) -> str:
    return "verb:" + re.sub(r"[^a-z0-9]+", "-", w.strip().lower()).strip("-")


def V(
    v1: str,
    v2: str,
    v3: str,
    v4: str,
    v5: str,
    phonetic: str,
    meaning_en: str,
    meaning_bn: str,
    *,
    cefr: str = "B1",
    category: str = "daily",
    irregular: bool = False,
    present: str = "",
    present_bn: str = "",
    past: str = "",
    past_bn: str = "",
    perfect: str = "",
    perfect_bn: str = "",
    continuous: str = "",
    continuous_bn: str = "",
    gerund_ex: str = "",
    gerund_ex_bn: str = "",
    part_ex: str = "",
    part_ex_bn: str = "",
    tags: list[str] | None = None,
) -> dict:
    return {
        "id": slug(v1),
        "v1": v1,
        "v2": v2,
        "v3": v3,
        "v4": v4,
        "v5": v5,
        "phonetic": phonetic,
        "meaning_en": meaning_en,
        "meaning_bn": meaning_bn,
        "cefr": cefr,
        "category": category,
        "irregular": irregular,
        "examples": {
            "present": present,
            "present_bn": present_bn,
            "past": past,
            "past_bn": past_bn,
            "perfect": perfect or f"I have {v3} this before.",
            "perfect_bn": perfect_bn or "আমি আগে এটা করেছি।",
            "continuous": continuous or f"She is {v4} now.",
            "continuous_bn": continuous_bn or "সে এখন এটা করছে।",
        },
        "gerund_use": f"Gerund ({v4}) — as subject or after enjoy/avoid/keep",
        "gerund_example": gerund_ex or f"{v4.capitalize()} every day helps you improve.",
        "gerund_example_bn": gerund_ex_bn or "প্রতিদিন করলে উন্নতি হয়।",
        "participle_use": f"Past participle ({v3}) — perfect tenses and passive",
        "participle_example": part_ex or f"The work has been {v3}.",
        "participle_example_bn": part_ex_bn or "কাজটি হয়ে গেছে।",
        "tags": tags or ["verb", "grammar"],
    }


NEW_VERBS = [
    V("ask", "asked", "asked", "asking", "asks", "/ɑːsk/",
      "to request information or help", "জিজ্ঞাসা করা / চাওয়া",
      cefr="A1", present="Can I ask a question?", present_bn="আমি কি একটা প্রশ্ন করতে পারি?",
      past="She asked for directions.", past_bn="সে পথ জিজ্ঞেস করেছিল।",
      gerund_ex="Asking questions helps you learn.", gerund_ex_bn="প্রশ্ন করলে শেখা সহজ হয়।"),
    V("want", "wanted", "wanted", "wanting", "wants", "/wɒnt/",
      "to wish for something", "চাওয়া",
      cefr="A1", present="I want a glass of water.", present_bn="আমি এক গ্লাস পানি চাই।",
      past="He wanted to go home.", past_bn="সে বাড়ি যেতে চেয়েছিল।"),
    V("need", "needed", "needed", "needing", "needs", "/niːd/",
      "to require something", "প্রয়োজন হওয়া",
      cefr="A1", present="You need more practice.", present_bn="তোমার আরও অনুশীলন দরকার।",
      past="We needed extra time.", past_bn="আমাদের অতিরিক্ত সময় দরকার হয়েছিল।"),
    V("like", "liked", "liked", "liking", "likes", "/laɪk/",
      "to enjoy or find pleasant", "পছন্দ করা",
      cefr="A1", present="I like spicy food.", present_bn="আমি ঝাল খাবার পছন্দ করি।",
      past="She liked the movie.", past_bn="সে সিনেমাটা পছন্দ করেছিল।",
      gerund_ex="I like reading before bed.", gerund_ex_bn="ঘুমানোর আগে পড়তে পছন্দ করি।"),
    V("live", "lived", "lived", "living", "lives", "/lɪv/",
      "to stay in a place; to be alive", "বাস করা / বেঁচে থাকা",
      cefr="A1", present="They live in Dhaka.", present_bn="তারা ঢাকায় থাকেন।",
      past="I lived near the river.", past_bn="আমি নদীর কাছে থাকতাম।"),
    V("use", "used", "used", "using", "uses", "/juːz/",
      "to do something with a tool or method", "ব্যবহার করা",
      cefr="A1", present="We use English at work.", present_bn="কাজে আমরা ইংরেজি ব্যবহার করি।",
      past="She used a dictionary.", past_bn="সে ডিকশনারি ব্যবহার করেছিল।"),
    V("call", "called", "called", "calling", "calls", "/kɔːl/",
      "to phone someone; to name", "ফোন করা / ডাকা",
      cefr="A1", present="Call me after class.", present_bn="ক্লাসের পর আমাকে ফোন করো।",
      past="He called his mother.", past_bn="সে তার মাকে ফোন করেছিল।"),
    V("wait", "waited", "waited", "waiting", "waits", "/weɪt/",
      "to stay until something happens", "অপেক্ষা করা",
      cefr="A1", present="Please wait a minute.", present_bn="এক মিনিট অপেক্ষা করুন।",
      past="We waited for the bus.", past_bn="আমরা বাসের জন্য অপেক্ষা করেছিলাম।"),
    V("walk", "walked", "walked", "walking", "walks", "/wɔːk/",
      "to move on foot", "হাঁটা",
      cefr="A1", present="I walk to school.", present_bn="আমি হেঁটে স্কুলে যাই।",
      past="They walked in the park.", past_bn="তারা পার্কে হেঁটেছিল।"),
    V("talk", "talked", "talked", "talking", "talks", "/tɔːk/",
      "to speak with someone", "কথা বলা",
      cefr="A1", present="Let's talk later.", present_bn="পরে কথা বলি।",
      past="She talked about her job.", past_bn="সে তার চাকরি নিয়ে কথা বলেছিল।"),
    V("start", "started", "started", "starting", "starts", "/stɑːt/",
      "to begin", "শুরু করা",
      cefr="A1", present="Class starts at nine.", present_bn="ক্লাস নয়টায় শুরু হয়।",
      past="He started a new course.", past_bn="সে নতুন কোর্স শুরু করেছিল।"),
    V("stop", "stopped", "stopped", "stopping", "stops", "/stɒp/",
      "to not continue", "থামানো / থামা",
      cefr="A1", present="Stop talking, please.", present_bn="অনুগ্রহ করে কথা বলা বন্ধ করুন।",
      past="The rain stopped.", past_bn="বৃষ্টি থেমে গিয়েছিল।",
      gerund_ex="Stop making the same mistake.", gerund_ex_bn="একই ভুল করা বন্ধ করো।"),
    V("play", "played", "played", "playing", "plays", "/pleɪ/",
      "to take part in a game or music", "খেলা / বাজানো",
      cefr="A1", present="They play cricket on Friday.", present_bn="তারা শুক্রবার ক্রিকেট খেলে।",
      past="She played the guitar.", past_bn="সে গিটার বাজিয়েছিল।"),
    V("watch", "watched", "watched", "watching", "watches", "/wɒtʃ/",
      "to look at something for a time", "দেখা (টিভি/খেলা)",
      cefr="A1", present="I watch the news at night.", present_bn="আমি রাতে খবর দেখি।",
      past="We watched a drama.", past_bn="আমরা একটি নাটক দেখেছিলাম।"),
    V("drink", "drank", "drunk", "drinking", "drinks", "/drɪŋk/",
      "to take liquid into the mouth", "পান করা",
      cefr="A1", irregular=True, category="food",
      present="Drink more water.", present_bn="আরও পানি পান করুন।",
      past="He drank tea this morning.", past_bn="সে সকালে চা খেয়েছিল।"),
    V("put", "put", "put", "putting", "puts", "/pʊt/",
      "to place something somewhere", "রাখা / স্থাপন করা",
      cefr="A1", irregular=True,
      present="Put the book on the table.", present_bn="বইটা টেবিলে রাখো।",
      past="She put the keys in her bag.", past_bn="সে চাবি ব্যাগে রেখেছিল।"),
    V("sit", "sat", "sat", "sitting", "sits", "/sɪt/",
      "to rest on a chair", "বসা",
      cefr="A1", irregular=True,
      present="Please sit down.", present_bn="অনুগ্রহ করে বসুন।",
      past="We sat near the window.", past_bn="আমরা জানালার কাছে বসেছিলাম।"),
    V("stand", "stood", "stood", "standing", "stands", "/stænd/",
      "to be on your feet", "দাঁড়ানো",
      cefr="A1", irregular=True,
      present="Stand in a line.", present_bn="সারিতে দাঁড়ান।",
      past="He stood at the door.", past_bn="সে দরজায় দাঁড়িয়ে ছিল।"),
    V("leave", "left", "left", "leaving", "leaves", "/liːv/",
      "to go away from a place", "চলে যাওয়া / ছেড়ে যাওয়া",
      cefr="A1", irregular=True,
      present="I leave home at 8.", present_bn="আমি ৮টায় বাড়ি থেকে বের হই।",
      past="She left early.", past_bn="সে তাড়াতাড়ি চলে গিয়েছিল।"),
    V("send", "sent", "sent", "sending", "sends", "/send/",
      "to make something go to someone", "পাঠানো",
      cefr="A2", irregular=True,
      present="Send me the file.", present_bn="আমাকে ফাইলটা পাঠাও।",
      past="He sent an email.", past_bn="সে একটি ইমেইল পাঠিয়েছিল।"),
    V("pay", "paid", "paid", "paying", "pays", "/peɪ/",
      "to give money for something", "টাকা দেওয়া",
      cefr="A1", irregular=True,
      present="How much do I pay?", present_bn="আমাকে কত দিতে হবে?",
      past="They paid the bill.", past_bn="তারা বিল পরিশোধ করেছিল।"),
    V("forget", "forgot", "forgotten", "forgetting", "forgets", "/fəˈɡet/",
      "to not remember", "ভুলে যাওয়া",
      cefr="A1", irregular=True,
      present="Don't forget your ID.", present_bn="আইডি ভুলো না।",
      past="I forgot her name.", past_bn="আমি তার নাম ভুলে গিয়েছিলাম।"),
    V("remember", "remembered", "remembered", "remembering", "remembers", "/rɪˈmembə/",
      "to keep something in your mind", "মনে রাখা",
      cefr="A1",
      present="I remember that day.", present_bn="আমি সেই দিনটা মনে আছে।",
      past="She remembered the answer.", past_bn="সে উত্তরটা মনে করেছিল।"),
    V("understand", "understood", "understood", "understanding", "understands", "/ˌʌndəˈstænd/",
      "to know the meaning of something", "বুঝতে পারা",
      cefr="A1", irregular=True,
      present="Do you understand?", present_bn="তুমি কি বুঝতে পারছ?",
      past="He understood the problem.", past_bn="সে সমস্যাটা বুঝেছিল।"),
    V("look", "looked", "looked", "looking", "looks", "/lʊk/",
      "to turn your eyes towards something", "তাকানো / দেখা",
      cefr="A1",
      present="Look at the board.", present_bn="বোর্ডের দিকে তাকাও।",
      past="She looked tired.", past_bn="তাকে ক্লান্ত লাগছিল।"),
    V("hear", "heard", "heard", "hearing", "hears", "/hɪə/",
      "to notice sound with your ears", "শোনা",
      cefr="A1", irregular=True,
      present="I hear music.", present_bn="আমি গান শুনতে পাচ্ছি।",
      past="We heard a noise.", past_bn="আমরা একটি শব্দ শুনেছিলাম।"),
    V("lose", "lost", "lost", "losing", "loses", "/luːz/",
      "to not keep; to be defeated", "হারানো / হারা",
      cefr="A2", irregular=True,
      present="Don't lose your ticket.", present_bn="টিকিট হারিও না।",
      past="He lost his phone.", past_bn="সে তার ফোন হারিয়েছিল।"),
    V("win", "won", "won", "winning", "wins", "/wɪn/",
      "to be first in a contest", "জয় করা",
      cefr="A2", irregular=True,
      present="I hope we win.", present_bn="আশা করি আমরা জিতব।",
      past="She won the prize.", past_bn="সে পুরস্কার জিতেছিল।"),
    V("become", "became", "become", "becoming", "becomes", "/bɪˈkʌm/",
      "to start to be something", "হয়ে ওঠা",
      cefr="A2", irregular=True,
      present="It becomes dark early.", present_bn="তাড়াতাড়ি অন্ধকার হয়ে যায়।",
      past="He became a teacher.", past_bn="সে শিক্ষক হয়েছিলেন।"),
    V("mean", "meant", "meant", "meaning", "means", "/miːn/",
      "to have a particular meaning", "মানে হওয়া / বোঝানো",
      cefr="A1", irregular=True,
      present="What does this word mean?", present_bn="এই শব্দের মানে কী?",
      past="I meant to call you.", past_bn="আমি তোমাকে ফোন করতে চেয়েছিলাম।"),
    V("choose", "chose", "chosen", "choosing", "chooses", "/tʃuːz/",
      "to pick one thing from options", "বেছে নেওয়া",
      cefr="A2", irregular=True,
      present="Choose the best answer.", present_bn="সেরা উত্তর বেছে নাও।",
      past="They chose a quiet hotel.", past_bn="তারা শান্ত হোটেল বেছে নিয়েছিল।"),
    V("grow", "grew", "grown", "growing", "grows", "/ɡrəʊ/",
      "to become bigger", "বাড়া / বেড়ে ওঠা",
      cefr="A2", irregular=True, category="nature",
      present="Children grow quickly.", present_bn="শিশুরা দ্রুত বাড়ে।",
      past="The city grew fast.", past_bn="শহর দ্রুত বেড়েছিল।"),
    V("open", "opened", "opened", "opening", "opens", "/ˈəʊpən/",
      "to make something not closed", "খোলা",
      cefr="A1",
      present="Open your books.", present_bn="বই খোলো।",
      past="The shop opened at 10.", past_bn="দোকান ১০টায় খুলেছিল।"),
    V("close", "closed", "closed", "closing", "closes", "/kləʊz/",
      "to shut something", "বন্ধ করা",
      cefr="A1",
      present="Please close the door.", present_bn="দয়া করে দরজা বন্ধ করুন।",
      past="They closed the office early.", past_bn="তারা অফিস তাড়াতাড়ি বন্ধ করেছিল।"),
    V("stay", "stayed", "stayed", "staying", "stays", "/steɪ/",
      "to remain in a place", "থাকা / অবস্থান করা",
      cefr="A1",
      present="Stay here, please.", present_bn="এখানে থাকুন।",
      past="We stayed with relatives.", past_bn="আমরা আত্মীয়দের কাছে ছিলাম।"),
    V("happen", "happened", "happened", "happening", "happens", "/ˈhæpən/",
      "to take place", "ঘটা",
      cefr="A2",
      present="What happens next?", present_bn="এরপর কী হয়?",
      past="The accident happened at night.", past_bn="দুর্ঘটনা রাতে ঘটেছিল।"),
    # IELTS / academic
    V("analyse", "analysed", "analysed", "analysing", "analyses", "/ˈænəlaɪz/",
      "to examine in detail", "বিশ্লেষণ করা",
      cefr="B1", category="ielts",
      present="Students analyse the graph.", present_bn="শিক্ষার্থীরা গ্রাফ বিশ্লেষণ করে।",
      past="The report analysed the data.", past_bn="রিপোর্টটি তথ্য বিশ্লেষণ করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("argue", "argued", "argued", "arguing", "argues", "/ˈɑːɡjuː/",
      "to give reasons for an opinion", "যুক্তি দেওয়া / তর্ক করা",
      cefr="B1", category="ielts",
      present="Some people argue that cities are too crowded.", present_bn="কেউ কেউ যুক্তি দেন শহর খুব ভিড়।",
      past="The essay argued both sides.", past_bn="রচনাটি দুই পক্ষের যুক্তি দিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("demonstrate", "demonstrated", "demonstrated", "demonstrating", "demonstrates", "/ˈdemənstreɪt/",
      "to show clearly with evidence", "প্রমাণ করে দেখানো",
      cefr="B2", category="ielts",
      present="The chart demonstrates a rise in sales.", present_bn="চার্ট বিক্রিতে বৃদ্ধি দেখায়।",
      past="The study demonstrated the benefits.", past_bn="গবেষণা উপকার প্রমাণ করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("illustrate", "illustrated", "illustrated", "illustrating", "illustrates", "/ˈɪləstreɪt/",
      "to make clear with an example", "উদাহরণ দিয়ে বোঝানো",
      cefr="B2", category="ielts",
      present="This example illustrates the problem.", present_bn="এই উদাহরণ সমস্যাটা বোঝায়।",
      past="The teacher illustrated the rule.", past_bn="শিক্ষক নিয়মটা উদাহরণ দিয়ে বুঝিয়েছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("indicate", "indicated", "indicated", "indicating", "indicates", "/ˈɪndɪkeɪt/",
      "to show or point to something", "ইঙ্গিত করা / দেখানো",
      cefr="B1", category="ielts",
      present="The figures indicate a decline.", present_bn="সংখ্যাগুলো হ্রাসের ইঙ্গিত দেয়।",
      past="Results indicated improvement.", past_bn="ফলাফল উন্নতির ইঙ্গিত দিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("suggest", "suggested", "suggested", "suggesting", "suggests", "/səˈdʒest/",
      "to put forward an idea", "প্রস্তাব করা / ইঙ্গিত করা",
      cefr="B1", category="ielts",
      present="I suggest taking a break.", present_bn="আমি বিরতি নেওয়ার পরামর্শ দিই।",
      past="The data suggested a link.", past_bn="তথ্য একটি যোগসূত্রের ইঙ্গিত দিয়েছিল।",
      gerund_ex="I suggest practising every day.", gerund_ex_bn="প্রতিদিন অনুশীলনের পরামর্শ দিই।",
      tags=["verb", "grammar", "ielts"]),
    V("contribute", "contributed", "contributed", "contributing", "contributes", "/kənˈtrɪbjuːt/",
      "to help cause something", "অবদান রাখা",
      cefr="B2", category="ielts",
      present="Exercise contributes to health.", present_bn="ব্যায়াম স্বাস্থ্যে অবদান রাখে।",
      past="Many factors contributed to the change.", past_bn="অনেক কারণ পরিবর্তনে অবদান রেখেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("remain", "remained", "remained", "remaining", "remains", "/rɪˈmeɪn/",
      "to stay the same or stay behind", "অপরিবর্তিত থাকা / থেকে যাওয়া",
      cefr="B1", category="ielts",
      present="Unemployment remains high.", present_bn="বেকারত্ব এখনও বেশি।",
      past="The rate remained stable.", past_bn="হার স্থিতিশীল ছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("compare", "compared", "compared", "comparing", "compares", "/kəmˈpeə/",
      "to look at similarities and differences", "তুলনা করা",
      cefr="B1", category="ielts",
      present="Compare the two graphs.", present_bn="দুই গ্রাফ তুলনা করো।",
      past="The essay compared urban and rural life.", past_bn="রচনা শহর ও গ্রামের জীবন তুলনা করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("emphasise", "emphasised", "emphasised", "emphasising", "emphasises", "/ˈemfəsaɪz/",
      "to give special importance", "জোর দেওয়া",
      cefr="B2", category="ielts",
      present="The author emphasises education.", present_bn="লেখক শিক্ষার উপর জোর দেন।",
      past="The speaker emphasised safety.", past_bn="বক্তা নিরাপত্তায় জোর দিয়েছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("assess", "assessed", "assessed", "assessing", "assesses", "/əˈses/",
      "to judge the quality or amount", "মূল্যায়ন করা",
      cefr="B2", category="education",
      present="Teachers assess students' work.", present_bn="শিক্ষকরা শিক্ষার্থীর কাজ মূল্যায়ন করেন।",
      past="The risk was assessed carefully.", past_bn="ঝুঁকি সাবধানে মূল্যায়ন করা হয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("evaluate", "evaluated", "evaluated", "evaluating", "evaluates", "/ɪˈvæljueɪt/",
      "to judge after careful thought", "মূল্যায়ন করে সিদ্ধান্ত নেওয়া",
      cefr="B2", category="ielts",
      present="Evaluate both arguments.", present_bn="দুই যুক্তি মূল্যায়ন করো।",
      past="The committee evaluated the plan.", past_bn="কমিটি পরিকল্পনা মূল্যায়ন করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("require", "required", "required", "requiring", "requires", "/rɪˈkwaɪə/",
      "to need something as necessary", "প্রয়োজন হওয়া / আবশ্যক করা",
      cefr="B1", category="ielts",
      present="The job requires patience.", present_bn="কাজটিতে ধৈর্য লাগে।",
      past="The form required a signature.", past_bn="ফর্মে স্বাক্ষর লাগত।",
      tags=["verb", "grammar", "ielts"]),
    V("reduce", "reduced", "reduced", "reducing", "reduces", "/rɪˈdjuːs/",
      "to make smaller in amount", "কমানো",
      cefr="B1", category="ielts",
      present="We should reduce plastic use.", present_bn="প্লাস্টিক ব্যবহার কমানো উচিত।",
      past="The government reduced taxes.", past_bn="সরকার কর কমিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("improve", "improved", "improved", "improving", "improves", "/ɪmˈpruːv/",
      "to make or become better", "উন্নতি করা / উন্নত করা",
      cefr="A2", category="education",
      present="Practice improves your English.", present_bn="অনুশীলন ইংরেজি উন্নত করে।",
      past="Her score improved last month.", past_bn="গত মাসে তার স্কোর বেড়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("affect", "affected", "affected", "affecting", "affects", "/əˈfekt/",
      "to have an influence on", "প্রভাব ফেলা",
      cefr="B1", category="ielts",
      present="Pollution affects health.", present_bn="দূষণ স্বাস্থ্যে প্রভাব ফেলে।",
      past="The delay affected the result.", past_bn="বিলম্ব ফলাফলে প্রভাব ফেলেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("imply", "implied", "implied", "implying", "implies", "/ɪmˈplaɪ/",
      "to suggest without saying directly", "ইঙ্গিতে বোঝানো",
      cefr="B2", category="ielts",
      present="The writer implies a warning.", present_bn="লেখক একটি সতর্কবার্তা ইঙ্গিত করেন।",
      past="The article implied bias.", past_bn="প্রবন্ধটি পক্ষপাতের ইঙ্গিত দিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("infer", "inferred", "inferred", "inferring", "infers", "/ɪnˈfɜː/",
      "to reach a conclusion from clues", "অনুমান করা / সিদ্ধান্ত টানা",
      cefr="B2", category="ielts",
      present="Readers infer the meaning from context.", present_bn="পাঠক প্রসঙ্গ থেকে অর্থ অনুমান করে।",
      past="We inferred that demand had fallen.", past_bn="আমরা অনুমান করেছিলাম চাহিদা কমেছে।",
      tags=["verb", "grammar", "ielts"]),
    V("claim", "claimed", "claimed", "claiming", "claims", "/kleɪm/",
      "to say something is true", "দাবি করা",
      cefr="B1", category="ielts",
      present="Some experts claim it is safer.", present_bn="কিছু বিশেষজ্ঞ দাবি করেন এটা নিরাপদ।",
      past="The company claimed success.", past_bn="কোম্পানি সাফল্য দাবি করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("reveal", "revealed", "revealed", "revealing", "reveals", "/rɪˈviːl/",
      "to make something known", "প্রকাশ করা",
      cefr="B2", category="ielts",
      present="The survey reveals public opinion.", present_bn="জরিপ জনমত প্রকাশ করে।",
      past="The study revealed a gap.", past_bn="গবেষণা একটি ফাঁক প্রকাশ করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("describe", "described", "described", "describing", "describes", "/dɪˈskraɪb/",
      "to say what something is like", "বর্ণনা করা",
      cefr="A2", category="ielts",
      present="Describe your hometown.", present_bn="তোমার শহরের বর্ণনা দাও।",
      past="She described the process clearly.", past_bn="সে প্রক্রিয়া স্পষ্ট করে বর্ণনা করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("prefer", "preferred", "preferred", "preferring", "prefers", "/prɪˈfɜː/",
      "to like one thing more than another", "বেশি পছন্দ করা",
      cefr="A2",
      present="I prefer tea to coffee.", present_bn="কফির চেয়ে চা বেশি পছন্দ করি।",
      past="He preferred studying at night.", past_bn="সে রাতে পড়তে বেশি পছন্দ করত।",
      gerund_ex="I prefer studying in the morning.", gerund_ex_bn="সকালে পড়া বেশি পছন্দ করি।",
      tags=["verb", "grammar", "ielts"]),
    V("enjoy", "enjoyed", "enjoyed", "enjoying", "enjoys", "/ɪnˈdʒɔɪ/",
      "to get pleasure from something", "উপভোগ করা",
      cefr="A1",
      present="I enjoy cooking.", present_bn="আমি রান্না উপভোগ করি।",
      past="They enjoyed the trip.", past_bn="তারা ভ্রমণ উপভোগ করেছিল।",
      gerund_ex="She enjoys speaking English.", gerund_ex_bn="সে ইংরেজিতে কথা বলা উপভোগ করে।"),
    V("explain", "explained", "explained", "explaining", "explains", "/ɪkˈspleɪn/",
      "to make something clear", "ব্যাখ্যা করা",
      cefr="A2", category="education",
      present="Can you explain this word?", present_bn="এই শব্দটা ব্যাখ্যা করতে পারবে?",
      past="The teacher explained the rule.", past_bn="শিক্ষক নিয়ম ব্যাখ্যা করেছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("discuss", "discussed", "discussed", "discussing", "discusses", "/dɪˈskʌs/",
      "to talk about a topic in detail", "আলোচনা করা",
      cefr="B1", category="ielts",
      present="We will discuss both views.", present_bn="আমরা দুই মত আলোচনা করব।",
      past="The class discussed climate change.", past_bn="ক্লাস জলবায়ু পরিবর্তন আলোচনা করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("consider", "considered", "considered", "considering", "considers", "/kənˈsɪdə/",
      "to think carefully about", "বিবেচনা করা",
      cefr="B1", category="ielts",
      present="Consider the disadvantages too.", present_bn="অসুবিধাগুলোও বিবেচনা করো।",
      past="She considered studying abroad.", past_bn="সে বিদেশে পড়ার কথা ভেবেছিল।",
      gerund_ex="I am considering changing my plan.", gerund_ex_bn="আমি পরিকল্পনা বদলানোর কথা ভাবছি।",
      tags=["verb", "grammar", "ielts"]),
    V("recommend", "recommended", "recommended", "recommending", "recommends", "/ˌrekəˈmend/",
      "to say something is good to do", "সুপারিশ করা",
      cefr="B1", category="ielts",
      present="I recommend reading newspapers.", present_bn="খবরের কাগজ পড়ার সুপারিশ করি।",
      past="The doctor recommended rest.", past_bn="ডাক্তার বিশ্রামের পরামর্শ দিয়েছিলেন।",
      gerund_ex="I recommend practising aloud.", gerund_ex_bn="জোরে অনুশীলনের সুপারিশ করি।",
      tags=["verb", "grammar", "ielts"]),
    V("expect", "expected", "expected", "expecting", "expects", "/ɪkˈspekt/",
      "to think something will happen", "আশা করা / প্রত্যাশা করা",
      cefr="A2",
      present="I expect a high score.", present_bn="আমি উচ্চ স্কোর আশা করি।",
      past="We expected more visitors.", past_bn="আমরা আরও দর্শনার্থী আশা করেছিলাম।"),
    V("enable", "enabled", "enabled", "enabling", "enables", "/ɪˈneɪbl/",
      "to make something possible", "সম্ভব করা",
      cefr="B2", category="ielts",
      present="Technology enables remote work.", present_bn="প্রযুক্তি দূর থেকে কাজ সম্ভব করে।",
      past="The grant enabled the project.", past_bn="অনুদান প্রকল্প সম্ভব করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("represent", "represented", "represented", "representing", "represents", "/ˌreprɪˈzent/",
      "to stand for; to show", "প্রতিনিধিত্ব করা / নির্দেশ করা",
      cefr="B1", category="ielts",
      present="The blue line represents imports.", present_bn="নীল রেখা আমদানি নির্দেশ করে।",
      past="She represented her school.", past_bn="সে তার স্কুলের প্রতিনিধিত্ব করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("decline", "declined", "declined", "declining", "declines", "/dɪˈklaɪn/",
      "to become smaller or weaker", "কমতে থাকা / প্রত্যাখ্যান করা",
      cefr="B2", category="ielts",
      present="Sales decline in winter.", present_bn="শীতকালে বিক্রি কমে।",
      past="The population declined.", past_bn="জনসংখ্যা কমেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("fluctuate", "fluctuated", "fluctuated", "fluctuating", "fluctuates", "/ˈflʌktʃueɪt/",
      "to rise and fall irregularly", "ওঠানামা করা",
      cefr="B2", category="ielts",
      present="Prices fluctuate each month.", present_bn="প্রতি মাসে দাম ওঠানামা করে।",
      past="The figures fluctuated widely.", past_bn="সংখ্যাগুলো ব্যাপক ওঠানামা করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("outline", "outlined", "outlined", "outlining", "outlines", "/ˈaʊtlaɪn/",
      "to give the main points", "মূল বিষয় তুলে ধরা",
      cefr="B2", category="ielts",
      present="Outline your main ideas first.", present_bn="আগে মূল ধারণাগুলো লিখে নাও।",
      past="The introduction outlined the topic.", past_bn="ভূমিকা বিষয়টি তুলে ধরেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("predict", "predicted", "predicted", "predicting", "predicts", "/prɪˈdɪkt/",
      "to say what will happen", "ভবিষ্যদ্বাণী করা",
      cefr="B1", category="ielts",
      present="Experts predict higher demand.", present_bn="বিশেষজ্ঞরা বেশি চাহিদার পূর্বাভাস দেন।",
      past="The model predicted rainfall.", past_bn="মডেল বৃষ্টির পূর্বাভাস দিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("identify", "identified", "identified", "identifying", "identifies", "/aɪˈdentɪfaɪ/",
      "to recognise and name", "শনাক্ত করা",
      cefr="B1", category="ielts",
      present="Identify the main idea.", present_bn="মূল ভাব শনাক্ত করো।",
      past="Researchers identified the cause.", past_bn="গবেষকরা কারণ শনাক্ত করেছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("conclude", "concluded", "concluded", "concluding", "concludes", "/kənˈkluːd/",
      "to decide after evidence; to finish", "সিদ্ধান্তে পৌঁছানো / শেষ করা",
      cefr="B1", category="ielts",
      present="We can conclude that practice works.", present_bn="সিদ্ধান্তে পৌঁছানো যায় অনুশীলন কাজ করে।",
      past="The author concluded with a warning.", past_bn="লেখক সতর্কবার্তা দিয়ে শেষ করেছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("mention", "mentioned", "mentioned", "mentioning", "mentions", "/ˈmenʃn/",
      "to say something briefly", "উল্লেখ করা",
      cefr="A2", category="ielts",
      present="Please mention one example.", present_bn="একটি উদাহরণ উল্লেখ করুন।",
      past="He mentioned his hometown.", past_bn="সে তার শহরের কথা উল্লেখ করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("notice", "noticed", "noticed", "noticing", "notices", "/ˈnəʊtɪs/",
      "to become aware of something", "লক্ষ্য করা",
      cefr="A2",
      present="Did you notice the change?", present_bn="পরিবর্তন লক্ষ্য করেছ?",
      past="I noticed a spelling mistake.", past_bn="আমি একটি বানান ভুল লক্ষ্য করেছিলাম।"),
    V("spend", "spent", "spent", "spending", "spends", "/spend/",
      "to use time or money", "খরচ করা / কাটানো",
      cefr="A1", irregular=True,
      present="I spend two hours studying.", present_bn="আমি দুই ঘণ্টা পড়াশোনা করি।",
      past="She spent the weekend at home.", past_bn="সে সপ্তাহান্তে বাড়িতে কাটিয়েছিল।"),
    V("visit", "visited", "visited", "visiting", "visits", "/ˈvɪzɪt/",
      "to go to a place for a short time", "ঘুরতে যাওয়া / সাক্ষাৎ করা",
      cefr="A1", category="travel",
      present="We visit our grandparents every Eid.", present_bn="প্রতি ঈদে আমরা দাদা-দাদির কাছে যাই।",
      past="They visited Cox's Bazar.", past_bn="তারা কক্সবাজার ঘুরতে গিয়েছিল।"),
    V("agree", "agreed", "agreed", "agreeing", "agrees", "/əˈɡriː/",
      "to have the same opinion", "একমত হওয়া",
      cefr="A2",
      present="I agree with you.", present_bn="আমি তোমার সঙ্গে একমত।",
      past="They agreed on a plan.", past_bn="তারা একটি পরিকল্পনায় একমত হয়েছিল।"),
    V("manage", "managed", "managed", "managing", "manages", "/ˈmænɪdʒ/",
      "to succeed in doing; to be in charge", "সফলভাবে করা / পরিচালনা করা",
      cefr="B1", category="office",
      present="She manages a small team.", present_bn="সে একটি ছোট টিম পরিচালনা করে।",
      past="He managed to finish on time.", past_bn="সে সময়মতো শেষ করতে পেরেছিল।"),
    V("commute", "commuted", "commuted", "commuting", "commutes", "/kəˈmjuːt/",
      "to travel regularly to work", "নিয়মিত যাতায়াত করা",
      cefr="B1", category="office",
      present="I commute by bus.", present_bn="আমি বাসে যাতায়াত করি।",
      past="They commuted two hours a day.", past_bn="তারা দিনে দুই ঘণ্টা যাতায়াত করত।"),
    V("postpone", "postponed", "postponed", "postponing", "postpones", "/pəˈspəʊn/",
      "to delay until later", "মুলতবি করা",
      cefr="B1",
      present="Let's postpone the meeting.", present_bn="মিটিং পিছিয়ে দিই।",
      past="The exam was postponed.", past_bn="পরীক্ষা মুলতবি হয়েছিল।"),
    V("negotiate", "negotiated", "negotiated", "negotiating", "negotiates", "/nɪˈɡəʊʃieɪt/",
      "to try to reach an agreement", "আলোচনা করে সমঝোতা করা",
      cefr="B2", category="office",
      present="They negotiate the contract.", present_bn="তারা চুক্তি নিয়ে আলোচনা করে।",
      past="We negotiated a better price.", past_bn="আমরা ভালো দামে সমঝোতা করেছিলাম।"),
    V("complain", "complained", "complained", "complaining", "complains", "/kəmˈpleɪn/",
      "to say you are unhappy", "অভিযোগ করা",
      cefr="B1",
      present="Customers complain about delays.", present_bn="গ্রাহকরা বিলম্ব নিয়ে অভিযোগ করে।",
      past="He complained to the manager.", past_bn="সে ম্যানেজারের কাছে অভিযোগ করেছিল।"),
    V("apologise", "apologised", "apologised", "apologising", "apologises", "/əˈpɒlədʒaɪz/",
      "to say you are sorry", "ক্ষমা চাওয়া",
      cefr="B1",
      present="I apologise for the mistake.", present_bn="ভুলের জন্য ক্ষমা চাই।",
      past="She apologised immediately.", past_bn="সে সঙ্গে সঙ্গে ক্ষমা চেয়েছিল।"),
    V("persuade", "persuaded", "persuaded", "persuading", "persuades", "/pəˈsweɪd/",
      "to make someone agree by argument", "প্ররোচিত করা / রাজি করানো",
      cefr="B2",
      present="Can you persuade him to join?", present_bn="তাকে যোগ দিতে রাজি করাতে পারবে?",
      past="They persuaded the committee.", past_bn="তারা কমিটিকে রাজি করিয়েছিল।"),
    V("refuse", "refused", "refused", "refusing", "refuses", "/rɪˈfjuːz/",
      "to say no to something", "প্রত্যাখ্যান করা",
      cefr="B1",
      present="She refuses to give up.", present_bn="সে হার মানতে রাজি নয়।",
      past="He refused the offer.", past_bn="সে প্রস্তাব ফিরিয়ে দিয়েছিল।"),
    V("admit", "admitted", "admitted", "admitting", "admits", "/ədˈmɪt/",
      "to accept that something is true", "স্বীকার করা",
      cefr="B1",
      present="I admit I was wrong.", present_bn="আমি ভুল স্বীকার করি।",
      past="They admitted the error.", past_bn="তারা ভুল স্বীকার করেছিল।",
      gerund_ex="He admitted making a mistake.", gerund_ex_bn="সে ভুল করার কথা স্বীকার করেছিল।"),
    V("arrange", "arranged", "arranged", "arranging", "arranges", "/əˈreɪndʒ/",
      "to plan or organise", "আয়োজন করা / ঠিক করা",
      cefr="B1",
      present="I'll arrange an interview.", present_bn="আমি একটি ইন্টারভিউ ঠিক করব।",
      past="We arranged a meeting.", past_bn="আমরা একটি মিটিং আয়োজন করেছিলাম।"),
    V("confirm", "confirmed", "confirmed", "confirming", "confirms", "/kənˈfɜːm/",
      "to say something is definitely true", "নিশ্চিত করা",
      cefr="B1",
      present="Please confirm your booking.", present_bn="বুকিং নিশ্চিত করুন।",
      past="The result confirmed the theory.", past_bn="ফলাফল তত্ত্বটি নিশ্চিত করেছিল।"),
    V("encourage", "encouraged", "encouraged", "encouraging", "encourages", "/ɪnˈkʌrɪdʒ/",
      "to give someone confidence or support", "উৎসাহ দেওয়া",
      cefr="B1", category="education",
      present="Teachers encourage questions.", present_bn="শিক্ষকরা প্রশ্ন করতে উৎসাহ দেন।",
      past="Her parents encouraged her.", past_bn="তার বাবা-মা তাকে উৎসাহ দিয়েছিলেন।"),
    V("maintain", "maintained", "maintained", "maintaining", "maintains", "/meɪnˈteɪn/",
      "to keep at the same level", "বজায় রাখা",
      cefr="B2", category="ielts",
      present="It is hard to maintain focus.", present_bn="মনোযোগ বজায় রাখা কঠিন।",
      past="The city maintained the parks.", past_bn="শহর পার্কগুলো রক্ষণাবেক্ষণ করেছিল।"),
    V("participate", "participated", "participated", "participating", "participates", "/pɑːˈtɪsɪpeɪt/",
      "to take part in", "অংশগ্রহণ করা",
      cefr="B1", category="education",
      present="Students participate in debates.", present_bn="শিক্ষার্থীরা বিতর্কে অংশ নেয়।",
      past="She participated in the survey.", past_bn="সে জরিপে অংশ নিয়েছিল।"),
    V("prevent", "prevented", "prevented", "preventing", "prevents", "/prɪˈvent/",
      "to stop something from happening", "প্রতিরোধ করা",
      cefr="B1", category="ielts",
      present="Laws prevent discrimination.", present_bn="আইন বৈষম্য প্রতিরোধ করে।",
      past="The vaccine prevented infection.", past_bn="টিকা সংক্রমণ প্রতিরোধ করেছিল।"),
    V("provide", "provided", "provided", "providing", "provides", "/prəˈvaɪd/",
      "to give something needed", "সরবরাহ করা",
      cefr="B1", category="ielts",
      present="The course provides feedback.", present_bn="কোর্সটি ফিডব্যাক দেয়।",
      past="The hotel provided breakfast.", past_bn="হোটেল সকালের নাস্তা দিয়েছিল।"),
    V("realise", "realised", "realised", "realising", "realises", "/ˈrɪəlaɪz/",
      "to become aware of", "উপলব্ধি করা",
      cefr="B1",
      present="I realise the risk now.", present_bn="এখন ঝুঁকি উপলব্ধি করছি।",
      past="She realised her mistake.", past_bn="সে তার ভুল বুঝতে পেরেছিল।"),
    V("receive", "received", "received", "receiving", "receives", "/rɪˈsiːv/",
      "to get something given to you", "গ্রহণ করা / পাওয়া",
      cefr="B1",
      present="Did you receive the email?", present_bn="ইমেইল পেয়েছ?",
      past="He received an award.", past_bn="সে একটি পুরস্কার পেয়েছিল।"),
    V("rely", "relied", "relied", "relying", "relies", "/rɪˈlaɪ/",
      "to depend on", "নির্ভর করা",
      cefr="B2",
      present="Many cities rely on tourism.", present_bn="অনেক শহর পর্যটনের উপর নির্ভর করে।",
      past="We relied on public transport.", past_bn="আমরা গণপরিবহনের উপর নির্ভর করেছিলাম।"),
    V("request", "requested", "requested", "requesting", "requests", "/rɪˈkwest/",
      "to ask for something politely", "অনুরোধ করা",
      cefr="B1", category="office",
      present="I request extra time.", present_bn="আমি অতিরিক্ত সময় চাই।",
      past="They requested a refund.", past_bn="তারা রিফান্ড চেয়েছিল।"),
    V("respond", "responded", "responded", "responding", "responds", "/rɪˈspɒnd/",
      "to reply or react", "সাড়া দেওয়া / জবাব দেওয়া",
      cefr="B1",
      present="Please respond by Friday.", present_bn="শুক্রবারের মধ্যে জবাব দিন।",
      past="The government responded quickly.", past_bn="সরকার দ্রুত সাড়া দিয়েছিল।"),
    V("review", "reviewed", "reviewed", "reviewing", "reviews", "/rɪˈvjuː/",
      "to examine again", "পুনর্বিবেচনা করা / রিভিউ করা",
      cefr="B1", category="education",
      present="Review your essay before submitting.", present_bn="জমা দেওয়ার আগে রচনা আবার দেখো।",
      past="The panel reviewed the applications.", past_bn="প্যানেল আবেদনগুলো পর্যালোচনা করেছিল।"),
    V("succeed", "succeeded", "succeeded", "succeeding", "succeeds", "/səkˈsiːd/",
      "to achieve what you wanted", "সফল হওয়া",
      cefr="B1",
      present="Hard work helps you succeed.", present_bn="কঠোর পরিশ্রম সফল হতে সাহায্য করে।",
      past="She succeeded in the interview.", past_bn="সে ইন্টারভিউতে সফল হয়েছিল।"),
    V("support", "supported", "supported", "supporting", "supports", "/səˈpɔːt/",
      "to help or agree with", "সমর্থন করা",
      cefr="B1", category="ielts",
      present="The evidence supports the claim.", present_bn="প্রমাণ দাবিটি সমর্থন করে।",
      past="Parents supported the decision.", past_bn="বাবা-মা সিদ্ধান্ত সমর্থন করেছিলেন।"),
    V("handle", "handled", "handled", "handling", "handles", "/ˈhændl/",
      "to deal with a situation", "সামলানো / মোকাবিলা করা",
      cefr="B1", category="office",
      present="She handles customer complaints.", present_bn="সে গ্রাহকের অভিযোগ সামলায়।",
      past="He handled the crisis well.", past_bn="সে সংকট ভালোভাবে সামলেছিল।"),
    V("involve", "involved", "involved", "involving", "involves", "/ɪnˈvɒlv/",
      "to include as a necessary part", "জড়িত করা / অন্তর্ভুক্ত করা",
      cefr="B1", category="ielts",
      present="The job involves travel.", present_bn="কাজটিতে ভ্রমণ জড়িত।",
      past="The study involved 200 people.", past_bn="গবেষণায় ২০০ জন অংশ নিয়েছিল।"),
    V("insist", "insisted", "insisted", "insisting", "insists", "/ɪnˈsɪst/",
      "to say firmly that something must happen", "জেদ করা / জোর দেওয়া",
      cefr="B2",
      present="They insist on quality.", present_bn="তারা মানের উপর জোর দেয়।",
      past="She insisted on paying.", past_bn="সে বিল দেওয়ার জেদ করেছিল।"),
    V("arise", "arose", "arisen", "arising", "arises", "/əˈraɪz/",
      "to happen or appear", "উদ্ভূত হওয়া",
      cefr="B2", irregular=True, category="ielts",
      present="Problems arise without planning.", present_bn="পরিকল্পনা ছাড়া সমস্যা দেখা দেয়।",
      past="A dispute arose last year.", past_bn="গত বছর বিরোধ দেখা দিয়েছিল।"),
    V("seek", "sought", "sought", "seeking", "seeks", "/siːk/",
      "to try to find or obtain", "খোঁজা / চাওয়া",
      cefr="B2", irregular=True, category="ielts",
      present="Many graduates seek overseas jobs.", present_bn="অনেক গ্র্যাজুয়েট বিদেশে চাকরি খোঁজে।",
      past="They sought legal advice.", past_bn="তারা আইনি পরামর্শ চেয়েছিল।"),
    V("undergo", "underwent", "undergone", "undergoing", "undergoes", "/ˌʌndəˈɡəʊ/",
      "to experience something, often difficult", "ভোগ করা / অতিক্রম করা",
      cefr="B2", irregular=True, category="ielts",
      present="The city is undergoing change.", present_bn="শহর পরিবর্তনের মধ্য দিয়ে যাচ্ছে।",
      past="He underwent surgery.", past_bn="তার অস্ত্রোপচার হয়েছিল।"),
    V("overcome", "overcame", "overcome", "overcoming", "overcomes", "/ˌəʊvəˈkʌm/",
      "to succeed in dealing with a problem", "জয় করা / কাটিয়ে ওঠা",
      cefr="B2", irregular=True,
      present="Learners overcome anxiety with practice.", present_bn="অনুশীলনে শিক্ষার্থীরা উদ্বেগ কাটায়।",
      past="She overcame many obstacles.", past_bn="সে অনেক বাধা কাটিয়ে উঠেছিল।"),
    V("withdraw", "withdrew", "withdrawn", "withdrawing", "withdraws", "/wɪðˈdrɔː/",
      "to take back or pull out", "প্রত্যাহার করা",
      cefr="B2", irregular=True,
      present="You can withdraw money at the ATM.", present_bn="এটিএম থেকে টাকা তোলা যায়।",
      past="The company withdrew the product.", past_bn="কোম্পানি পণ্য প্রত্যাহার করেছিল।"),
    V("undertake", "undertook", "undertaken", "undertaking", "undertakes", "/ˌʌndəˈteɪk/",
      "to start a task or responsibility", "দায়িত্ব নেওয়া / শুরু করা",
      cefr="B2", irregular=True, category="ielts",
      present="Researchers undertake long studies.", present_bn="গবেষকরা দীর্ঘ গবেষণা করেন।",
      past="The team undertook a review.", past_bn="টিম একটি পর্যালোচনা শুরু করেছিল।"),
    V("lead", "led", "led", "leading", "leads", "/liːd/",
      "to be in charge; to cause", "নেতৃত্ব দেওয়া / ঘটানো",
      cefr="B1", irregular=True, category="ielts",
      present="Poor diet leads to illness.", present_bn="খারাপ খাবার অসুখ ঘটায়।",
      past="She led the project.", past_bn="সে প্রকল্পের নেতৃত্ব দিয়েছিল।"),
    V("rise", "rose", "risen", "rising", "rises", "/raɪz/",
      "to go up", "ওপরে ওঠা / বৃদ্ধি পাওয়া",
      cefr="B1", irregular=True, category="ielts",
      present="Prices rise every year.", present_bn="প্রতি বছর দাম বাড়ে।",
      past="Unemployment rose sharply.", past_bn="বেকারত্ব তীব্রভাবে বেড়েছিল।"),
    V("spread", "spread", "spread", "spreading", "spreads", "/spred/",
      "to move across a wider area", "ছড়িয়ে পড়া",
      cefr="B1", irregular=True, category="ielts",
      present="Information spreads quickly online.", present_bn="অনলাইনে তথ্য দ্রুত ছড়ায়।",
      past="The news spread in hours.", past_bn="কয়েক ঘণ্টায় খবর ছড়িয়ে পড়েছিল।"),
    V("deal", "dealt", "dealt", "dealing", "deals", "/diːl/",
      "to handle a problem or topic", "মোকাবিলা করা / লেনদেন করা",
      cefr="B1", irregular=True,
      present="The essay deals with climate change.", present_bn="রচনা জলবায়ু পরিবর্তন নিয়ে।",
      past="The staff dealt with complaints.", past_bn="কর্মীরা অভিযোগ সামলেছিল।"),
]

LISTS = [
    {
        "id": "vf-daily-conversation",
        "title": "Everyday Intermediate Verbs",
        "title_bn": "দৈনন্দিন ইন্টারমিডিয়েট ক্রিয়া",
        "description": "B1+ verbs for natural conversation at work, study and daily life.",
        "description_bn": "কাজ, পড়া ও দৈনন্দিন কথার B1+ verb।",
        "cefr": "B1–B2",
        "word_ids": [
            "verb:manage", "verb:commute", "verb:postpone", "verb:complain", "verb:apologise",
            "verb:refuse", "verb:admit", "verb:arrange", "verb:confirm", "verb:encourage",
            "verb:participate", "verb:prevent", "verb:provide", "verb:realise", "verb:receive",
            "verb:request", "verb:respond", "verb:review", "verb:succeed", "verb:support",
            "verb:handle", "verb:involve", "verb:discuss", "verb:consider", "verb:recommend",
            "verb:suggest", "verb:accept", "verb:avoid", "verb:achieve", "verb:require",
        ],
    },
    {
        "id": "vf-irregular-core",
        "title": "Irregular Verbs · Intermediate",
        "title_bn": "অনিয়মিত ক্রিয়া · ইন্টারমিডিয়েট",
        "description": "B1+ irregular forms used in essays and speech.",
        "description_bn": "রচনা ও কথার B1+ irregular verb।",
        "cefr": "B1–C1",
        "word_ids": [
            "verb:arise", "verb:seek", "verb:undergo", "verb:overcome", "verb:withdraw",
            "verb:undertake", "verb:lead", "verb:rise", "verb:spread", "verb:deal",
        ],
    },
    {
        "id": "vf-ielts-speaking",
        "title": "IELTS Speaking Verbs",
        "title_bn": "IELTS স্পিকিং ক্রিয়া",
        "description": "B1+ verbs for Part 2–3 answers (unofficial).",
        "description_bn": "Part 2–3 উত্তরের B1+ verb (অনঅফিসিয়াল)।",
        "cefr": "B1–C1",
        "word_ids": [
            "verb:discuss", "verb:consider", "verb:recommend", "verb:suggest", "verb:accept",
            "verb:avoid", "verb:achieve", "verb:require", "verb:compare", "verb:identify",
            "verb:conclude", "verb:contribute", "verb:claim", "verb:argue", "verb:assess",
            "verb:evaluate", "verb:emphasise", "verb:demonstrate", "verb:illustrate", "verb:indicate",
            "verb:enable", "verb:represent", "verb:predict", "verb:outline", "verb:imply",
            "verb:maintain", "verb:support", "verb:involve", "verb:persuade", "verb:participate",
        ],
    },
    {
        "id": "vf-ielts-writing",
        "title": "IELTS Writing Verbs",
        "title_bn": "IELTS রাইটিং ক্রিয়া",
        "description": "Task 1–2 academic verbs: graphs, essays (unofficial).",
        "description_bn": "টাস্ক ১–২ গ্রাফ ও রচনার academic verb (অনঅফিসিয়াল)।",
        "cefr": "B1–C1",
        "word_ids": [
            "verb:decline", "verb:remain", "verb:fluctuate", "verb:represent",
            "verb:indicate", "verb:illustrate", "verb:demonstrate", "verb:compare", "verb:outline",
            "verb:analyse", "verb:argue", "verb:emphasise", "verb:assess", "verb:evaluate",
            "verb:suggest", "verb:claim", "verb:conclude", "verb:contribute", "verb:require",
            "verb:reduce", "verb:affect", "verb:enable", "verb:predict",
            "verb:avoid", "verb:achieve", "verb:rise", "verb:lead", "verb:spread",
            "verb:maintain", "verb:provide",
        ],
    },
    {
        "id": "vf-ielts-reading",
        "title": "IELTS Reading Verbs",
        "title_bn": "IELTS রিডিং ক্রিয়া",
        "description": "Passage verbs for TFNG and matching headings (unofficial).",
        "description_bn": "প্যাসেজের TFNG ও heading মিলানোর verb (অনঅফিসিয়াল)।",
        "cefr": "B1–C1",
        "word_ids": [
            "verb:imply", "verb:infer", "verb:claim", "verb:reveal", "verb:indicate",
            "verb:suggest", "verb:demonstrate", "verb:identify", "verb:conclude", "verb:assess",
            "verb:evaluate", "verb:analyse", "verb:compare", "verb:emphasise", "verb:illustrate",
            "verb:argue", "verb:consider", "verb:require", "verb:affect", "verb:contribute",
            "verb:remain", "verb:enable", "verb:represent", "verb:outline", "verb:predict",
            "verb:undergo", "verb:seek", "verb:arise", "verb:undertake", "verb:support",
        ],
    },
    {
        "id": "vf-regular-starter",
        "title": "Regular Verbs · Intermediate",
        "title_bn": "নিয়মিত ক্রিয়া · ইন্টারমিডিয়েট",
        "description": "B1+ regular -ed verbs for precise speaking and writing.",
        "description_bn": "কথা ও লেখার B1+ নিয়মিত verb।",
        "cefr": "B1–B2",
        "word_ids": [
            "verb:accept", "verb:avoid", "verb:discuss", "verb:consider", "verb:recommend",
            "verb:suggest", "verb:manage", "verb:arrange", "verb:confirm", "verb:encourage",
            "verb:participate", "verb:prevent", "verb:provide", "verb:realise", "verb:receive",
            "verb:request", "verb:respond", "verb:review", "verb:succeed", "verb:support",
            "verb:handle", "verb:involve", "verb:complain", "verb:apologise", "verb:refuse",
            "verb:admit", "verb:postpone", "verb:negotiate", "verb:maintain", "verb:persuade",
        ],
    },
]


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    bank = load_json(VERB_DATA)
    by_id = {v["id"]: i for i, v in enumerate(bank)}
    added = 0
    updated = 0
    for v in NEW_VERBS:
        if v["id"] in by_id:
            bank[by_id[v["id"]]] = v
            updated += 1
        else:
            bank.append(v)
            by_id[v["id"]] = len(bank) - 1
            added += 1
    save_json(VERB_DATA, bank)

    meta = load_json(VLISTS)
    lists = meta.get("lists") or []
    by_list = {L.get("id"): i for i, L in enumerate(lists)}

    master_ids = [v["id"] for v in bank if keep_word(v)]
    lists_to_write = []
    for entry in LISTS:
        item = dict(entry)
        item["word_ids"] = [
            wid for wid in entry["word_ids"] if wid in by_id and keep_word(bank[by_id[wid]])
        ]
        item["cefr"] = list_cefr_label(item.get("cefr"))
        lists_to_write.append(item)
    lists_to_write.append(
        {
            "id": "verb-forms-master",
            "title": "Verb Forms Master List",
            "title_bn": "ক্রিয়া রূপ মাস্টার লিস্ট",
            "description": "B1+ verb forms with V1–V5, gerund and participle usage.",
            "description_bn": "B1+ verb-এর V1–V5 + gerund ও participle ব্যবহার।",
            "cefr": "B1–C1",
            "word_ids": master_ids,
        }
    )
    for entry in lists_to_write:
        if entry["id"] in by_list:
            lists[by_list[entry["id"]]] = entry
        else:
            lists.append(entry)
            by_list[entry["id"]] = len(lists) - 1
    meta["lists"] = lists
    save_json(VLISTS, meta)

    print(f"verb-forms.json: {len(bank)} total (+{added} new, {updated} updated)")
    print("lists:", ", ".join(e["id"] for e in lists_to_write))


if __name__ == "__main__":
    main()
