# -*- coding: utf-8 -*-
"""Add extra verbs + curated verb-form study lists (daily, IELTS skills)."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERB_DATA = ROOT / "data" / "verb-forms.json"
VLISTS = ROOT / "data" / "vocabulary-lists.json"


def slug(w: str) -> str:
    return "verb:" + re.sub(r"[^a-z0-9]+", "-", w.strip().lower()).strip("-")


def V(
    v1: str,
    v2: str,
    v3: str,
    v4: str,
    v5: str,
    phonetic: str,
    meaning_en: str,
    meaning_bn: str,
    *,
    cefr: str = "A2",
    category: str = "daily",
    irregular: bool = False,
    present: str = "",
    present_bn: str = "",
    past: str = "",
    past_bn: str = "",
    perfect: str = "",
    perfect_bn: str = "",
    continuous: str = "",
    continuous_bn: str = "",
    gerund_ex: str = "",
    gerund_ex_bn: str = "",
    part_ex: str = "",
    part_ex_bn: str = "",
    tags: list[str] | None = None,
) -> dict:
    return {
        "id": slug(v1),
        "v1": v1,
        "v2": v2,
        "v3": v3,
        "v4": v4,
        "v5": v5,
        "phonetic": phonetic,
        "meaning_en": meaning_en,
        "meaning_bn": meaning_bn,
        "cefr": cefr,
        "category": category,
        "irregular": irregular,
        "examples": {
            "present": present,
            "present_bn": present_bn,
            "past": past,
            "past_bn": past_bn,
            "perfect": perfect or f"I have {v3} this before.",
            "perfect_bn": perfect_bn or "আমি আগে এটা করেছি।",
            "continuous": continuous or f"She is {v4} now.",
            "continuous_bn": continuous_bn or "সে এখন এটা করছে।",
        },
        "gerund_use": f"Gerund ({v4}) — as subject or after enjoy/avoid/keep",
        "gerund_example": gerund_ex or f"{v4.capitalize()} every day helps you improve.",
        "gerund_example_bn": gerund_ex_bn or "প্রতিদিন করলে উন্নতি হয়।",
        "participle_use": f"Past participle ({v3}) — perfect tenses and passive",
        "participle_example": part_ex or f"The work has been {v3}.",
        "participle_example_bn": part_ex_bn or "কাজটি হয়ে গেছে।",
        "tags": tags or ["verb", "grammar"],
    }


NEW_VERBS = [
    V("ask", "asked", "asked", "asking", "asks", "/ɑːsk/",
      "to request information or help", "জিজ্ঞাসা করা / চাওয়া",
      cefr="A1", present="Can I ask a question?", present_bn="আমি কি একটা প্রশ্ন করতে পারি?",
      past="She asked for directions.", past_bn="সে পথ জিজ্ঞেস করেছিল।",
      gerund_ex="Asking questions helps you learn.", gerund_ex_bn="প্রশ্ন করলে শেখা সহজ হয়।"),
    V("want", "wanted", "wanted", "wanting", "wants", "/wɒnt/",
      "to wish for something", "চাওয়া",
      cefr="A1", present="I want a glass of water.", present_bn="আমি এক গ্লাস পানি চাই।",
      past="He wanted to go home.", past_bn="সে বাড়ি যেতে চেয়েছিল।"),
    V("need", "needed", "needed", "needing", "needs", "/niːd/",
      "to require something", "প্রয়োজন হওয়া",
      cefr="A1", present="You need more practice.", present_bn="তোমার আরও অনুশীলন দরকার।",
      past="We needed extra time.", past_bn="আমাদের অতিরিক্ত সময় দরকার হয়েছিল।"),
    V("like", "liked", "liked", "liking", "likes", "/laɪk/",
      "to enjoy or find pleasant", "পছন্দ করা",
      cefr="A1", present="I like spicy food.", present_bn="আমি ঝাল খাবার পছন্দ করি।",
      past="She liked the movie.", past_bn="সে সিনেমাটা পছন্দ করেছিল।",
      gerund_ex="I like reading before bed.", gerund_ex_bn="ঘুমানোর আগে পড়তে পছন্দ করি।"),
    V("live", "lived", "lived", "living", "lives", "/lɪv/",
      "to stay in a place; to be alive", "বাস করা / বেঁচে থাকা",
      cefr="A1", present="They live in Dhaka.", present_bn="তারা ঢাকায় থাকেন।",
      past="I lived near the river.", past_bn="আমি নদীর কাছে থাকতাম।"),
    V("use", "used", "used", "using", "uses", "/juːz/",
      "to do something with a tool or method", "ব্যবহার করা",
      cefr="A1", present="We use English at work.", present_bn="কাজে আমরা ইংরেজি ব্যবহার করি।",
      past="She used a dictionary.", past_bn="সে ডিকশনারি ব্যবহার করেছিল।"),
    V("call", "called", "called", "calling", "calls", "/kɔːl/",
      "to phone someone; to name", "ফোন করা / ডাকা",
      cefr="A1", present="Call me after class.", present_bn="ক্লাসের পর আমাকে ফোন করো।",
      past="He called his mother.", past_bn="সে তার মাকে ফোন করেছিল।"),
    V("wait", "waited", "waited", "waiting", "waits", "/weɪt/",
      "to stay until something happens", "অপেক্ষা করা",
      cefr="A1", present="Please wait a minute.", present_bn="এক মিনিট অপেক্ষা করুন।",
      past="We waited for the bus.", past_bn="আমরা বাসের জন্য অপেক্ষা করেছিলাম।"),
    V("walk", "walked", "walked", "walking", "walks", "/wɔːk/",
      "to move on foot", "হাঁটা",
      cefr="A1", present="I walk to school.", present_bn="আমি হেঁটে স্কুলে যাই।",
      past="They walked in the park.", past_bn="তারা পার্কে হেঁটেছিল।"),
    V("talk", "talked", "talked", "talking", "talks", "/tɔːk/",
      "to speak with someone", "কথা বলা",
      cefr="A1", present="Let's talk later.", present_bn="পরে কথা বলি।",
      past="She talked about her job.", past_bn="সে তার চাকরি নিয়ে কথা বলেছিল।"),
    V("start", "started", "started", "starting", "starts", "/stɑːt/",
      "to begin", "শুরু করা",
      cefr="A1", present="Class starts at nine.", present_bn="ক্লাস নয়টায় শুরু হয়।",
      past="He started a new course.", past_bn="সে নতুন কোর্স শুরু করেছিল।"),
    V("stop", "stopped", "stopped", "stopping", "stops", "/stɒp/",
      "to not continue", "থামানো / থামা",
      cefr="A1", present="Stop talking, please.", present_bn="অনুগ্রহ করে কথা বলা বন্ধ করুন।",
      past="The rain stopped.", past_bn="বৃষ্টি থেমে গিয়েছিল।",
      gerund_ex="Stop making the same mistake.", gerund_ex_bn="একই ভুল করা বন্ধ করো।"),
    V("play", "played", "played", "playing", "plays", "/pleɪ/",
      "to take part in a game or music", "খেলা / বাজানো",
      cefr="A1", present="They play cricket on Friday.", present_bn="তারা শুক্রবার ক্রিকেট খেলে।",
      past="She played the guitar.", past_bn="সে গিটার বাজিয়েছিল।"),
    V("watch", "watched", "watched", "watching", "watches", "/wɒtʃ/",
      "to look at something for a time", "দেখা (টিভি/খেলা)",
      cefr="A1", present="I watch the news at night.", present_bn="আমি রাতে খবর দেখি।",
      past="We watched a drama.", past_bn="আমরা একটি নাটক দেখেছিলাম।"),
    V("drink", "drank", "drunk", "drinking", "drinks", "/drɪŋk/",
      "to take liquid into the mouth", "পান করা",
      cefr="A1", irregular=True, category="food",
      present="Drink more water.", present_bn="আরও পানি পান করুন।",
      past="He drank tea this morning.", past_bn="সে সকালে চা খেয়েছিল।"),
    V("put", "put", "put", "putting", "puts", "/pʊt/",
      "to place something somewhere", "রাখা / স্থাপন করা",
      cefr="A1", irregular=True,
      present="Put the book on the table.", present_bn="বইটা টেবিলে রাখো।",
      past="She put the keys in her bag.", past_bn="সে চাবি ব্যাগে রেখেছিল।"),
    V("sit", "sat", "sat", "sitting", "sits", "/sɪt/",
      "to rest on a chair", "বসা",
      cefr="A1", irregular=True,
      present="Please sit down.", present_bn="অনুগ্রহ করে বসুন।",
      past="We sat near the window.", past_bn="আমরা জানালার কাছে বসেছিলাম।"),
    V("stand", "stood", "stood", "standing", "stands", "/stænd/",
      "to be on your feet", "দাঁড়ানো",
      cefr="A1", irregular=True,
      present="Stand in a line.", present_bn="সারিতে দাঁড়ান।",
      past="He stood at the door.", past_bn="সে দরজায় দাঁড়িয়ে ছিল।"),
    V("leave", "left", "left", "leaving", "leaves", "/liːv/",
      "to go away from a place", "চলে যাওয়া / ছেড়ে যাওয়া",
      cefr="A1", irregular=True,
      present="I leave home at 8.", present_bn="আমি ৮টায় বাড়ি থেকে বের হই।",
      past="She left early.", past_bn="সে তাড়াতাড়ি চলে গিয়েছিল।"),
    V("send", "sent", "sent", "sending", "sends", "/send/",
      "to make something go to someone", "পাঠানো",
      cefr="A2", irregular=True,
      present="Send me the file.", present_bn="আমাকে ফাইলটা পাঠাও।",
      past="He sent an email.", past_bn="সে একটি ইমেইল পাঠিয়েছিল।"),
    V("pay", "paid", "paid", "paying", "pays", "/peɪ/",
      "to give money for something", "টাকা দেওয়া",
      cefr="A1", irregular=True,
      present="How much do I pay?", present_bn="আমাকে কত দিতে হবে?",
      past="They paid the bill.", past_bn="তারা বিল পরিশোধ করেছিল।"),
    V("forget", "forgot", "forgotten", "forgetting", "forgets", "/fəˈɡet/",
      "to not remember", "ভুলে যাওয়া",
      cefr="A1", irregular=True,
      present="Don't forget your ID.", present_bn="আইডি ভুলো না।",
      past="I forgot her name.", past_bn="আমি তার নাম ভুলে গিয়েছিলাম।"),
    V("remember", "remembered", "remembered", "remembering", "remembers", "/rɪˈmembə/",
      "to keep something in your mind", "মনে রাখা",
      cefr="A1",
      present="I remember that day.", present_bn="আমি সেই দিনটা মনে আছে।",
      past="She remembered the answer.", past_bn="সে উত্তরটা মনে করেছিল।"),
    V("understand", "understood", "understood", "understanding", "understands", "/ˌʌndəˈstænd/",
      "to know the meaning of something", "বুঝতে পারা",
      cefr="A1", irregular=True,
      present="Do you understand?", present_bn="তুমি কি বুঝতে পারছ?",
      past="He understood the problem.", past_bn="সে সমস্যাটা বুঝেছিল।"),
    V("look", "looked", "looked", "looking", "looks", "/lʊk/",
      "to turn your eyes towards something", "তাকানো / দেখা",
      cefr="A1",
      present="Look at the board.", present_bn="বোর্ডের দিকে তাকাও।",
      past="She looked tired.", past_bn="তাকে ক্লান্ত লাগছিল।"),
    V("hear", "heard", "heard", "hearing", "hears", "/hɪə/",
      "to notice sound with your ears", "শোনা",
      cefr="A1", irregular=True,
      present="I hear music.", present_bn="আমি গান শুনতে পাচ্ছি।",
      past="We heard a noise.", past_bn="আমরা একটি শব্দ শুনেছিলাম।"),
    V("lose", "lost", "lost", "losing", "loses", "/luːz/",
      "to not keep; to be defeated", "হারানো / হারা",
      cefr="A2", irregular=True,
      present="Don't lose your ticket.", present_bn="টিকিট হারিও না।",
      past="He lost his phone.", past_bn="সে তার ফোন হারিয়েছিল।"),
    V("win", "won", "won", "winning", "wins", "/wɪn/",
      "to be first in a contest", "জয় করা",
      cefr="A2", irregular=True,
      present="I hope we win.", present_bn="আশা করি আমরা জিতব।",
      past="She won the prize.", past_bn="সে পুরস্কার জিতেছিল।"),
    V("become", "became", "become", "becoming", "becomes", "/bɪˈkʌm/",
      "to start to be something", "হয়ে ওঠা",
      cefr="A2", irregular=True,
      present="It becomes dark early.", present_bn="তাড়াতাড়ি অন্ধকার হয়ে যায়।",
      past="He became a teacher.", past_bn="সে শিক্ষক হয়েছিলেন।"),
    V("mean", "meant", "meant", "meaning", "means", "/miːn/",
      "to have a particular meaning", "মানে হওয়া / বোঝানো",
      cefr="A1", irregular=True,
      present="What does this word mean?", present_bn="এই শব্দের মানে কী?",
      past="I meant to call you.", past_bn="আমি তোমাকে ফোন করতে চেয়েছিলাম।"),
    V("choose", "chose", "chosen", "choosing", "chooses", "/tʃuːz/",
      "to pick one thing from options", "বেছে নেওয়া",
      cefr="A2", irregular=True,
      present="Choose the best answer.", present_bn="সেরা উত্তর বেছে নাও।",
      past="They chose a quiet hotel.", past_bn="তারা শান্ত হোটেল বেছে নিয়েছিল।"),
    V("grow", "grew", "grown", "growing", "grows", "/ɡrəʊ/",
      "to become bigger", "বাড়া / বেড়ে ওঠা",
      cefr="A2", irregular=True, category="nature",
      present="Children grow quickly.", present_bn="শিশুরা দ্রুত বাড়ে।",
      past="The city grew fast.", past_bn="শহর দ্রুত বেড়েছিল।"),
    V("open", "opened", "opened", "opening", "opens", "/ˈəʊpən/",
      "to make something not closed", "খোলা",
      cefr="A1",
      present="Open your books.", present_bn="বই খোলো।",
      past="The shop opened at 10.", past_bn="দোকান ১০টায় খুলেছিল।"),
    V("close", "closed", "closed", "closing", "closes", "/kləʊz/",
      "to shut something", "বন্ধ করা",
      cefr="A1",
      present="Please close the door.", present_bn="দয়া করে দরজা বন্ধ করুন।",
      past="They closed the office early.", past_bn="তারা অফিস তাড়াতাড়ি বন্ধ করেছিল।"),
    V("stay", "stayed", "stayed", "staying", "stays", "/steɪ/",
      "to remain in a place", "থাকা / অবস্থান করা",
      cefr="A1",
      present="Stay here, please.", present_bn="এখানে থাকুন।",
      past="We stayed with relatives.", past_bn="আমরা আত্মীয়দের কাছে ছিলাম।"),
    V("happen", "happened", "happened", "happening", "happens", "/ˈhæpən/",
      "to take place", "ঘটা",
      cefr="A2",
      present="What happens next?", present_bn="এরপর কী হয়?",
      past="The accident happened at night.", past_bn="দুর্ঘটনা রাতে ঘটেছিল।"),
    # IELTS / academic
    V("analyse", "analysed", "analysed", "analysing", "analyses", "/ˈænəlaɪz/",
      "to examine in detail", "বিশ্লেষণ করা",
      cefr="B1", category="ielts",
      present="Students analyse the graph.", present_bn="শিক্ষার্থীরা গ্রাফ বিশ্লেষণ করে।",
      past="The report analysed the data.", past_bn="রিপোর্টটি তথ্য বিশ্লেষণ করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("argue", "argued", "argued", "arguing", "argues", "/ˈɑːɡjuː/",
      "to give reasons for an opinion", "যুক্তি দেওয়া / তর্ক করা",
      cefr="B1", category="ielts",
      present="Some people argue that cities are too crowded.", present_bn="কেউ কেউ যুক্তি দেন শহর খুব ভিড়।",
      past="The essay argued both sides.", past_bn="রচনাটি দুই পক্ষের যুক্তি দিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("demonstrate", "demonstrated", "demonstrated", "demonstrating", "demonstrates", "/ˈdemənstreɪt/",
      "to show clearly with evidence", "প্রমাণ করে দেখানো",
      cefr="B2", category="ielts",
      present="The chart demonstrates a rise in sales.", present_bn="চার্ট বিক্রিতে বৃদ্ধি দেখায়।",
      past="The study demonstrated the benefits.", past_bn="গবেষণা উপকার প্রমাণ করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("illustrate", "illustrated", "illustrated", "illustrating", "illustrates", "/ˈɪləstreɪt/",
      "to make clear with an example", "উদাহরণ দিয়ে বোঝানো",
      cefr="B2", category="ielts",
      present="This example illustrates the problem.", present_bn="এই উদাহরণ সমস্যাটা বোঝায়।",
      past="The teacher illustrated the rule.", past_bn="শিক্ষক নিয়মটা উদাহরণ দিয়ে বুঝিয়েছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("indicate", "indicated", "indicated", "indicating", "indicates", "/ˈɪndɪkeɪt/",
      "to show or point to something", "ইঙ্গিত করা / দেখানো",
      cefr="B1", category="ielts",
      present="The figures indicate a decline.", present_bn="সংখ্যাগুলো হ্রাসের ইঙ্গিত দেয়।",
      past="Results indicated improvement.", past_bn="ফলাফল উন্নতির ইঙ্গিত দিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("suggest", "suggested", "suggested", "suggesting", "suggests", "/səˈdʒest/",
      "to put forward an idea", "প্রস্তাব করা / ইঙ্গিত করা",
      cefr="B1", category="ielts",
      present="I suggest taking a break.", present_bn="আমি বিরতি নেওয়ার পরামর্শ দিই।",
      past="The data suggested a link.", past_bn="তথ্য একটি যোগসূত্রের ইঙ্গিত দিয়েছিল।",
      gerund_ex="I suggest practising every day.", gerund_ex_bn="প্রতিদিন অনুশীলনের পরামর্শ দিই।",
      tags=["verb", "grammar", "ielts"]),
    V("contribute", "contributed", "contributed", "contributing", "contributes", "/kənˈtrɪbjuːt/",
      "to help cause something", "অবদান রাখা",
      cefr="B2", category="ielts",
      present="Exercise contributes to health.", present_bn="ব্যায়াম স্বাস্থ্যে অবদান রাখে।",
      past="Many factors contributed to the change.", past_bn="অনেক কারণ পরিবর্তনে অবদান রেখেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("remain", "remained", "remained", "remaining", "remains", "/rɪˈmeɪn/",
      "to stay the same or stay behind", "অপরিবর্তিত থাকা / থেকে যাওয়া",
      cefr="B1", category="ielts",
      present="Unemployment remains high.", present_bn="বেকারত্ব এখনও বেশি।",
      past="The rate remained stable.", past_bn="হার স্থিতিশীল ছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("compare", "compared", "compared", "comparing", "compares", "/kəmˈpeə/",
      "to look at similarities and differences", "তুলনা করা",
      cefr="B1", category="ielts",
      present="Compare the two graphs.", present_bn="দুই গ্রাফ তুলনা করো।",
      past="The essay compared urban and rural life.", past_bn="রচনা শহর ও গ্রামের জীবন তুলনা করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("emphasise", "emphasised", "emphasised", "emphasising", "emphasises", "/ˈemfəsaɪz/",
      "to give special importance", "জোর দেওয়া",
      cefr="B2", category="ielts",
      present="The author emphasises education.", present_bn="লেখক শিক্ষার উপর জোর দেন।",
      past="The speaker emphasised safety.", past_bn="বক্তা নিরাপত্তায় জোর দিয়েছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("assess", "assessed", "assessed", "assessing", "assesses", "/əˈses/",
      "to judge the quality or amount", "মূল্যায়ন করা",
      cefr="B2", category="education",
      present="Teachers assess students' work.", present_bn="শিক্ষকরা শিক্ষার্থীর কাজ মূল্যায়ন করেন।",
      past="The risk was assessed carefully.", past_bn="ঝুঁকি সাবধানে মূল্যায়ন করা হয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("evaluate", "evaluated", "evaluated", "evaluating", "evaluates", "/ɪˈvæljueɪt/",
      "to judge after careful thought", "মূল্যায়ন করে সিদ্ধান্ত নেওয়া",
      cefr="B2", category="ielts",
      present="Evaluate both arguments.", present_bn="দুই যুক্তি মূল্যায়ন করো।",
      past="The committee evaluated the plan.", past_bn="কমিটি পরিকল্পনা মূল্যায়ন করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("require", "required", "required", "requiring", "requires", "/rɪˈkwaɪə/",
      "to need something as necessary", "প্রয়োজন হওয়া / আবশ্যক করা",
      cefr="B1", category="ielts",
      present="The job requires patience.", present_bn="কাজটিতে ধৈর্য লাগে।",
      past="The form required a signature.", past_bn="ফর্মে স্বাক্ষর লাগত।",
      tags=["verb", "grammar", "ielts"]),
    V("reduce", "reduced", "reduced", "reducing", "reduces", "/rɪˈdjuːs/",
      "to make smaller in amount", "কমানো",
      cefr="B1", category="ielts",
      present="We should reduce plastic use.", present_bn="প্লাস্টিক ব্যবহার কমানো উচিত।",
      past="The government reduced taxes.", past_bn="সরকার কর কমিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("improve", "improved", "improved", "improving", "improves", "/ɪmˈpruːv/",
      "to make or become better", "উন্নতি করা / উন্নত করা",
      cefr="A2", category="education",
      present="Practice improves your English.", present_bn="অনুশীলন ইংরেজি উন্নত করে।",
      past="Her score improved last month.", past_bn="গত মাসে তার স্কোর বেড়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("affect", "affected", "affected", "affecting", "affects", "/əˈfekt/",
      "to have an influence on", "প্রভাব ফেলা",
      cefr="B1", category="ielts",
      present="Pollution affects health.", present_bn="দূষণ স্বাস্থ্যে প্রভাব ফেলে।",
      past="The delay affected the result.", past_bn="বিলম্ব ফলাফলে প্রভাব ফেলেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("imply", "implied", "implied", "implying", "implies", "/ɪmˈplaɪ/",
      "to suggest without saying directly", "ইঙ্গিতে বোঝানো",
      cefr="B2", category="ielts",
      present="The writer implies a warning.", present_bn="লেখক একটি সতর্কবার্তা ইঙ্গিত করেন।",
      past="The article implied bias.", past_bn="প্রবন্ধটি পক্ষপাতের ইঙ্গিত দিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("infer", "inferred", "inferred", "inferring", "infers", "/ɪnˈfɜː/",
      "to reach a conclusion from clues", "অনুমান করা / সিদ্ধান্ত টানা",
      cefr="B2", category="ielts",
      present="Readers infer the meaning from context.", present_bn="পাঠক প্রসঙ্গ থেকে অর্থ অনুমান করে।",
      past="We inferred that demand had fallen.", past_bn="আমরা অনুমান করেছিলাম চাহিদা কমেছে।",
      tags=["verb", "grammar", "ielts"]),
    V("claim", "claimed", "claimed", "claiming", "claims", "/kleɪm/",
      "to say something is true", "দাবি করা",
      cefr="B1", category="ielts",
      present="Some experts claim it is safer.", present_bn="কিছু বিশেষজ্ঞ দাবি করেন এটা নিরাপদ।",
      past="The company claimed success.", past_bn="কোম্পানি সাফল্য দাবি করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("reveal", "revealed", "revealed", "revealing", "reveals", "/rɪˈviːl/",
      "to make something known", "প্রকাশ করা",
      cefr="B2", category="ielts",
      present="The survey reveals public opinion.", present_bn="জরিপ জনমত প্রকাশ করে।",
      past="The study revealed a gap.", past_bn="গবেষণা একটি ফাঁক প্রকাশ করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("describe", "described", "described", "describing", "describes", "/dɪˈskraɪb/",
      "to say what something is like", "বর্ণনা করা",
      cefr="A2", category="ielts",
      present="Describe your hometown.", present_bn="তোমার শহরের বর্ণনা দাও।",
      past="She described the process clearly.", past_bn="সে প্রক্রিয়া স্পষ্ট করে বর্ণনা করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("prefer", "preferred", "preferred", "preferring", "prefers", "/prɪˈfɜː/",
      "to like one thing more than another", "বেশি পছন্দ করা",
      cefr="A2",
      present="I prefer tea to coffee.", present_bn="কফির চেয়ে চা বেশি পছন্দ করি।",
      past="He preferred studying at night.", past_bn="সে রাতে পড়তে বেশি পছন্দ করত।",
      gerund_ex="I prefer studying in the morning.", gerund_ex_bn="সকালে পড়া বেশি পছন্দ করি।",
      tags=["verb", "grammar", "ielts"]),
    V("enjoy", "enjoyed", "enjoyed", "enjoying", "enjoys", "/ɪnˈdʒɔɪ/",
      "to get pleasure from something", "উপভোগ করা",
      cefr="A1",
      present="I enjoy cooking.", present_bn="আমি রান্না উপভোগ করি।",
      past="They enjoyed the trip.", past_bn="তারা ভ্রমণ উপভোগ করেছিল।",
      gerund_ex="She enjoys speaking English.", gerund_ex_bn="সে ইংরেজিতে কথা বলা উপভোগ করে।"),
    V("explain", "explained", "explained", "explaining", "explains", "/ɪkˈspleɪn/",
      "to make something clear", "ব্যাখ্যা করা",
      cefr="A2", category="education",
      present="Can you explain this word?", present_bn="এই শব্দটা ব্যাখ্যা করতে পারবে?",
      past="The teacher explained the rule.", past_bn="শিক্ষক নিয়ম ব্যাখ্যা করেছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("discuss", "discussed", "discussed", "discussing", "discusses", "/dɪˈskʌs/",
      "to talk about a topic in detail", "আলোচনা করা",
      cefr="B1", category="ielts",
      present="We will discuss both views.", present_bn="আমরা দুই মত আলোচনা করব।",
      past="The class discussed climate change.", past_bn="ক্লাস জলবায়ু পরিবর্তন আলোচনা করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("consider", "considered", "considered", "considering", "considers", "/kənˈsɪdə/",
      "to think carefully about", "বিবেচনা করা",
      cefr="B1", category="ielts",
      present="Consider the disadvantages too.", present_bn="অসুবিধাগুলোও বিবেচনা করো।",
      past="She considered studying abroad.", past_bn="সে বিদেশে পড়ার কথা ভেবেছিল।",
      gerund_ex="I am considering changing my plan.", gerund_ex_bn="আমি পরিকল্পনা বদলানোর কথা ভাবছি।",
      tags=["verb", "grammar", "ielts"]),
    V("recommend", "recommended", "recommended", "recommending", "recommends", "/ˌrekəˈmend/",
      "to say something is good to do", "সুপারিশ করা",
      cefr="B1", category="ielts",
      present="I recommend reading newspapers.", present_bn="খবরের কাগজ পড়ার সুপারিশ করি।",
      past="The doctor recommended rest.", past_bn="ডাক্তার বিশ্রামের পরামর্শ দিয়েছিলেন।",
      gerund_ex="I recommend practising aloud.", gerund_ex_bn="জোরে অনুশীলনের সুপারিশ করি।",
      tags=["verb", "grammar", "ielts"]),
    V("expect", "expected", "expected", "expecting", "expects", "/ɪkˈspekt/",
      "to think something will happen", "আশা করা / প্রত্যাশা করা",
      cefr="A2",
      present="I expect a high score.", present_bn="আমি উচ্চ স্কোর আশা করি।",
      past="We expected more visitors.", past_bn="আমরা আরও দর্শনার্থী আশা করেছিলাম।"),
    V("enable", "enabled", "enabled", "enabling", "enables", "/ɪˈneɪbl/",
      "to make something possible", "সম্ভব করা",
      cefr="B2", category="ielts",
      present="Technology enables remote work.", present_bn="প্রযুক্তি দূর থেকে কাজ সম্ভব করে।",
      past="The grant enabled the project.", past_bn="অনুদান প্রকল্প সম্ভব করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("represent", "represented", "represented", "representing", "represents", "/ˌreprɪˈzent/",
      "to stand for; to show", "প্রতিনিধিত্ব করা / নির্দেশ করা",
      cefr="B1", category="ielts",
      present="The blue line represents imports.", present_bn="নীল রেখা আমদানি নির্দেশ করে।",
      past="She represented her school.", past_bn="সে তার স্কুলের প্রতিনিধিত্ব করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("decline", "declined", "declined", "declining", "declines", "/dɪˈklaɪn/",
      "to become smaller or weaker", "কমতে থাকা / প্রত্যাখ্যান করা",
      cefr="B2", category="ielts",
      present="Sales decline in winter.", present_bn="শীতকালে বিক্রি কমে।",
      past="The population declined.", past_bn="জনসংখ্যা কমেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("fluctuate", "fluctuated", "fluctuated", "fluctuating", "fluctuates", "/ˈflʌktʃueɪt/",
      "to rise and fall irregularly", "ওঠানামা করা",
      cefr="B2", category="ielts",
      present="Prices fluctuate each month.", present_bn="প্রতি মাসে দাম ওঠানামা করে।",
      past="The figures fluctuated widely.", past_bn="সংখ্যাগুলো ব্যাপক ওঠানামা করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("outline", "outlined", "outlined", "outlining", "outlines", "/ˈaʊtlaɪn/",
      "to give the main points", "মূল বিষয় তুলে ধরা",
      cefr="B2", category="ielts",
      present="Outline your main ideas first.", present_bn="আগে মূল ধারণাগুলো লিখে নাও।",
      past="The introduction outlined the topic.", past_bn="ভূমিকা বিষয়টি তুলে ধরেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("predict", "predicted", "predicted", "predicting", "predicts", "/prɪˈdɪkt/",
      "to say what will happen", "ভবিষ্যদ্বাণী করা",
      cefr="B1", category="ielts",
      present="Experts predict higher demand.", present_bn="বিশেষজ্ঞরা বেশি চাহিদার পূর্বাভাস দেন।",
      past="The model predicted rainfall.", past_bn="মডেল বৃষ্টির পূর্বাভাস দিয়েছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("identify", "identified", "identified", "identifying", "identifies", "/aɪˈdentɪfaɪ/",
      "to recognise and name", "শনাক্ত করা",
      cefr="B1", category="ielts",
      present="Identify the main idea.", present_bn="মূল ভাব শনাক্ত করো।",
      past="Researchers identified the cause.", past_bn="গবেষকরা কারণ শনাক্ত করেছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("conclude", "concluded", "concluded", "concluding", "concludes", "/kənˈkluːd/",
      "to decide after evidence; to finish", "সিদ্ধান্তে পৌঁছানো / শেষ করা",
      cefr="B1", category="ielts",
      present="We can conclude that practice works.", present_bn="সিদ্ধান্তে পৌঁছানো যায় অনুশীলন কাজ করে।",
      past="The author concluded with a warning.", past_bn="লেখক সতর্কবার্তা দিয়ে শেষ করেছিলেন।",
      tags=["verb", "grammar", "ielts"]),
    V("mention", "mentioned", "mentioned", "mentioning", "mentions", "/ˈmenʃn/",
      "to say something briefly", "উল্লেখ করা",
      cefr="A2", category="ielts",
      present="Please mention one example.", present_bn="একটি উদাহরণ উল্লেখ করুন।",
      past="He mentioned his hometown.", past_bn="সে তার শহরের কথা উল্লেখ করেছিল।",
      tags=["verb", "grammar", "ielts"]),
    V("notice", "noticed", "noticed", "noticing", "notices", "/ˈnəʊtɪs/",
      "to become aware of something", "লক্ষ্য করা",
      cefr="A2",
      present="Did you notice the change?", present_bn="পরিবর্তন লক্ষ্য করেছ?",
      past="I noticed a spelling mistake.", past_bn="আমি একটি বানান ভুল লক্ষ্য করেছিলাম।"),
    V("spend", "spent", "spent", "spending", "spends", "/spend/",
      "to use time or money", "খরচ করা / কাটানো",
      cefr="A1", irregular=True,
      present="I spend two hours studying.", present_bn="আমি দুই ঘণ্টা পড়াশোনা করি।",
      past="She spent the weekend at home.", past_bn="সে সপ্তাহান্তে বাড়িতে কাটিয়েছিল।"),
    V("visit", "visited", "visited", "visiting", "visits", "/ˈvɪzɪt/",
      "to go to a place for a short time", "ঘুরতে যাওয়া / সাক্ষাৎ করা",
      cefr="A1", category="travel",
      present="We visit our grandparents every Eid.", present_bn="প্রতি ঈদে আমরা দাদা-দাদির কাছে যাই।",
      past="They visited Cox's Bazar.", past_bn="তারা কক্সবাজার ঘুরতে গিয়েছিল।"),
    V("agree", "agreed", "agreed", "agreeing", "agrees", "/əˈɡriː/",
      "to have the same opinion", "একমত হওয়া",
      cefr="A2",
      present="I agree with you.", present_bn="আমি তোমার সঙ্গে একমত।",
      past="They agreed on a plan.", past_bn="তারা একটি পরিকল্পনায় একমত হয়েছিল।"),
]

LISTS = [
    {
        "id": "vf-daily-conversation",
        "title": "Daily Conversation Verbs",
        "title_bn": "দৈনন্দিন কথোপকথনের ক্রিয়া",
        "description": "Most common verbs for everyday speaking.",
        "description_bn": "প্রতিদিনের কথাবার্তার সবচেয়ে দরকারি verb।",
        "cefr": "A1–A2",
        "word_ids": [
            "verb:be", "verb:have", "verb:do", "verb:go", "verb:come", "verb:get",
            "verb:give", "verb:take", "verb:make", "verb:say", "verb:tell", "verb:ask",
            "verb:want", "verb:need", "verb:like", "verb:live", "verb:use", "verb:call",
            "verb:wait", "verb:walk", "verb:talk", "verb:eat", "verb:drink", "verb:buy",
            "verb:put", "verb:sit", "verb:stand", "verb:leave", "verb:stay", "verb:look",
            "verb:see", "verb:hear", "verb:feel", "verb:know", "verb:think", "verb:meet",
            "verb:help", "verb:try", "verb:start", "verb:stop", "verb:play", "verb:watch",
            "verb:open", "verb:close", "verb:send", "verb:pay", "verb:forget", "verb:remember",
            "verb:understand", "verb:mean",
        ],
    },
    {
        "id": "vf-irregular-core",
        "title": "Irregular Verbs Core",
        "title_bn": "অনিয়মিত ক্রিয়া — মূল তালিকা",
        "description": "High-frequency irregular V1–V5 forms.",
        "description_bn": "সবচেয়ে চালু irregular verb-এর V1–V5।",
        "cefr": "A1–B1",
        "word_ids": [
            "verb:be", "verb:have", "verb:do", "verb:go", "verb:come", "verb:get",
            "verb:give", "verb:take", "verb:make", "verb:know", "verb:think", "verb:see",
            "verb:say", "verb:tell", "verb:write", "verb:read", "verb:speak", "verb:run",
            "verb:eat", "verb:drink", "verb:sleep", "verb:buy", "verb:find", "verb:feel",
            "verb:begin", "verb:break", "verb:meet", "verb:bring", "verb:show", "verb:keep",
            "verb:put", "verb:sit", "verb:stand", "verb:leave", "verb:send", "verb:pay",
            "verb:forget", "verb:understand", "verb:hear", "verb:lose", "verb:win",
            "verb:become", "verb:mean", "verb:choose", "verb:grow", "verb:spend",
        ],
    },
    {
        "id": "vf-ielts-speaking",
        "title": "IELTS Speaking Verbs",
        "title_bn": "IELTS স্পিকিং ক্রিয়া",
        "description": "Useful verbs for Part 1–3 answers (unofficial).",
        "description_bn": "Part 1–3 উত্তরের দরকারি verb (অনঅফিসিয়াল)।",
        "cefr": "A2–B2",
        "word_ids": [
            "verb:describe", "verb:prefer", "verb:enjoy", "verb:remember", "verb:explain",
            "verb:mention", "verb:discuss", "verb:consider", "verb:recommend", "verb:suggest",
            "verb:notice", "verb:expect", "verb:agree", "verb:visit", "verb:spend",
            "verb:live", "verb:like", "verb:want", "verb:need", "verb:think",
            "verb:feel", "verb:know", "verb:speak", "verb:listen", "verb:meet",
            "verb:help", "verb:try", "verb:learn", "verb:study", "verb:work",
        ],
    },
    {
        "id": "vf-ielts-writing",
        "title": "IELTS Writing Verbs",
        "title_bn": "IELTS রাইটিং ক্রিয়া",
        "description": "Task 1–2 academic verbs: graphs, essays (unofficial).",
        "description_bn": "টাস্ক ১–২ গ্রাফ ও রচনার academic verb (অনঅফিসিয়াল)।",
        "cefr": "B1–C1",
        "word_ids": [
            "verb:increase", "verb:decline", "verb:remain", "verb:fluctuate", "verb:represent",
            "verb:indicate", "verb:illustrate", "verb:demonstrate", "verb:compare", "verb:outline",
            "verb:analyse", "verb:argue", "verb:emphasise", "verb:assess", "verb:evaluate",
            "verb:suggest", "verb:claim", "verb:conclude", "verb:contribute", "verb:require",
            "verb:reduce", "verb:improve", "verb:affect", "verb:enable", "verb:predict",
            "verb:show", "verb:keep", "verb:avoid", "verb:achieve", "verb:decide",
        ],
    },
    {
        "id": "vf-ielts-reading",
        "title": "IELTS Reading Verbs",
        "title_bn": "IELTS রিডিং ক্রিয়া",
        "description": "Passage verbs for TFNG and matching headings (unofficial).",
        "description_bn": "প্যাসেজের TFNG ও heading মিলানোর verb (অনঅফিসিয়াল)।",
        "cefr": "B1–C1",
        "word_ids": [
            "verb:imply", "verb:infer", "verb:claim", "verb:reveal", "verb:indicate",
            "verb:suggest", "verb:demonstrate", "verb:identify", "verb:conclude", "verb:assess",
            "verb:evaluate", "verb:analyse", "verb:compare", "verb:emphasise", "verb:illustrate",
            "verb:argue", "verb:consider", "verb:require", "verb:affect", "verb:contribute",
            "verb:remain", "verb:enable", "verb:represent", "verb:outline", "verb:predict",
        ],
    },
    {
        "id": "vf-regular-starter",
        "title": "Regular Verbs Starter",
        "title_bn": "নিয়মিত ক্রিয়া — শুরু",
        "description": "Regular -ed pattern with V1–V5.",
        "description_bn": "নিয়মিত -ed প্যাটার্ন V1–V5 সহ।",
        "cefr": "A1–B1",
        "word_ids": [
            "verb:ask", "verb:want", "verb:need", "verb:like", "verb:live", "verb:use",
            "verb:call", "verb:wait", "verb:walk", "verb:talk", "verb:start", "verb:stop",
            "verb:play", "verb:watch", "verb:open", "verb:close", "verb:stay", "verb:help",
            "verb:try", "verb:work", "verb:learn", "verb:study", "verb:listen", "verb:decide",
            "verb:accept", "verb:avoid", "verb:enjoy", "verb:explain", "verb:visit", "verb:agree",
        ],
    },
]


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    bank = load_json(VERB_DATA)
    by_id = {v["id"]: i for i, v in enumerate(bank)}
    added = 0
    updated = 0
    for v in NEW_VERBS:
        if v["id"] in by_id:
            bank[by_id[v["id"]]] = v
            updated += 1
        else:
            bank.append(v)
            by_id[v["id"]] = len(bank) - 1
            added += 1
    save_json(VERB_DATA, bank)

    meta = load_json(VLISTS)
    lists = meta.get("lists") or []
    by_list = {L.get("id"): i for i, L in enumerate(lists)}

    master_ids = [v["id"] for v in bank]
    lists_to_write = LISTS + [
        {
            "id": "verb-forms-master",
            "title": "Verb Forms Master List",
            "title_bn": "ক্রিয়া রূপ মাস্টার লিস্ট",
            "description": "All verb forms with V1–V5, gerund and participle usage.",
            "description_bn": "সব verb-এর V1–V5 + gerund ও participle ব্যবহার।",
            "cefr": "A1–C1",
            "word_ids": master_ids,
        }
    ]
    for entry in lists_to_write:
        if entry["id"] in by_list:
            lists[by_list[entry["id"]]] = entry
        else:
            lists.append(entry)
            by_list[entry["id"]] = len(lists) - 1
    meta["lists"] = lists
    save_json(VLISTS, meta)

    print(f"verb-forms.json: {len(bank)} total (+{added} new, {updated} updated)")
    print("lists:", ", ".join(e["id"] for e in lists_to_write))


if __name__ == "__main__":
    main()
